dxFeed Graal CXX API: dxfcpp::SimpleHandler< void(ArgTypes...)> Struct Template Reference
dxfcpp::SimpleHandler< void(ArgTypes...)> Struct Template Reference final
A thread-safe class that allows to asynchronously notify listeners with a given signature.
#include <Handler.hpp>
Public Member Functions
SimpleHandler () noexcept=default
Creates the new handler.
void handle (ArgTypes... args)
Calls the listeners and pass the args to them.
void operator() (ArgTypes... args)
Calls the listeners and pass the ars to them.
std::size_t add (ListenerType &&listener)
Adds the listener to "main" group.
std::size_t addLowPriority (ListenerType &&listener)
Adds the low priority listener (to the "low priority" group) It will be called after the "main" listeners.
std::size_t operator+= (ListenerType &&listener)
Adds the listener to "main" group.
std::size_t operator%= (ListenerType &&listener)
Adds the low priority listener (to the "low priority" group).
void remove (std::size_t id)
Removes a listener by the id.
void operator-= (std::size_t id)
Removes a listener by the id.
Detailed Description
template<typename... ArgTypes>
struct dxfcpp::SimpleHandler< void(ArgTypes...)>
A thread-safe class that allows to asynchronously notify listeners with a given signature.
Listeners can be any callable entities. Listeners are placed in one future without queues.
Template Parameters
ArgTypes The arguments "signature" (example: void(int, int))
Member Function Documentation
add()
template<typename... ArgTypes> std::size_t dxfcpp::SimpleHandler< void(ArgTypes...)>::add (ListenerType && listener) inline
Adds the listener to "main" group.
Parameters
listener The listener
Returns
The listener id
Referenced by operator+=().
addLowPriority()
template<typename... ArgTypes> std::size_t dxfcpp::SimpleHandler< void(ArgTypes...)>::addLowPriority (ListenerType && listener) inline
Adds the low priority listener (to the "low priority" group) It will be called after the "main" listeners.
Parameters
listener The listener
Returns
The listener id
Referenced by operator%=().
handle()
template<typename... ArgTypes> void dxfcpp::SimpleHandler< void(ArgTypes...)>::handle (ArgTypes... args) inline
Calls the listeners and pass the args to them.
Parameters
args The listeners arguments
Referenced by operator()().
operator%=()
template<typename... ArgTypes> std::size_t dxfcpp::SimpleHandler< void(ArgTypes...)>::operator%= (ListenerType && listener) inline
Adds the low priority listener (to the "low priority" group).
It will be called after the "main" listeners
Parameters
listener The listener
Returns
The listener id
References addLowPriority().
operator()()
template<typename... ArgTypes> void dxfcpp::SimpleHandler< void(ArgTypes...)>::operator() (ArgTypes... args) inline
Calls the listeners and pass the ars to them.
Parameters
args The listeners arguments
References handle().
operator+=()
template<typename... ArgTypes> std::size_t dxfcpp::SimpleHandler< void(ArgTypes...)>::operator+= (ListenerType && listener) inline
Adds the listener to "main" group.
Parameters
listener The listener
Returns
The listener id
References add().
operator-=()
template<typename... ArgTypes> void dxfcpp::SimpleHandler< void(ArgTypes...)>::operator-= (std::size_t id) inline
Removes a listener by the id.
Parameters
id The listener id
References remove().
Referenced by dxfcpp::InstrumentProfileConnection::removeStateChangeListener().
remove()
template<typename... ArgTypes> void dxfcpp::SimpleHandler< void(ArgTypes...)>::remove (std::size_t id) inline
Removes a listener by the id.
Parameters
id The listener id
Referenced by operator-=().