dxFeed Graal CXX API: TimeAndSale Class Reference
TimeAndSale Class Reference final
Time and Sale represents a trade or other market event with price, like market open/close price, etc.
#include <TimeAndSale.hpp>
Public Types
using Ptr = std::shared_ptr< TimeAndSale >
The alias to a type of shared pointer to the TimeAndSale object.
using Unique = std::unique_ptr< TimeAndSale >
The alias to a type of unique pointer to the TimeAndSale object.
Public Types inherited from MarketEvent
using Ptr = std::shared_ptr< MarketEvent >
The alias to a type of shared pointer to the MarketEvent object.
Public Types inherited from EventTypeWithSymbol< std::string >
using Ptr = std::shared_ptr< EventTypeWithSymbol< std::string > >
The alias to a type of shared pointer to the EventTypeWithSymbol's child object.
Public Types inherited from EventType
using Ptr = std::shared_ptr< EventType >
The alias to a type of shared pointer to the EventType object.
Public Types inherited from SharedEntity
using Ptr = std::shared_ptr< SharedEntity >
The alias to a type of shared pointer to the SharedEntity object.
Public Types inherited from TimeSeriesEvent
using Ptr = std::shared_ptr< TimeSeriesEvent >
The alias to a type of shared pointer to the TimeSeriesEvent object.
Public Types inherited from IndexedEvent
using Ptr = std::shared_ptr< IndexedEvent >
The alias to a type of shared pointer to the IndexedEvent object.
Public Member Functions
void * toGraal () const override
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
TimeAndSale () noexcept=default
Creates new time and sale event with default values.
TimeAndSale (std::string eventSymbol) noexcept
Creates new time and sale event with the specified event symbol.
const IndexedEventSource & getSource () const &noexcept override
Returns the source of this event.
std::int32_t getEventFlags () const noexcept override
Returns transactional event flags.
EventFlagsMask getEventFlagsMask () const noexcept override
Returns transactional event flags.
void setEventFlags (std::int32_t eventFlags) noexcept override
Changes transactional event flags.
void setEventFlags (const EventFlagsMask &eventFlags) noexcept override
Changes transactional event flags.
std::int64_t getIndex () const noexcept override
Returns unique per-symbol index of this event.
void setIndex (std::int64_t index) override
Changes unique per-symbol index of this event.
std::int64_t getTime () const noexcept override
Returns timestamp of the event in milliseconds.
void setTime (std::int64_t time) noexcept
Changes timestamp of the event in milliseconds.
std::int64_t getTimeNanos () const noexcept
Returns time of the original event in nanoseconds.
void setTimeNanos (std::int64_t timeNanos) noexcept
Changes time of the original event.
void setTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds time part of the original event.
std::int32_t getTimeNanoPart () const noexcept
Returns microseconds and nanoseconds time part of the original event.
std::int32_t getSequence () const noexcept
Returns the sequence number of this event to distinguish events that have the same time.
void setSequence (std::int32_t sequence)
Changes sequence number of this event.
std::int16_t getExchangeCode () const noexcept
Returns exchange code of this time and sale event.
std::string getExchangeCodeString () const noexcept
Returns exchange code of this time and sale event as UTF8 string.
void setExchangeCode (char exchangeCode) noexcept
Changes exchange code of this time and sale event.
void setExchangeCode (std::int16_t exchangeCode) noexcept
Changes exchange code of this time and sale event.
double getPrice () const noexcept
Returns price of this time and sale event.
void setPrice (double price) noexcept
Changes price of this time and sale event.
double getSize () const noexcept
Returns size of this time and sale event.
void setSize (double size) noexcept
Changes size of this time and sale event.
double getBidPrice () const noexcept
Returns the current bid price on the market when this time and sale event had occurred.
void setBidPrice (double bidPrice) noexcept
Changes the current bid price on the market when this time and sale event had occurred.
double getAskPrice () const noexcept
Returns the current ask price on the market when this time and sale event had occurred.
void setAskPrice (double askPrice) noexcept
Changes price of this time and sale event.the current ask price on the market when this time and sale event had occurred.
const std::string & getExchangeSaleConditions () const &noexcept
Returns sale conditions provided for this event by data feed.
const std::optional< std::string > & getExchangeSaleConditionsOpt () const &noexcept
Returns sale conditions provided for this event by data feed.
void setExchangeSaleConditions (std::string exchangeSaleConditions) noexcept
Changes sale conditions provided for this event by data feed.
char getTradeThroughExempt () const noexcept
Returns TradeThroughExempt flag of this time and sale event.
void setTradeThroughExempt (char tradeThroughExempt)
Changes TradeThroughExempt flag of this time and sale event.
const Side & getAggressorSide () const &noexcept
Returns aggressor side of this time and sale event.
void setAggressorSide (const Side &side) noexcept
Changes aggressor side of this time and sale event.
bool isSpreadLeg () const noexcept
Returns whether this event represents a spread leg.
void setSpreadLeg (bool spreadLeg) noexcept
Changes whether this event represents a spread leg.
bool isExtendedTradingHours () const noexcept
Returns whether this event represents an extended trading hours sale.
void setExtendedTradingHours (bool extendedTradingHours) noexcept
Changes whether this event represents an extended trading hours sale.
bool isValidTick () const noexcept
Returns whether this event represents a valid intraday tick.
void setValidTick (bool validTick) noexcept
Changes whether this event represents a valid intraday tick.
const TimeAndSaleType & getType () const &noexcept
Returns type of this time and sale event.
void setType (const TimeAndSaleType &type) noexcept
Changes type of this time and sale event.
bool isNew () const noexcept
Returns whether this is a new event (not cancellation or correction).
bool isCorrection () const noexcept
Returns whether this is a correction of a previous event.
bool isCancel () const noexcept
Returns whether this is a cancellation of a previous event.
const std::string & getBuyer () const &noexcept
Returns buyer of this time and sale event.
const std::optional< std::string > & getBuyerOpt () const &noexcept
Returns buyer of this time and sale event.
void setBuyer (std::string buyer) noexcept
Changes buyer of this time and sale event.
const std::string & getSeller () const &noexcept
Returns seller of this time and sale event.
const std::optional< std::string > & getSellerOpt () const &noexcept
Returns seller of this time and sale event.
void setSeller (std::string seller) noexcept
Changes seller of this time and sale event.
std::string toString () const noexcept override
Returns a string representation of the current object.
Public Member Functions inherited from MarketEvent
const std::string & getEventSymbol () const &noexcept override
Returns symbol of this event.
const std::optional< std::string > & getEventSymbolOpt () const &noexcept override
Returns symbol of this event.
void setEventSymbol (const std::string &eventSymbol) noexcept override
Changes symbol of this event.
std::int64_t getEventTime () const noexcept override
Returns time when event was created or zero when time is not available.
void setEventTime (std::int64_t eventTime) noexcept override
Changes event creation time.
Public Member Functions inherited from SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
Public Member Functions inherited from Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Public Member Functions inherited from TimeSeriesEvent
const IndexedEventSource & getSource () const &noexcept override
Returns the source identifier for this event, which is always DEFAULT for time-series events.
std::int64_t getIndex () const noexcept override
Returns unique per-symbol index of this event.
virtual std::int64_t getEventId () const noexcept
Returns unique per-symbol index of this event.
Static Public Member Functions
static Ptr fromGraal (void *graalNative)
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
static void freeGraal (void *graalNative)
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Attributes
static const EventTypeEnum & TYPE = EventTypeEnum::TIME_AND_SALE
Type identifier and additional information about the current event class.
static constexpr std::uint32_t MAX_SEQUENCE = (1U << 22U) - 1U
Maximum allowed sequence value.
Static Public Attributes inherited from IndexedEvent
static const EventFlag TX_PENDING = EventFlag::TX_PENDING
0x01 - A bitmask to get transaction pending indicator from the value of eventFlags property.
static const EventFlag REMOVE_EVENT = EventFlag::REMOVE_EVENT
0x02 - A bitmask to get removal indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_BEGIN = EventFlag::SNAPSHOT_BEGIN
0x04 - A bitmask to get snapshot begin indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_END = EventFlag::SNAPSHOT_END
0x08 - A bitmask to get snapshot end indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_SNIP = EventFlag::SNAPSHOT_SNIP
0x10 - A bitmask to get snapshot snip indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_MODE = EventFlag::SNAPSHOT_MODE
0x40 - A bitmask to set snapshot mode indicator into the value of eventFlags property.
Friends
class OptionSale
Additional Inherited Members
Protected Member Functions inherited from MarketEvent
MarketEvent (std::string eventSymbol) noexcept
Protected constructor for concrete implementation classes that initializes eventSymbol property.
Detailed Description
Time and Sale represents a trade or other market event with price, like market open/close price, etc.
Time and Sales are intended to provide information about trades in a continuous time slice (unlike Trade events which are supposed to provide snapshot about the current last trade).
Time and Sale events have unique index which can be used for later correction/cancellation processing.
Some time and sale sources provide a consistent view of the set of known time and sales for a given time range when used with DXFeedTimeSeriesSubscription}. The corresponding information is carried in eventFlags property. The logic behind this property is detailed in IndexedEvent class documentation. Multiple event sources for the same symbol are not supported for time and sales, thus source property is always DEFAULT.
Regular subscription via DXFeedSubscription produces a stream of time and sale events as they happen and their eventFlags are always zero.
Publishing of time and sales events follows the general rules explained in TimeSeriesEvent class documentation.
This event is implemented on top of QDS record TimeAndSale.
Constructor & Destructor Documentation
TimeAndSale()
TimeAndSale::TimeAndSale (std::string eventSymbol) inline explicit noexcept
Creates new time and sale event with the specified event symbol.
Parameters
eventSymbol The event symbol.
References MarketEvent::MarketEvent().
Member Function Documentation
freeGraal()
void TimeAndSale::freeGraal (void * graalNative) static
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
fromGraal()
std::shared_ptr< TimeAndSale > TimeAndSale::fromGraal (void * graalNative) static
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Returns
The object of current type.
Exceptions
std::invalid_argument
getAggressorSide()
const Side& TimeAndSale::getAggressorSide () const & inline noexcept
Returns aggressor side of this time and sale event.
Returns
aggressor side of this time and sale event.
getAskPrice()
double TimeAndSale::getAskPrice () const inline noexcept
Returns the current ask price on the market when this time and sale event had occurred.
Returns
the current ask price on the market when this time and sale event had occurred.
getBidPrice()
double TimeAndSale::getBidPrice () const inline noexcept
Returns the current bid price on the market when this time and sale event had occurred.
Returns
the current bid price on the market when this time and sale event had occurred.
getBuyer()
const std::string& TimeAndSale::getBuyer () const & inline noexcept
Returns buyer of this time and sale event.
Returns
buyer of this time and sale event or dxfcpp::String::NUL (std::string{"<null>"}).
getBuyerOpt()
const std::optional<std::string>& TimeAndSale::getBuyerOpt () const & inline noexcept
Returns buyer of this time and sale event.
Returns
buyer of this time and sale event or std::nullopt
getEventFlags()
std::int32_t TimeAndSale::getEventFlags () const inline override virtual noexcept
Returns transactional event flags.
See EventFlag "Event Flags" section.
Returns
The transactional event flags.
Implements IndexedEvent.
getEventFlagsMask()
EventFlagsMask TimeAndSale::getEventFlagsMask () const inline override virtual noexcept
Returns transactional event flags.
See EventFlag "Event Flags" section.
Returns
The transactional event flags' mask.
Implements IndexedEvent.
getExchangeCode()
std::int16_t TimeAndSale::getExchangeCode () const inline noexcept
Returns exchange code of this time and sale event.
Returns
exchange code of this time and sale event.
getExchangeCodeString()
std::string TimeAndSale::getExchangeCodeString () const inline noexcept
Returns exchange code of this time and sale event as UTF8 string.
Returns
exchange code of this time and sale event as UTF8 string.
getExchangeSaleConditions()
const std::string& TimeAndSale::getExchangeSaleConditions () const & inline noexcept
Returns sale conditions provided for this event by data feed.
This field format is specific for every particular data feed.
Returns
sale conditions or dxfcpp::String::NUL (std::string{"<null>"}).
getExchangeSaleConditionsOpt()
const std::optional<std::string>& TimeAndSale::getExchangeSaleConditionsOpt () const & inline noexcept
Returns sale conditions provided for this event by data feed.
This field format is specific for every particular data feed.
Returns
sale conditions or std::nullopt
getIndex()
std::int64_t TimeAndSale::getIndex () const inline override virtual noexcept
Returns unique per-symbol index of this event.
The index is composed of time and sequence. Changing either time or sequence changes event index.
Returns
unique index of this event.
Implements IndexedEvent.
getPrice()
double TimeAndSale::getPrice () const inline noexcept
Returns price of this time and sale event.
Returns
price of this time and sale event.
getSeller()
const std::string& TimeAndSale::getSeller () const & inline noexcept
Returns seller of this time and sale event.
Returns
seller of this time and sale event or dxfcpp::String::NUL (std::string{"<null>"}).
getSellerOpt()
const std::optional<std::string>& TimeAndSale::getSellerOpt () const & inline noexcept
Returns seller of this time and sale event.
Returns
seller of this time and sale event or std::nullopt
getSequence()
std::int32_t TimeAndSale::getSequence () const inline noexcept
Returns the sequence number of this event to distinguish events that have the same time.
This sequence number does not have to be unique and does not need to be sequential. Sequence can range from 0 to ::MAX_SEQUENCE.
Returns
The sequence number of this event
getSize()
double TimeAndSale::getSize () const inline noexcept
Returns size of this time and sale event.
Returns
size of this time and sale event.
getSource()
const IndexedEventSource& TimeAndSale::getSource () const & inline override virtual noexcept
Returns the source of this event.
Returns
The source of this event.
Implements IndexedEvent.
References IndexedEventSource::DEFAULT.
getTime()
std::int64_t TimeAndSale::getTime () const inline override virtual noexcept
Returns timestamp of the event in milliseconds.
Returns
timestamp of the event in milliseconds
Implements TimeSeriesEvent.
getTimeNanoPart()
std::int32_t TimeAndSale::getTimeNanoPart () const inline noexcept
Returns microseconds and nanoseconds time part of the original event.
Returns
microseconds and nanoseconds time part of the original event.
getTimeNanos()
std::int64_t TimeAndSale::getTimeNanos () const inline noexcept
Returns time of the original event in nanoseconds.
Time is measured in nanoseconds between the current time and midnight, January 1, 1970 UTC.
Returns
time of the original event in nanoseconds.
getTradeThroughExempt()
char TimeAndSale::getTradeThroughExempt () const inline noexcept
Returns TradeThroughExempt flag of this time and sale event.
Returns
TradeThroughExempt flag of this time and sale event.
getType()
const TimeAndSaleType& TimeAndSale::getType () const & inline noexcept
Returns type of this time and sale event.
Returns
type of this time and sale event.
Referenced by isCancel(), isCorrection(), and isNew().
isCancel()
bool TimeAndSale::isCancel () const inline noexcept
Returns whether this is a cancellation of a previous event.
It is false for newly created time and sale event.
Returns
true if this is a cancellation of a previous event
References TimeAndSaleType::CANCEL, and getType().
isCorrection()
bool TimeAndSale::isCorrection () const inline noexcept
Returns whether this is a correction of a previous event.
It is false for newly created time and sale event.
Returns
true if this is a correction of a previous event
References TimeAndSaleType::CORRECTION, and getType().
isExtendedTradingHours()
bool TimeAndSale::isExtendedTradingHours () const inline noexcept
Returns whether this event represents an extended trading hours sale.
Returns
true if this event represents an extended trading hours sale.
isNew()
bool TimeAndSale::isNew () const inline noexcept
Returns whether this is a new event (not cancellation or correction).
It is true for newly created time and sale event.
Returns
true if this is a new event (not cancellation or correction).
References getType(), and TimeAndSaleType::NEW.
isSpreadLeg()
bool TimeAndSale::isSpreadLeg () const inline noexcept
Returns whether this event represents a spread leg.
Returns
true if this event represents a spread leg.
isValidTick()
bool TimeAndSale::isValidTick () const inline noexcept
Returns whether this event represents a valid intraday tick.
Note, that a correction for a previously distributed valid tick represents a new valid tick itself, but a cancellation of a previous valid tick does not.
Returns
true if this event represents a valid intraday tick.
setAggressorSide()
void TimeAndSale::setAggressorSide (const Side & side) inline noexcept
Changes aggressor side of this time and sale event.
Parameters
side aggressor side of this time and sale event.
setAskPrice()
void TimeAndSale::setAskPrice (double askPrice) inline noexcept
Changes price of this time and sale event.the current ask price on the market when this time and sale event had occurred.
Parameters
askPrice the current ask price on the market when this time and sale event had occurred.
setBidPrice()
void TimeAndSale::setBidPrice (double bidPrice) inline noexcept
Changes the current bid price on the market when this time and sale event had occurred.
Parameters
bidPrice the current bid price on the market when this time and sale event had occurred.
setBuyer()
void TimeAndSale::setBuyer (std::string buyer) inline noexcept
Changes buyer of this time and sale event.
Parameters
buyer buyer of this time and sale event.
setEventFlags() [1/2]
void TimeAndSale::setEventFlags (const EventFlagsMask & eventFlags) inline override virtual noexcept
Changes transactional event flags.
See EventFlag "Event Flags" section.
Parameters
eventFlags transactional event flags' mask.
Implements IndexedEvent.
setEventFlags() [2/2]
void TimeAndSale::setEventFlags (std::int32_t eventFlags) inline override virtual noexcept
Changes transactional event flags.
See EventFlag "Event Flags" section.
Parameters
eventFlags transactional event flags.
Implements IndexedEvent.
setExchangeCode() [1/2]
DXFCPP_BEGIN_NAMESPACE void TimeAndSale::setExchangeCode (char exchangeCode) noexcept
Changes exchange code of this time and sale event.
Parameters
exchangeCode exchange code of this time and sale event.
setExchangeCode() [2/2]
void TimeAndSale::setExchangeCode (std::int16_t exchangeCode) inline noexcept
Changes exchange code of this time and sale event.
Parameters
exchangeCode exchange code of this time and sale event.
setExchangeSaleConditions()
void TimeAndSale::setExchangeSaleConditions (std::string exchangeSaleConditions) inline noexcept
Changes sale conditions provided for this event by data feed.
Parameters
exchangeSaleConditions sale conditions.
setExtendedTradingHours()
void TimeAndSale::setExtendedTradingHours (bool extendedTradingHours) inline noexcept
Changes whether this event represents an extended trading hours sale.
Parameters
extendedTradingHours true if this event represents an extended trading hours sale.
setIndex()
void TimeAndSale::setIndex (std::int64_t index) inline override virtual
Changes unique per-symbol index of this event.
The index is composed of time and sequence and invocation of this method changes time and sequence. Do not use this method directly. Change time and/or sequence.
Parameters
index the event index.
See also
::getIndex()
Implements IndexedEvent.
setPrice()
void TimeAndSale::setPrice (double price) inline noexcept
Changes price of this time and sale event.
Parameters
price price of this time and sale event.
setSeller()
void TimeAndSale::setSeller (std::string seller) inline noexcept
Changes seller of this time and sale event.
Parameters
seller seller of this time and sale event.
setSequence()
void TimeAndSale::setSequence (std::int32_t sequence) inline
Changes sequence number of this event.
Parameters
sequence the sequence.
See also
::getSequence()
References MAX_SEQUENCE.
setSize()
void TimeAndSale::setSize (double size) inline noexcept
Changes size of this time and sale event.
Parameters
size size of this time and sale event.
setSpreadLeg()
void TimeAndSale::setSpreadLeg (bool spreadLeg) inline noexcept
Changes whether this event represents a spread leg.
Parameters
spreadLeg true if this event represents a spread leg.
setTime()
void TimeAndSale::setTime (std::int64_t time) inline noexcept
Changes timestamp of the event in milliseconds.
Parameters
time timestamp of the event in milliseconds.
See also
::getTime()
Referenced by setTimeNanos().
setTimeNanoPart()
void TimeAndSale::setTimeNanoPart (std::int32_t timeNanoPart) inline noexcept
Changes microseconds and nanoseconds time part of the original event.
Parameters
timeNanoPart microseconds and nanoseconds time part of the original event.
setTimeNanos()
void TimeAndSale::setTimeNanos (std::int64_t timeNanos) inline noexcept
Changes time of the original event.
Time is measured in nanoseconds between the current time and midnight, January 1, 1970 UTC.
Parameters
timeNanos time of the original event in nanoseconds.
References setTime().
setTradeThroughExempt()
void TimeAndSale::setTradeThroughExempt (char tradeThroughExempt) inline
Changes TradeThroughExempt flag of this time and sale event.
Parameters
tradeThroughExempt TradeThroughExempt flag of this time and sale event.
setType()
void TimeAndSale::setType (const TimeAndSaleType & type) inline noexcept
Changes type of this time and sale event.
Parameters
type type of this time and sale event.
setValidTick()
void TimeAndSale::setValidTick (bool validTick) inline noexcept
Changes whether this event represents a valid intraday tick.
Parameters
validTick true if this event represents a valid intraday tick.
toGraal()
void * TimeAndSale::toGraal () const override virtual
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Implements EventType.
References toString().
toString()
std::string TimeAndSale::toString () const override virtual noexcept
Returns a string representation of the current object.
Returns
a string representation
Reimplemented from EventType.
Referenced by toGraal().
Member Data Documentation
MAX_SEQUENCE
constexpr std::uint32_t TimeAndSale::MAX_SEQUENCE = (1U << 22U) - 1U static constexpr
Maximum allowed sequence value.
See also
::setSequence()
Referenced by setSequence().