dxFeed Graal CXX API: System Struct Reference
System Struct Reference
A class that allows to set JVM system properties and get the values of JVM system properties.
#include <System.hpp>
Static Public Member Functions
static bool setProperty (const std::string &key, const std::string &value)
Sets the JVM system property indicated by the specified key.
template<typename Properties >
static void setProperties (Properties &&properties)
Sets the JVM system properties to the Properties argument.
static std::string getProperty (const std::string &key)
Gets the system property indicated by the specified key.
Detailed Description
A class that allows to set JVM system properties and get the values of JVM system properties.
Member Function Documentation
getProperty()
std::string System::getProperty (const std::string & key) static
Gets the system property indicated by the specified key.
Parameters
key The name of the system property (UTF-8 string).
Returns
The value of a JVM system property (UTF-8 string), or an empty string.
setProperties()
template<typename Properties > static void System::setProperties (Properties && properties) inline static
Sets the JVM system properties to the Properties argument.
Template Parameters
Properties The properties' type (std::map, std::unordered_map etc).
Parameters
properties The new system properties.
Returns
setProperty()
DXFCPP_BEGIN_NAMESPACE bool System::setProperty (const std::string & key, const std::string & value) static
Sets the JVM system property indicated by the specified key.
Parameters
key The name of the system property (UTF-8 string).
value The value of the system property (UTF-8 string).
Returns
true if the setting of the JVM system property succeeded.
Referenced by dxfc_system_set_property(), Logging::init(), Logging::init(), and Logging::init().