dxFeed Graal CXX API: dxfcpp::TheoPrice Class Reference
dxfcpp::TheoPrice Class Reference final
Theo price is a snapshot of the theoretical option price computation that is periodically performed by dxPrice model-free computation.
#include <TheoPrice.hpp>
Public Types
using Ptr = std::shared_ptr< TheoPrice >
The alias to a type of shared pointer to the TheoPrice object.
using Unique = std::unique_ptr< TheoPrice >
The alias to a type of unique pointer to the TheoPrice object.
Public Types inherited from dxfcpp::MarketEvent
using Ptr = std::shared_ptr< MarketEvent >
The alias to a type of shared pointer to the MarketEvent object.
Public Types inherited from dxfcpp::EventTypeWithSymbol< std::string >
using Ptr = std::shared_ptr< EventTypeWithSymbol< std::string > >
The alias to a type of shared pointer to the EventTypeWithSymbol's child object.
Public Types inherited from dxfcpp::EventType
using Ptr = std::shared_ptr< EventType >
The alias to a type of shared pointer to the EventType object.
Public Types inherited from dxfcpp::SharedEntity
using Ptr = std::shared_ptr< SharedEntity >
The alias to a type of shared pointer to the SharedEntity object.
Public Types inherited from dxfcpp::TimeSeriesEvent
using Ptr = std::shared_ptr< TimeSeriesEvent >
The alias to a type of shared pointer to the TimeSeriesEvent object.
Public Types inherited from dxfcpp::IndexedEvent
using Ptr = std::shared_ptr< IndexedEvent >
The alias to a type of shared pointer to the IndexedEvent object.
Public Types inherited from dxfcpp::LastingEvent
using Ptr = std::shared_ptr< LastingEvent >
The alias to a type of shared pointer to the LastingEvent object.
Public Member Functions
void * toGraal () const noexcept override
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
TheoPrice () noexcept=default
Creates new theoprice event with default values.
TheoPrice (std::string eventSymbol) noexcept
Creates new theoprice event with the specified event symbol.
const IndexedEventSource & getSource () const &noexcept override
Returns the source of this event.
std::int32_t getEventFlags () const noexcept override
Returns transactional event flags.
EventFlagsMask getEventFlagsMask () const noexcept override
Returns transactional event flags.
void setEventFlags (std::int32_t eventFlags) noexcept override
Changes transactional event flags.
void setEventFlags (const EventFlagsMask &eventFlags) noexcept override
Changes transactional event flags.
std::int64_t getIndex () const noexcept override
Returns unique per-symbol index of this event.
void setIndex (std::int64_t index) noexcept override
Changes unique per-symbol index of this event.
std::int64_t getTime () const noexcept override
Returns timestamp of the event in milliseconds.
void setTime (std::int64_t time) noexcept
Changes timestamp of the event in milliseconds.
std::int32_t getSequence () const noexcept
Returns the sequence number of this event to distinguish events that have the same time.
void setSequence (int sequence) noexcept
Changes sequence number of this event.
double getPrice () const noexcept
Returns theoretical option price.
void setPrice (double price) noexcept
Changes theoretical option price.
double getUnderlyingPrice () const noexcept
Returns underlying price at the time of theo price computation.
void setUnderlyingPrice (double underlyingPrice) noexcept
Changes underlying price at the time of theo price computation.
double getDelta () const noexcept
Returns delta of the theoretical price.
void setDelta (double delta) noexcept
Changes delta of the theoretical price.
double getGamma () const noexcept
Returns gamma of the theoretical price.
void setGamma (double gamma) noexcept
Changes gamma of the theoretical price.
double getDividend () const noexcept
Returns implied simple dividend return of the corresponding option series.
void setDividend (double dividend) noexcept
Changes implied simple dividend return of the corresponding option series.
double getInterest () const noexcept
Returns implied simple interest return of the corresponding option series.
void setInterest (double interest) noexcept
Changes implied simple interest return of the corresponding option series.
std::string toString () const noexcept override
Returns a string representation of the current object.
Public Member Functions inherited from dxfcpp::MarketEvent
const std::string & getEventSymbol () const &noexcept override
Returns symbol of this event.
const std::optional< std::string > & getEventSymbolOpt () const &noexcept override
Returns symbol of this event.
void setEventSymbol (const std::string &eventSymbol) noexcept override
Changes symbol of this event.
std::int64_t getEventTime () const noexcept override
Returns time when event was created or zero when time is not available.
void setEventTime (std::int64_t eventTime) noexcept override
Changes event creation time.
Public Member Functions inherited from dxfcpp::SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
Public Member Functions inherited from dxfcpp::Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Public Member Functions inherited from dxfcpp::TimeSeriesEvent
const IndexedEventSource & getSource () const &noexcept override
Returns the source identifier for this event, which is always DEFAULT for time-series events.
std::int64_t getIndex () const noexcept override
Returns unique per-symbol index of this event.
virtual std::int64_t getEventId () const noexcept
Returns unique per-symbol index of this event.
Static Public Member Functions
static void freeGraal (void *graalNative) noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Attributes
static constexpr std::uint32_t MAX_SEQUENCE = (1U << 22U) - 1U
Maximum allowed sequence value.
static const EventTypeEnum & TYPE = EventTypeEnum::THEO_PRICE
Type identifier and additional information about the current event class.
Static Public Attributes inherited from dxfcpp::IndexedEvent
static const EventFlag TX_PENDING = EventFlag::TX_PENDING
0x01 - A bitmask to get transaction pending indicator from the value of eventFlags property.
static const EventFlag REMOVE_EVENT = EventFlag::REMOVE_EVENT
0x02 - A bitmask to get removal indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_BEGIN = EventFlag::SNAPSHOT_BEGIN
0x04 - A bitmask to get snapshot begin indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_END = EventFlag::SNAPSHOT_END
0x08 - A bitmask to get snapshot end indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_SNIP = EventFlag::SNAPSHOT_SNIP
0x10 - A bitmask to get snapshot snip indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_MODE = EventFlag::SNAPSHOT_MODE
0x40 - A bitmask to set snapshot mode indicator into the value of eventFlags property.
Additional Inherited Members
Protected Member Functions inherited from dxfcpp::MarketEvent
MarketEvent (std::string eventSymbol) noexcept
Protected constructor for concrete implementation classes that initializes eventSymbol property.
Detailed Description
Theo price is a snapshot of the theoretical option price computation that is periodically performed by dxPrice model-free computation.
It represents the most recent information that is available about the corresponding values at any given moment of time. The values include first and second order derivative of the price curve by price, so that the real-time theoretical option price can be estimated on real-time changes of the underlying price in the vicinity.
Event flags, transactions and snapshots
Some TheoPrice sources provide a consistent view of the set of known TheoPrice. The corresponding information is carried in eventFlags property. The logic behind this property is detailed in IndexedEvent class documentation. Multiple event sources for the same symbol are not supported for TheoPrice, thus source property is always DEFAULT.
TimeSeriesEventModel class handles all the snapshot and transaction logic and conveniently represents a list current of time-series events order by their time.
Publishing TheoPrice
Publishing of TheoPrice events follows the general rules explained in TimeSeriesEvent class documentation.
Implementation details
This event is implemented on top of QDS records TheoPrice.
Constructor & Destructor Documentation
TheoPrice()
dxfcpp::TheoPrice::TheoPrice (std::string eventSymbol) inline explicit noexcept
Creates new theoprice event with the specified event symbol.
Parameters
eventSymbol The event symbol.
References dxfcpp::MarketEvent::MarketEvent().
Member Function Documentation
freeGraal()
void dxfcpp::TheoPrice::freeGraal (void * graalNative) static noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
getDelta()
double dxfcpp::TheoPrice::getDelta () const inline noexcept
Returns delta of the theoretical price.
Delta is the first derivative of the theoretical price by the underlying price.
Returns
delta of the theoretical price.
getDividend()
double dxfcpp::TheoPrice::getDividend () const inline noexcept
Returns implied simple dividend return of the corresponding option series.
Returns
implied simple dividend return of the corresponding option series.
getEventFlags()
std::int32_t dxfcpp::TheoPrice::getEventFlags () const inline override virtual noexcept
Returns transactional event flags.
See EventFlag "Event Flags" section.
Returns
The transactional event flags.
Implements dxfcpp::IndexedEvent.
getEventFlagsMask()
EventFlagsMask dxfcpp::TheoPrice::getEventFlagsMask () const inline override virtual noexcept
Returns transactional event flags.
See EventFlag "Event Flags" section.
Returns
The transactional event flags' mask.
Implements dxfcpp::IndexedEvent.
getGamma()
double dxfcpp::TheoPrice::getGamma () const inline noexcept
Returns gamma of the theoretical price.
Gamma is the second derivative of the theoretical price by the underlying price.
Returns
gamma of the theoretical price.
getIndex()
std::int64_t dxfcpp::TheoPrice::getIndex () const inline override virtual noexcept
Returns unique per-symbol index of this event.
The index is composed of time and sequence. Changing either time or sequence changes event index.
Returns
unique index of this event.
Implements dxfcpp::IndexedEvent.
getInterest()
double dxfcpp::TheoPrice::getInterest () const inline noexcept
Returns implied simple interest return of the corresponding option series.
Returns
implied simple interest return of the corresponding option series.
getPrice()
double dxfcpp::TheoPrice::getPrice () const inline noexcept
Returns theoretical option price.
Returns
theoretical option price.
getSequence()
std::int32_t dxfcpp::TheoPrice::getSequence () const inline noexcept
Returns the sequence number of this event to distinguish events that have the same time.
This sequence number does not have to be unique and does not need to be sequential. Sequence can range from 0 to ::MAX_SEQUENCE.
Returns
The sequence number of this event
References MAX_SEQUENCE.
Referenced by setTime().
getSource()
const IndexedEventSource& dxfcpp::TheoPrice::getSource () const & inline override virtual noexcept
Returns the source of this event.
Returns
The source of this event.
Implements dxfcpp::IndexedEvent.
References dxfcpp::IndexedEventSource::DEFAULT.
getTime()
std::int64_t dxfcpp::TheoPrice::getTime () const inline override virtual noexcept
Returns timestamp of the event in milliseconds.
Returns
timestamp of the event in milliseconds
Implements dxfcpp::TimeSeriesEvent.
getUnderlyingPrice()
double dxfcpp::TheoPrice::getUnderlyingPrice () const inline noexcept
Returns underlying price at the time of theo price computation.
Returns
underlying price at the time of theo price computation.
setDelta()
void dxfcpp::TheoPrice::setDelta (double delta) inline noexcept
Changes delta of the theoretical price.
Parameters
delta delta of the theoretical price.
setDividend()
void dxfcpp::TheoPrice::setDividend (double dividend) inline noexcept
Changes implied simple dividend return of the corresponding option series.
Parameters
dividend implied simple dividend return of the corresponding option series.
setEventFlags() [1/2]
void dxfcpp::TheoPrice::setEventFlags (const EventFlagsMask & eventFlags) inline override virtual noexcept
Changes transactional event flags.
See EventFlag "Event Flags" section.
Parameters
eventFlags transactional event flags' mask.
Implements dxfcpp::IndexedEvent.
References dxfcpp::EventFlagsMask::getMask().
setEventFlags() [2/2]
void dxfcpp::TheoPrice::setEventFlags (std::int32_t eventFlags) inline override virtual noexcept
Changes transactional event flags.
See EventFlag "Event Flags" section.
Parameters
eventFlags transactional event flags.
Implements dxfcpp::IndexedEvent.
setGamma()
void dxfcpp::TheoPrice::setGamma (double gamma) inline noexcept
Changes gamma of the theoretical price.
Parameters
gamma gamma of the theoretical price.
setIndex()
void dxfcpp::TheoPrice::setIndex (std::int64_t index) inline override virtual noexcept
Changes unique per-symbol index of this event.
The index is composed of time and sequence and invocation of this method changes time and sequence. Do not use this method directly. Change time and/or sequence.
Parameters
index the event index.
See also
::getIndex()
Implements dxfcpp::IndexedEvent.
setInterest()
void dxfcpp::TheoPrice::setInterest (double interest) inline noexcept
Changes implied simple interest return of the corresponding option series.
Parameters
interest implied simple interest return of the corresponding option series.
setPrice()
void dxfcpp::TheoPrice::setPrice (double price) inline noexcept
Changes theoretical option price.
Parameters
price theoretical option price.
setSequence()
void dxfcpp::TheoPrice::setSequence (int sequence) inline noexcept
Changes sequence number of this event.
Parameters
sequence the sequence.
See also
::getSequence()
References MAX_SEQUENCE.
setTime()
void dxfcpp::TheoPrice::setTime (std::int64_t time) inline noexcept
Changes timestamp of the event in milliseconds.
Parameters
time timestamp of the event in milliseconds.
See also
::getTime()
References getSequence().
setUnderlyingPrice()
void dxfcpp::TheoPrice::setUnderlyingPrice (double underlyingPrice) inline noexcept
Changes underlying price at the time of theo price computation.
Parameters
underlyingPrice underlying price at the time of theo price computation.
toGraal()
void * dxfcpp::TheoPrice::toGraal () const override virtual noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Implements dxfcpp::EventType.
References toString().
toString()
std::string dxfcpp::TheoPrice::toString () const override virtual noexcept
Returns a string representation of the current object.
Returns
a string representation
Reimplemented from dxfcpp::EventType.
Referenced by toGraal().
Member Data Documentation
MAX_SEQUENCE
constexpr std::uint32_t dxfcpp::TheoPrice::MAX_SEQUENCE = (1U << 22U) - 1U static constexpr
Maximum allowed sequence value.
See also
::setSequence()
Referenced by getSequence(), and setSequence().