dxFeed Graal CXX API: AnalyticOrder Class Reference
AnalyticOrder Class Reference final
Represents an extension of Order introducing analytic information, e.g.
#include <AnalyticOrder.hpp>
Public Types
using Ptr = std::shared_ptr<AnalyticOrder>
The alias to a type of shared pointer to the AnalyticOrder object.
using Unique = std::unique_ptr<AnalyticOrder>
The alias to a type of unique pointer to the AnalyticOrder object.
Public Types inherited from Order
using Ptr = std::shared_ptr<Order>
The alias to a type of shared pointer to the Order object.
using Unique = std::unique_ptr<Order>
The alias to a type of unique pointer to the Order object.
Public Types inherited from MarketEvent
using Ptr = std::shared_ptr<MarketEvent>
The alias to a type of shared pointer to the MarketEvent object.
Public Types inherited from EventTypeWithSymbol< std::string >
using Ptr
The alias to a type of shared pointer to the EventTypeWithSymbol's child object.
Public Types inherited from EventType
using Ptr = std::shared_ptr<EventType>
The alias to a type of shared pointer to the EventType object.
Public Types inherited from SharedEntity
using Ptr = std::shared_ptr<SharedEntity>
The alias to a type of shared pointer to the SharedEntity object.
Public Types inherited from IndexedEvent
using Ptr = std::shared_ptr<IndexedEvent>
The alias to a type of shared pointer to the IndexedEvent object.
Public Member Functions
void * toGraal () const override
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
AnalyticOrder () noexcept=default
Creates new analytic order event with default values.
AnalyticOrder (std::string eventSymbol) noexcept
Creates new analytic order event with the specified event symbol.
AnalyticOrder & withEventSymbol (const std::string &eventSymbol) noexcept override
Changes event's symbol and returns the current analytic order.
AnalyticOrder & withEventTime (std::int64_t eventTime) noexcept
Changes event's creation time and returns the current analytic order.
AnalyticOrder & withSource (const OrderSource &source) noexcept
Changes event's source and returns the current analytic order.
AnalyticOrder & withEventFlags (std::int32_t eventFlags) noexcept
Changes transactional event flags and returns the current analytic order.
AnalyticOrder & withEventFlags (const EventFlagsMask &eventFlags) noexcept
Changes transactional event flags and returns the current analytic order.
AnalyticOrder & withIndex (std::int64_t index) noexcept
Changes unique per-symbol index of this analytic order and returns it.
AnalyticOrder & withTime (std::int64_t time) noexcept
Changes time of this analytic order and returns it.
AnalyticOrder & withTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds time part of this analytic order.
AnalyticOrder & withSequence (std::int32_t sequence) noexcept
Changes sequence number of this analytic order.
AnalyticOrder & withTimeNanos (std::int64_t timeNanos) noexcept
Changes time of this analytic order and returns it.
AnalyticOrder & withAction (const OrderAction &action) noexcept
Changes action of this analytic order and returns it.
AnalyticOrder & withActionTime (std::int64_t actionTime) noexcept
Changes time of the last action and returns current analytic order.
AnalyticOrder & withOrderId (std::int64_t orderId) noexcept
Changes order ID.
AnalyticOrder & withAuxOrderId (std::int64_t auxOrderId) noexcept
Changes auxiliary order ID.
AnalyticOrder & withPrice (double price) noexcept
Changes price of this analytic order.
AnalyticOrder & withSize (double size) noexcept
Changes size of this analytic order.
AnalyticOrder & withExecutedSize (double executedSize) noexcept
Changes executed size of this analytic order.
AnalyticOrder & withCount (std::int64_t count) noexcept
Changes number of individual orders in this aggregate order.
AnalyticOrder & withTradeId (std::int64_t tradeId) noexcept
Changes trade ID.
AnalyticOrder & withTradePrice (double tradePrice) noexcept
Changes trade price.
AnalyticOrder & withTradeSize (double tradeSize) noexcept
Changes trade size.
AnalyticOrder & withExchangeCode (char exchangeCode) noexcept
Changes exchange code of this analytic order.
AnalyticOrder & withExchangeCode (std::int16_t exchangeCode) noexcept
Changes exchange code of this analytic order.
AnalyticOrder & withOrderSide (const Side &side) noexcept
Changes side of this analytic order.
AnalyticOrder & withScope (const Scope &scope) noexcept
Changes scope of this analytic order.
AnalyticOrder & withMarketMaker (std::string marketMaker) noexcept
Changes market maker or other aggregate identifier of this analytic order.
double getIcebergPeakSize () const noexcept
Returns iceberg peak size of this analytic order.
void setIcebergPeakSize (double icebergPeakSize) noexcept
Changes iceberg peak size of this analytic order.
AnalyticOrder & withIcebergPeakSize (double icebergPeakSize) noexcept
Changes iceberg peak size and returns the current analytic order.
double getIcebergHiddenSize () const noexcept
Returns iceberg hidden size of this analytic order.
void setIcebergHiddenSize (double icebergHiddenSize) noexcept
Changes iceberg hidden size of this analytic order.
AnalyticOrder & withIcebergHiddenSize (double icebergHiddenSize) noexcept
Changes iceberg hidden size and returns the current analytic order.
double getIcebergExecutedSize () const noexcept
Returns iceberg executed size of this analytic order.
void setIcebergExecutedSize (double icebergExecutedSize) noexcept
Changes iceberg executed size of this analytic order.
AnalyticOrder & withIcebergExecutedSize (double icebergExecutedSize) noexcept
Changes iceberg executed size and returns the current analytic order.
const IcebergType & getIcebergType () const &noexcept
Returns iceberg type of this analytic order.
void setIcebergType (const IcebergType &icebergType) noexcept
Changes iceberg type of this analytic order.
AnalyticOrder & withIcebergType (const IcebergType &icebergType) noexcept
Changes iceberg type and returns the current analytic order.
std::string toString () const noexcept override
Returns a string representation of the current object.
Public Member Functions inherited from Order
void * toGraal () const override
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Order () noexcept=default
Creates new order event with default values.
Order (std::string eventSymbol) noexcept
Creates new order event with the specified event symbol.
Order & withEventTime (std::int64_t eventTime) noexcept
Changes event's creation time and returns the current order.
Order & withSource (const OrderSource &source) noexcept
Changes event's source and returns the current order.
Order & withEventFlags (std::int32_t eventFlags) noexcept
Changes transactional event flags and returns the current order.
Order & withEventFlags (const EventFlagsMask &eventFlags) noexcept
Changes transactional event flags and returns the current order.
Order & withIndex (std::int64_t index) noexcept
Changes unique per-symbol index of this order and returns it.
Order & withTime (std::int64_t time) noexcept
Changes time of this order and returns it.
Order & withTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds time part of this order.
Order & withSequence (std::int32_t sequence) noexcept
Changes sequence number of this order.
Order & withTimeNanos (std::int64_t timeNanos) noexcept
Changes time of this order and returns it.
Order & withAction (const OrderAction &action) noexcept
Changes action of this order and returns it.
Order & withActionTime (std::int64_t actionTime) noexcept
Changes time of the last action and returns current order.
Order & withOrderId (std::int64_t orderId) noexcept
Changes order ID.
Order & withAuxOrderId (std::int64_t auxOrderId) noexcept
Changes auxiliary order ID.
Order & withPrice (double price) noexcept
Changes price of this order.
Order & withSize (double size) noexcept
Changes size of this order.
Order & withExecutedSize (double executedSize) noexcept
Changes executed size of this order.
Order & withCount (std::int64_t count) noexcept
Changes number of individual orders in this aggregate order.
Order & withTradeId (std::int64_t tradeId) noexcept
Changes trade ID.
Order & withTradePrice (double tradePrice) noexcept
Changes trade price.
Order & withTradeSize (double tradeSize) noexcept
Changes trade size.
Order & withExchangeCode (char exchangeCode) noexcept
Changes exchange code of this order.
Order & withExchangeCode (std::int16_t exchangeCode) noexcept
Changes exchange code of this order.
Order & withOrderSide (const Side &side) noexcept
Changes side of this order.
Order & withScope (const Scope &scope) noexcept
Changes scope of this order.
const std::string & getMarketMaker () const &noexcept
Returns market maker or other aggregate identifier of this order.
const std::optional< std::string > & getMarketMakerOpt () const &noexcept
Returns market maker or other aggregate identifier of this order.
void setMarketMaker (std::string marketMaker) noexcept
Changes market maker or other aggregate identifier of this order.
Order & withMarketMaker (std::string marketMaker) noexcept
Changes market maker or other aggregate identifier of this order.
std::string toString () const noexcept override
Returns a string representation of the current object.
Public Member Functions inherited from OrderBase
OrderBase () noexcept=default
Creates new order event with default values.
OrderBase (std::string eventSymbol) noexcept
Creates new order event with the specified event symbol.
const OrderSource & getSource () const &noexcept override
Returns source of this event.
void setSource (const OrderSource &source) noexcept
Changes source of this event.
std::int32_t getEventFlags () const noexcept override
Returns transactional event flags.
EventFlagsMask getEventFlagsMask () const noexcept override
Returns transactional event flags.
void setEventFlags (std::int32_t eventFlags) noexcept override
Changes transactional event flags.
void setEventFlags (const EventFlagsMask &eventFlags) noexcept override
Changes transactional event flags.
void setIndex (std::int64_t index) override
Changes unique per-symbol index of this order.
std::int64_t getIndex () const noexcept override
Returns unique per-symbol index of this order.
std::int64_t getTimeSequence () const noexcept
Returns time and sequence of this order packaged into single long value.
void setTimeSequence (std::int64_t timeSequence) noexcept
Changes time and sequence of this order.
std::int64_t getTime () const noexcept
Returns time of this order.
void setTime (std::int64_t time) noexcept
Changes time of this order.
void setTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds time part of this order.
std::int32_t getTimeNanoPart () const noexcept
Returns microseconds and nanoseconds time part of this order.
std::int32_t getSequence () const noexcept
Returns sequence number of this order to distinguish orders that have the same time.
void setSequence (std::int32_t sequence)
Changes sequence number of this order.
std::int64_t getTimeNanos () const noexcept
Returns time of this order in nanoseconds.
void setTimeNanos (std::int64_t timeNanos) noexcept
Changes time of this order.
const OrderAction & getAction () const &noexcept
Returns order action if available, otherwise - OrderAction::UNDEFINED.
void setAction (const OrderAction &action) noexcept
Changes action of this order.
std::int64_t getActionTime () const noexcept
Returns time of the last action.
void setActionTime (std::int64_t actionTime) noexcept
Changes time of the last action.
std::int64_t getOrderId () const noexcept
Returns order ID if available.
void setOrderId (std::int64_t orderId) noexcept
Changes order ID.
std::int64_t getAuxOrderId () const noexcept
Returns auxiliary order ID if available:
void setAuxOrderId (std::int64_t auxOrderId) noexcept
Changes auxiliary order ID.
double getPrice () const noexcept
Returns price of this order.
void setPrice (double price) noexcept
Changes price of this order.
double getSize () const noexcept
Returns size of this order.
void setSize (double size) noexcept
Changes size of this order.
bool hasSize () const noexcept
Returns true if this order has some size (sizeAsDouble is neither 0 nor NaN).
double getExecutedSize () const noexcept
Returns executed size of this order.
void setExecutedSize (double executedSize) noexcept
Changes executed size of this order.
std::int64_t getCount () const noexcept
Returns number of individual orders in this aggregate order.
void setCount (std::int64_t count) noexcept
Changes number of individual orders in this aggregate order.
std::int64_t getTradeId () const noexcept
Returns trade (order execution) ID for events containing trade-related action.
void setTradeId (std::int64_t tradeId) noexcept
Changes trade ID.
double getTradePrice () const noexcept
Returns trade price for events containing trade-related action.
void setTradePrice (double tradePrice) noexcept
Changes trade price.
double getTradeSize () const noexcept
Returns trade size for events containing trade-related action.
void setTradeSize (double tradeSize) noexcept
Changes trade size.
std::int16_t getExchangeCode () const noexcept
Returns exchange code of this order.
std::string getExchangeCodeString () const noexcept
Returns exchange code of this order as UTF8 string.
void setExchangeCode (char exchangeCode)
Changes exchange code of this order.
void setExchangeCode (std::int16_t exchangeCode) noexcept
Changes exchange code of this order.
const Side & getOrderSide () const &noexcept
Returns side of this order.
void setOrderSide (const Side &side) noexcept
Changes side of this order.
const Scope & getScope () const &noexcept
Returns scope of this order.
void setScope (const Scope &scope) noexcept
Changes scope of this order.
std::string baseFieldsToString () const noexcept
Returns string representation of this order event's fields.
Public Member Functions inherited from MarketEvent
const std::string & getEventSymbol () const &noexcept override
Returns symbol of this event.
const std::optional< std::string > & getEventSymbolOpt () const &noexcept override
Returns symbol of this event.
void setEventSymbol (const std::string &eventSymbol) noexcept override
Changes symbol of this event.
std::int64_t getEventTime () const noexcept override
Returns time when event was created or zero when time is not available.
void setEventTime (std::int64_t eventTime) noexcept override
Changes event creation time.
Public Member Functions inherited from SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
Public Member Functions inherited from Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Static Public Member Functions
static Ptr fromGraal (void *graalNative)
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
static void freeGraal (void *graalNative)
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Member Functions inherited from Order
static Ptr fromGraal (void *graalNative)
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
static void freeGraal (void *graalNative)
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Attributes
static const EventTypeEnum & TYPE = EventTypeEnum::ANALYTIC_ORDER
Type identifier and additional information about the current event class.
Static Public Attributes inherited from Order
static const EventTypeEnum & TYPE = EventTypeEnum::ORDER
Type identifier and additional information about the current event class.
Static Public Attributes inherited from OrderBase
static constexpr std::uint32_t MAX_SEQUENCE = (1U << 22U) - 1U
Maximum allowed sequence value.
Static Public Attributes inherited from IndexedEvent
static const EventFlag TX_PENDING = EventFlag::TX_PENDING
0x01 - A bitmask to get transaction pending indicator from the value of eventFlags property.
static const EventFlag REMOVE_EVENT = EventFlag::REMOVE_EVENT
0x02 - A bitmask to get removal indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_BEGIN = EventFlag::SNAPSHOT_BEGIN
0x04 - A bitmask to get snapshot begin indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_END = EventFlag::SNAPSHOT_END
0x08 - A bitmask to get snapshot end indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_SNIP = EventFlag::SNAPSHOT_SNIP
0x10 - A bitmask to get snapshot snip indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_MODE = EventFlag::SNAPSHOT_MODE
0x40 - A bitmask to set snapshot mode indicator into the value of eventFlags property.
Additional Inherited Members
Protected Member Functions inherited from MarketEvent
MarketEvent (std::string eventSymbol) noexcept
Protected constructor for concrete implementation classes that initializes eventSymbol property.
Detailed Description
Represents an extension of Order introducing analytic information, e.g.
adding to this order iceberg related information (icebergPeakSize, icebergHiddenSize, icebergExecutedSize). The collection of analytic order events of a symbol represents the most recent analytic information that is available about orders on the market at any given moment of time.
Analytic order is similar to a regular Order. In addition this event has few additional properties:
icebergPeakSize - the size of the peak, i.e. the visible part of the iceberg, that is being continually refilled until the order is fully traded or cancelled;
icebergHiddenSize - the prediction of current hidden size of the iceberg, as inferred by the model;
icebergExecutedSize - the executed size of the iceberg order. For IcebergType::SYNTHETIC type represents total executed size of all orders composing current iceberg;
AnalyticOrder::getIcebergType() - type of the iceberg, either native (exchange-managed) or synthetic (managed outside of the exchange).
Implementation details
This event is implemented on top of QDS records AnalyticOrder#<source-id>, where <source-id> is up to 4 ASCII characters with a mnemonic for the source like "GLBX".
Constructor & Destructor Documentation
AnalyticOrder()
AnalyticOrder::AnalyticOrder (std::string eventSymbol) inline explicit noexcept
Creates new analytic order event with the specified event symbol.
Parameters
eventSymbol The event symbol.
Member Function Documentation
freeGraal()
void AnalyticOrder::freeGraal (void * graalNative) static
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
fromGraal()
std::shared_ptr< AnalyticOrder > AnalyticOrder::fromGraal (void * graalNative) static
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Returns
The object of current type.
Exceptions
std::invalid_argument
getIcebergExecutedSize()
double AnalyticOrder::getIcebergExecutedSize () const inline noexcept
Returns iceberg executed size of this analytic order.
Returns
iceberg executed size of this analytic order.
getIcebergHiddenSize()
double AnalyticOrder::getIcebergHiddenSize () const inline noexcept
Returns iceberg hidden size of this analytic order.
Returns
iceberg hidden size of this analytic order.
getIcebergPeakSize()
double AnalyticOrder::getIcebergPeakSize () const inline noexcept
Returns iceberg peak size of this analytic order.
Returns
iceberg peak size of this analytic order.
getIcebergType()
const IcebergType & AnalyticOrder::getIcebergType () const & inline noexcept
Returns iceberg type of this analytic order.
Returns
iceberg type of this analytic order.
setIcebergExecutedSize()
void AnalyticOrder::setIcebergExecutedSize (double icebergExecutedSize) inline noexcept
Changes iceberg executed size of this analytic order.
Parameters
icebergExecutedSize iceberg executed size of this analytic order.
Referenced by withIcebergExecutedSize().
setIcebergHiddenSize()
void AnalyticOrder::setIcebergHiddenSize (double icebergHiddenSize) inline noexcept
Changes iceberg hidden size of this analytic order.
Parameters
icebergHiddenSize iceberg hidden size of this analytic order.
Referenced by withIcebergHiddenSize().
setIcebergPeakSize()
void AnalyticOrder::setIcebergPeakSize (double icebergPeakSize) inline noexcept
Changes iceberg peak size of this analytic order.
Parameters
icebergPeakSize iceberg peak size of this analytic order.
Referenced by withIcebergPeakSize().
setIcebergType()
void AnalyticOrder::setIcebergType (const IcebergType & icebergType) inline noexcept
Changes iceberg type of this analytic order.
Parameters
icebergType iceberg type of this analytic order.
Referenced by withIcebergType().
toGraal()
void * AnalyticOrder::toGraal () const override virtual
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Implements EventType.
toString()
std::string AnalyticOrder::toString () const override virtual noexcept
Returns a string representation of the current object.
Returns
a string representation
Reimplemented from SharedEntity.
withAction()
AnalyticOrder & AnalyticOrder::withAction (const OrderAction & action) inline noexcept
Changes action of this analytic order and returns it.
Parameters
action The side of this analytic order.
Returns
The current analytic order.
References Order::withAction().
withActionTime()
AnalyticOrder & AnalyticOrder::withActionTime (std::int64_t actionTime) inline noexcept
Changes time of the last action and returns current analytic order.
Parameters
actionTime The last order action time.
Returns
The current analytic order.
References Order::withActionTime().
withAuxOrderId()
AnalyticOrder & AnalyticOrder::withAuxOrderId (std::int64_t auxOrderId) inline noexcept
Changes auxiliary order ID.
Returns the current analytic order.
Parameters
auxOrderId The auxiliary order ID.
Returns
The current analytic order.
References Order::withAuxOrderId().
withCount()
AnalyticOrder & AnalyticOrder::withCount (std::int64_t count) inline noexcept
Changes number of individual orders in this aggregate order.
Returns the current analytic order.
Parameters
count The number of individual orders in this aggregate order.
Returns
The current analytic order.
References Order::withCount().
withEventFlags() [1/2]
AnalyticOrder & AnalyticOrder::withEventFlags (const EventFlagsMask & eventFlags) inline noexcept
Changes transactional event flags and returns the current analytic order.
See EventFlag "Event Flags" section.
Parameters
eventFlags transactional event flags' mask.
Returns
The current analytic order.
withEventFlags() [2/2]
AnalyticOrder & AnalyticOrder::withEventFlags (std::int32_t eventFlags) inline noexcept
Changes transactional event flags and returns the current analytic order.
See EventFlag "Event Flags" section.
Parameters
eventFlags transactional event flags.
Returns
The current analytic order.
withEventSymbol()
AnalyticOrder & AnalyticOrder::withEventSymbol (const std::string & eventSymbol) inline override virtual noexcept
Changes event's symbol and returns the current analytic order.
Parameters
eventSymbol The symbol of this event.
Returns
The current analytic order.
Reimplemented from Order.
References Order::withEventSymbol().
withEventTime()
AnalyticOrder & AnalyticOrder::withEventTime (std::int64_t eventTime) inline noexcept
Changes event's creation time and returns the current analytic order.
Parameters
eventTime the difference, measured in milliseconds, between the event creation time and midnight, January 1, 1970 UTC.
Returns
The current analytic order.
References Order::withEventTime().
withExchangeCode() [1/2]
AnalyticOrder & AnalyticOrder::withExchangeCode (char exchangeCode) inline noexcept
Changes exchange code of this analytic order.
Returns the current analytic order.
Parameters
exchangeCode The exchange code of this analytic order.
Returns
The current analytic order.
withExchangeCode() [2/2]
AnalyticOrder & AnalyticOrder::withExchangeCode (std::int16_t exchangeCode) inline noexcept
Changes exchange code of this analytic order.
Returns the current analytic order.
Parameters
exchangeCode The exchange code of this analytic order.
Returns
The current analytic order.
withExecutedSize()
AnalyticOrder & AnalyticOrder::withExecutedSize (double executedSize) inline noexcept
Changes executed size of this analytic order.
Returns the current analytic order.
Parameters
executedSize The executed size of this analytic order.
Returns
The current analytic order.
References Order::withExecutedSize().
withIcebergExecutedSize()
AnalyticOrder & AnalyticOrder::withIcebergExecutedSize (double icebergExecutedSize) inline noexcept
Changes iceberg executed size and returns the current analytic order.
Parameters
icebergExecutedSize iceberg executed size of this analytic order.
Returns
The current analytic order.
References setIcebergExecutedSize().
withIcebergHiddenSize()
AnalyticOrder & AnalyticOrder::withIcebergHiddenSize (double icebergHiddenSize) inline noexcept
Changes iceberg hidden size and returns the current analytic order.
Parameters
icebergHiddenSize iceberg hidden size of this analytic order.
Returns
The current analytic order.
References setIcebergHiddenSize().
withIcebergPeakSize()
AnalyticOrder & AnalyticOrder::withIcebergPeakSize (double icebergPeakSize) inline noexcept
Changes iceberg peak size and returns the current analytic order.
Parameters
icebergPeakSize iceberg peak size of this analytic order.
Returns
The current analytic order.
References setIcebergPeakSize().
withIcebergType()
AnalyticOrder & AnalyticOrder::withIcebergType (const IcebergType & icebergType) inline noexcept
Changes iceberg type and returns the current analytic order.
Parameters
icebergType iceberg type of this analytic order.
Returns
The current analytic order.
References setIcebergType().
withIndex()
AnalyticOrder & AnalyticOrder::withIndex (std::int64_t index) inline noexcept
Changes unique per-symbol index of this analytic order and returns it.
Note, that this method also changes source, whose id occupies highest bits of index. Use OrderBase::setSource() after invocation of this method to set the desired value of source.
Parameters
index unique per-symbol index of this analytic order.
Returns
The current analytic order.
References Order::withIndex().
withMarketMaker()
AnalyticOrder & AnalyticOrder::withMarketMaker (std::string marketMaker) inline noexcept
Changes market maker or other aggregate identifier of this analytic order.
Returns the current analytic order.
Parameters
marketMaker The market maker or other aggregate identifier of this analytic order.
Returns
The current analytic order.
withOrderId()
AnalyticOrder & AnalyticOrder::withOrderId (std::int64_t orderId) inline noexcept
Changes order ID.
Returns the current analytic order.
Parameters
orderId The order ID.
Returns
The current analytic order.
References Order::withOrderId().
withOrderSide()
AnalyticOrder & AnalyticOrder::withOrderSide (const Side & side) inline noexcept
Changes side of this analytic order.
Returns the current analytic order.
Parameters
side The side of this analytic order.
Returns
The current analytic order.
References Order::withOrderSide().
withPrice()
AnalyticOrder & AnalyticOrder::withPrice (double price) inline noexcept
Changes price of this analytic order.
Returns the current analytic order.
Parameters
price The price of this analytic order.
Returns
The current analytic order.
References Order::withPrice().
withScope()
AnalyticOrder & AnalyticOrder::withScope (const Scope & scope) inline noexcept
Changes scope of this analytic order.
Returns the current analytic order.
Parameters
scope The scope of this analytic order.
Returns
The current analytic order.
References Order::withScope().
withSequence()
AnalyticOrder & AnalyticOrder::withSequence (std::int32_t sequence) inline noexcept
Changes sequence number of this analytic order.
Returns the current analytic order.
Parameters
sequence the sequence.
Returns
The current analytic order.
See also
OrderBase::getSequence()
References Order::withSequence().
withSize()
AnalyticOrder & AnalyticOrder::withSize (double size) inline noexcept
Changes size of this analytic order.
Returns the current analytic order.
Parameters
size The size of this analytic order.
Returns
The current analytic order.
References Order::withSize().
withSource()
AnalyticOrder & AnalyticOrder::withSource (const OrderSource & source) inline noexcept
Changes event's source and returns the current analytic order.
This method changes highest bits of the index of this event.
Parameters
source source of this event.
Returns
The current analytic order.
References Order::withSource().
withTime()
AnalyticOrder & AnalyticOrder::withTime (std::int64_t time) inline noexcept
Changes time of this analytic order and returns it.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
Parameters
time time of this analytic order.
Returns
The current analytic order.
References Order::withTime().
withTimeNanoPart()
AnalyticOrder & AnalyticOrder::withTimeNanoPart (std::int32_t timeNanoPart) inline noexcept
Changes microseconds and nanoseconds time part of this analytic order.
Returns the current analytic order.
Parameters
timeNanoPart microseconds and nanoseconds time part of this analytic order.
Returns
The current analytic order.
References Order::withTimeNanoPart().
withTimeNanos()
AnalyticOrder & AnalyticOrder::withTimeNanos (std::int64_t timeNanos) inline noexcept
Changes time of this analytic order and returns it.
Time is measured in nanoseconds between the current time and midnight, January 1, 1970 UTC.
Parameters
timeNanos The time of this analytic order in nanoseconds.
Returns
The current analytic order.
References Order::withTimeNanos().
withTradeId()
AnalyticOrder & AnalyticOrder::withTradeId (std::int64_t tradeId) inline noexcept
Changes trade ID.
Returns the current analytic order.
Parameters
tradeId The trade ID.
Returns
The current analytic order.
References Order::withTradeId().
withTradePrice()
AnalyticOrder & AnalyticOrder::withTradePrice (double tradePrice) inline noexcept
Changes trade price.
Returns the current analytic order.
Parameters
tradePrice The trade price.
Returns
The current analytic order.
References Order::withTradePrice().
withTradeSize()
AnalyticOrder & AnalyticOrder::withTradeSize (double tradeSize) inline noexcept
Changes trade size.
Returns the current analytic order.
Parameters
tradeSize The trade size.
Returns
The current analytic order.
References Order::withTradeSize().