dxFeed Graal CXX API: dxfcpp::IndexedEventSubscriptionSymbol Class Reference
dxfcpp::IndexedEventSubscriptionSymbol Class Reference
Represents subscription to a specific source of indexed events.
#include <IndexedEventSubscriptionSymbol.hpp>
Public Member Functions
IndexedEventSubscriptionSymbol (const SymbolWrapper &eventSymbol, const IndexedEventSource &source) noexcept
Creates indexed event subscription symbol with a specified event symbol and source.
virtual const std::unique_ptr< SymbolWrapper > & getEventSymbol () const
Returns the wrapped event symbol (CandleSymbol, WildcardSymbol, etc).
virtual const IndexedEventSource & getSource () const
Returns indexed event source.
virtual std::string toString () const noexcept
Returns string representation of this indexed event subscription symbol.
Protected Member Functions
virtual void * toGraal () const noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Static Protected Member Functions
static void freeGraal (void *graalNative) noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
static IndexedEventSubscriptionSymbol fromGraal (void *graalNative) noexcept
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure (recursively if necessary).
Detailed Description
Represents subscription to a specific source of indexed events.
This is symbol is observed by ObservableSubscriptionChangeListener methods symbolsAdded and symbolsRemoved when subscription to IndexedEvent is defined.
Instances of this class can be used with DXFeedSubscription to specify subscription to a particular source of indexed events. By default, when subscribing to indexed events by their event symbol object, the subscription is performed to all supported sources.
Equality and hash codes
Indexed event subscription symbols are compared based on their eventSymbol and source.
Constructor & Destructor Documentation
IndexedEventSubscriptionSymbol()
dxfcpp::IndexedEventSubscriptionSymbol::IndexedEventSubscriptionSymbol (const SymbolWrapper & eventSymbol, const IndexedEventSource & source) noexcept
Creates indexed event subscription symbol with a specified event symbol and source.
Parameters
eventSymbol the wrapped event symbol (CandleSymbol, WildcardSymbol, etc).
source the source.
References IndexedEventSubscriptionSymbol().
Referenced by IndexedEventSubscriptionSymbol().
Member Function Documentation
freeGraal()
void dxfcpp::IndexedEventSubscriptionSymbol::freeGraal (void * graalNative) static protected noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
References dxfcpp::IndexedEventSource::freeGraal(), and dxfcpp::SymbolWrapper::freeGraal().
Referenced by dxfcpp::SymbolWrapper::freeGraal().
fromGraal()
IndexedEventSubscriptionSymbol dxfcpp::IndexedEventSubscriptionSymbol::fromGraal (void * graalNative) static protected noexcept
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Returns
The object of current type.
getEventSymbol()
const std::unique_ptr< SymbolWrapper > & dxfcpp::IndexedEventSubscriptionSymbol::getEventSymbol () const virtual
Returns the wrapped event symbol (CandleSymbol, WildcardSymbol, etc).
Returns
the wrapped event symbol.
getSource()
const IndexedEventSource & dxfcpp::IndexedEventSubscriptionSymbol::getSource () const virtual
Returns indexed event source.
Returns
indexed event source.
toGraal()
void * dxfcpp::IndexedEventSubscriptionSymbol::toGraal () const protected virtual noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Reimplemented in dxfcpp::TimeSeriesSubscriptionSymbol.
toString()
std::string dxfcpp::IndexedEventSubscriptionSymbol::toString () const virtual noexcept
Returns string representation of this indexed event subscription symbol.
Returns
string representation of this indexed event subscription symbol.
Reimplemented in dxfcpp::TimeSeriesSubscriptionSymbol.