dxFeed Graal CXX API: dxfcpp::IndexedEventSource Class Reference
dxfcpp::IndexedEventSource Class Reference
Source identifier for IndexedEvent.
#include <IndexedEventSource.hpp>
Public Member Functions
IndexedEventSource (std::int32_t id, std::string name) noexcept
Creates the new IndexedEvent's source by id and name.
std::int32_t id () const noexcept
Returns the source identifier.
const std::string & name () const noexcept
Returns the string representation of the object.
std::string toString () const noexcept
Returns the string representation of the object.
virtual void * toGraal () const noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Static Public Member Functions
static void freeGraal (void *graalNative) noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Attributes
static const IndexedEventSource DEFAULT {0, "DEFAULT"}
The default source with zero identifier for all events that do not support multiple sources.
Detailed Description
Source identifier for IndexedEvent.
See IndexedEvent::getSource().
Constructor & Destructor Documentation
IndexedEventSource()
dxfcpp::IndexedEventSource::IndexedEventSource (std::int32_t id, std::string name) inline noexcept
Creates the new IndexedEvent's source by id and name.
Parameters
id The source id
name The source name
Member Function Documentation
freeGraal()
void dxfcpp::IndexedEventSource::freeGraal (void * graalNative) static noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Referenced by dxfcpp::IndexedEventSubscriptionSymbol::freeGraal().
id()
std::int32_t dxfcpp::IndexedEventSource::id () const inline noexcept
Returns the source identifier.
Source identifier is non-negative.
Returns
The source identifier.
Referenced by dxfcpp::OrderSource::isSpecialSourceId(), and dxfcpp::OrderBase::setSource().
name()
const std::string& dxfcpp::IndexedEventSource::name () const inline noexcept
Returns the string representation of the object.
Returns
The string representation of the object.
toGraal()
void * dxfcpp::IndexedEventSource::toGraal () const virtual noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
toString()
std::string dxfcpp::IndexedEventSource::toString () const inline noexcept
Returns the string representation of the object.
Returns
The string representation of the object.