dxFeed Graal CXX API: Summary Class Reference
Summary Class Reference final
Summary information snapshot about the trading session including session highs, lows, etc.
#include <Summary.hpp>
Public Types
using Ptr = std::shared_ptr< Summary >
The alias to a type of shared pointer to the Summary object.
using Unique = std::unique_ptr< Summary >
The alias to a type of unique pointer to the Summary object.
Public Types inherited from MarketEvent
using Ptr = std::shared_ptr< MarketEvent >
The alias to a type of shared pointer to the MarketEvent object.
Public Types inherited from EventTypeWithSymbol< std::string >
using Ptr = std::shared_ptr< EventTypeWithSymbol< std::string > >
The alias to a type of shared pointer to the EventTypeWithSymbol's child object.
Public Types inherited from EventType
using Ptr = std::shared_ptr< EventType >
The alias to a type of shared pointer to the EventType object.
Public Types inherited from SharedEntity
using Ptr = std::shared_ptr< SharedEntity >
The alias to a type of shared pointer to the SharedEntity object.
Public Types inherited from LastingEvent
using Ptr = std::shared_ptr< LastingEvent >
The alias to a type of shared pointer to the LastingEvent object.
Public Member Functions
void * toGraal () const override
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Summary () noexcept=default
Creates new summary event with default values.
Summary (std::string eventSymbol) noexcept
Creates new summary event with the specified event symbol.
std::int32_t getDayId () const noexcept
Returns identifier of the day that this summary represents.
void setDayId (std::int32_t dayId) noexcept
Changes identifier of the day that this summary represents.
double getDayOpenPrice () const noexcept
Returns the first (open) price for the day.
void setDayOpenPrice (double dayOpenPrice) noexcept
Changes the first (open) price for the day.
double getDayHighPrice () const noexcept
Returns the maximal (high) price for the day.
void setDayHighPrice (double dayHighPrice) noexcept
Changes the maximal (high) price for the day.
double getDayLowPrice () const noexcept
Returns the minimal (low) price for the day.
void setDayLowPrice (double dayLowPrice) noexcept
Changes the minimal (low) price for the day.
double getDayClosePrice () const noexcept
Returns the last (close) price for the day.
void setDayClosePrice (double dayClosePrice) noexcept
Changes the last (close) price for the day.
const PriceType & getDayClosePriceType () const &noexcept
Returns the price type of the last (close) price for the day.
void setDayClosePriceType (const PriceType &type) noexcept
Changes the price type of the last (close) price for the day.
std::int32_t getPrevDayId () const noexcept
Returns identifier of the previous day that this summary represents.
void setPrevDayId (std::int32_t prevDayId) noexcept
Changes identifier of the previous day that this summary represents.
double getPrevDayClosePrice () const noexcept
Returns the last (close) price for the previous day.
void setPrevDayClosePrice (double prevDayClosePrice) noexcept
Changes the last (close) price for the previous day.
const PriceType & getPrevDayClosePriceType () const &noexcept
Returns the price type of the last (close) price for the previous day.
void setPrevDayClosePriceType (const PriceType &type) noexcept
Changes the price type of the last (close) price for the previous day.
double getPrevDayVolume () const noexcept
Returns total volume traded for the previous day.
void setPrevDayVolume (double prevDayVolume) noexcept
Changes total volume traded for the previous day.
std::int64_t getOpenInterest () const noexcept
Returns open interest of the symbol as the number of open contracts.
void setOpenInterest (std::int64_t openInterest) noexcept
Changes open interest of the symbol as the number of open contracts.
std::string toString () const noexcept override
Returns a string representation of the current object.
Public Member Functions inherited from MarketEvent
const std::string & getEventSymbol () const &noexcept override
Returns symbol of this event.
const std::optional< std::string > & getEventSymbolOpt () const &noexcept override
Returns symbol of this event.
void setEventSymbol (const std::string &eventSymbol) noexcept override
Changes symbol of this event.
std::int64_t getEventTime () const noexcept override
Returns time when event was created or zero when time is not available.
void setEventTime (std::int64_t eventTime) noexcept override
Changes event creation time.
Public Member Functions inherited from SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
Public Member Functions inherited from Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Static Public Member Functions
static Ptr fromGraal (void *graalNative)
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
static void freeGraal (void *graalNative)
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Attributes
static const EventTypeEnum & TYPE = EventTypeEnum::SUMMARY
Type identifier and additional information about the current event class.
Additional Inherited Members
Protected Member Functions inherited from MarketEvent
MarketEvent (std::string eventSymbol) noexcept
Protected constructor for concrete implementation classes that initializes eventSymbol property.
Detailed Description
Summary information snapshot about the trading session including session highs, lows, etc.
It represents the most recent information that is available about the trading session in the market at any given moment of time.
Constructor & Destructor Documentation
Summary()
Summary::Summary (std::string eventSymbol) inline explicit noexcept
Creates new summary event with the specified event symbol.
Parameters
eventSymbol The event symbol.
References MarketEvent::MarketEvent().
Member Function Documentation
freeGraal()
void Summary::freeGraal (void * graalNative) static
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
fromGraal()
std::shared_ptr< Summary > Summary::fromGraal (void * graalNative) static
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Returns
The object of current type.
Exceptions
std::invalid_argument
getDayClosePrice()
double Summary::getDayClosePrice () const inline noexcept
Returns the last (close) price for the day.
Returns
the last (close) price for the day.
getDayClosePriceType()
const PriceType& Summary::getDayClosePriceType () const & inline noexcept
Returns the price type of the last (close) price for the day.
Returns
the price type of the last (close) price for the day.
getDayHighPrice()
double Summary::getDayHighPrice () const inline noexcept
Returns the maximal (high) price for the day.
Returns
the maximal (high) price for the day.
getDayId()
std::int32_t Summary::getDayId () const inline noexcept
Returns identifier of the day that this summary represents.
Identifier of the day is the number of days passed since January 1, 1970.
Returns
identifier of the day that this summary represents.
getDayLowPrice()
double Summary::getDayLowPrice () const inline noexcept
Returns the minimal (low) price for the day.
Returns
the minimal (low) price for the day.
getDayOpenPrice()
double Summary::getDayOpenPrice () const inline noexcept
Returns the first (open) price for the day.
Returns
the first (open) price for the day.
getOpenInterest()
std::int64_t Summary::getOpenInterest () const inline noexcept
Returns open interest of the symbol as the number of open contracts.
Returns
open interest of the symbol as the number of open contracts.
getPrevDayClosePrice()
double Summary::getPrevDayClosePrice () const inline noexcept
Returns the last (close) price for the previous day.
Returns
the last (close) price for the previous day.
getPrevDayClosePriceType()
const PriceType& Summary::getPrevDayClosePriceType () const & inline noexcept
Returns the price type of the last (close) price for the previous day.
Returns
the price type of the last (close) price for the previous day.
getPrevDayId()
std::int32_t Summary::getPrevDayId () const inline noexcept
Returns identifier of the previous day that this summary represents.
Identifier of the day is the number of days passed since January 1, 1970.
Returns
identifier of the previous day that this summary represents.
getPrevDayVolume()
double Summary::getPrevDayVolume () const inline noexcept
Returns total volume traded for the previous day.
Returns
total volume traded for the previous day.
setDayClosePrice()
void Summary::setDayClosePrice (double dayClosePrice) inline noexcept
Changes the last (close) price for the day.
Parameters
dayClosePrice the last (close) price for the day.
setDayClosePriceType()
void Summary::setDayClosePriceType (const PriceType & type) inline noexcept
Changes the price type of the last (close) price for the day.
Parameters
type the price type of the last (close) price for the day.
setDayHighPrice()
void Summary::setDayHighPrice (double dayHighPrice) inline noexcept
Changes the maximal (high) price for the day.
Parameters
dayHighPrice the maximal (high) price for the day.
setDayId()
void Summary::setDayId (std::int32_t dayId) inline noexcept
Changes identifier of the day that this summary represents.
Identifier of the day is the number of days passed since January 1, 1970.
Parameters
dayId identifier of the day that this summary represents.
setDayLowPrice()
void Summary::setDayLowPrice (double dayLowPrice) inline noexcept
Changes the minimal (low) price for the day.
Parameters
dayLowPrice the minimal (low) price for the day.
setDayOpenPrice()
void Summary::setDayOpenPrice (double dayOpenPrice) inline noexcept
Changes the first (open) price for the day.
Parameters
dayOpenPrice the first (open) price for the day.
setOpenInterest()
void Summary::setOpenInterest (std::int64_t openInterest) inline noexcept
Changes open interest of the symbol as the number of open contracts.
Parameters
openInterest open interest of the symbol as the number of open contracts.
setPrevDayClosePrice()
void Summary::setPrevDayClosePrice (double prevDayClosePrice) inline noexcept
Changes the last (close) price for the previous day.
Parameters
prevDayClosePrice the last (close) price for the previous day.
setPrevDayClosePriceType()
void Summary::setPrevDayClosePriceType (const PriceType & type) inline noexcept
Changes the price type of the last (close) price for the previous day.
Parameters
type the price type of the last (close) price for the previous day.
setPrevDayId()
void Summary::setPrevDayId (std::int32_t prevDayId) inline noexcept
Changes identifier of the previous day that this summary represents.
Identifier of the day is the number of days passed since January 1, 1970.
Parameters
prevDayId identifier of the previous day that this summary represents.
setPrevDayVolume()
void Summary::setPrevDayVolume (double prevDayVolume) inline noexcept
Changes total volume traded for the previous day.
Parameters
prevDayVolume total volume traded for the previous day.
toGraal()
void * Summary::toGraal () const override virtual
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Implements EventType.
References toString().
toString()
std::string Summary::toString () const override virtual noexcept
Returns a string representation of the current object.
Returns
a string representation
Reimplemented from EventType.
Referenced by toGraal().