dxFeed Graal CXX API: dxfcpp::DXEndpoint::Builder Class Reference
dxfcpp::DXEndpoint::Builder Class Reference
Builder class for DXEndpoint that supports additional configuration properties.
#include <DXEndpoint.hpp>
Inherits std::enable_shared_from_this< Builder >.
Public Member Functions
virtual ~Builder ()
Releases the GraalVM handle.
std::shared_ptr< Builder > withName (const std::string &name)
Changes name that is used to distinguish multiple endpoints in the same process (GraalVM Isolate) in logs and in other diagnostic means.
std::shared_ptr< Builder > withRole (Role role)
Sets role for the created DXEndpoint.
std::shared_ptr< Builder > withProperty (const std::string &key, const std::string &value)
Sets the specified property.
template<typename Properties >
std::shared_ptr< Builder > withProperties (Properties &&properties)
Sets all supported properties from the provided properties object.
bool supportsProperty (const std::string &key)
Checks if a property is supported.
std::shared_ptr< DXEndpoint > build ()
Builds DXEndpoint instance.
Detailed Description
Builder class for DXEndpoint that supports additional configuration properties.
Member Function Documentation
build()
std::shared_ptr< DXEndpoint > dxfcpp::DXEndpoint::Builder::build ()
Builds DXEndpoint instance.
Returns
the created endpoint.
supportsProperty()
bool dxfcpp::DXEndpoint::Builder::supportsProperty (const std::string & key)
Checks if a property is supported.
Parameters
key The property's key to be checked for support
Returns
true if the corresponding property key is supported.
See also
::withProperty(const std::string&, const std::string&)
withName()
std::shared_ptr<Builder> dxfcpp::DXEndpoint::Builder::withName (const std::string & name) inline
Changes name that is used to distinguish multiple endpoints in the same process (GraalVM Isolate) in logs and in other diagnostic means.
This is a shortcut for withProperty(::NAME_PROPERTY, name)
Parameters
name The endpoint's name
Returns
this endpoint builder.
References dxfcpp::DXEndpoint::NAME_PROPERTY, and withProperty().
withProperties()
template<typename Properties > std::shared_ptr<Builder> dxfcpp::DXEndpoint::Builder::withProperties (Properties && properties) inline
Sets all supported properties from the provided properties object.
Template Parameters
Properties The properties' type (std::map, std::unordered_map etc)
Parameters
properties The endpoint's properties
Returns
this endpoint builder.
See also
::withProperty(const std::string&, const std::string&)
References withProperty().
withProperty()
std::shared_ptr< DXEndpoint::Builder > dxfcpp::DXEndpoint::Builder::withProperty (const std::string & key, const std::string & value)
Sets the specified property.
Unsupported properties are ignored.
Parameters
key The endpoint's property key
value The endpoint's property value
Returns
this endpoint builder.
See also
::supportsProperty(const std::string&)
Referenced by withName(), and withProperties().
withRole()
std::shared_ptr< DXEndpoint::Builder > dxfcpp::DXEndpoint::Builder::withRole (DXEndpoint::Role role)
Sets role for the created DXEndpoint.
Default role is FEED.
Parameters
role The endpoint's role
Returns
this endpoint builder.