dxFeed Graal CXX API: dxfcpp::SpreadOrder Class Reference
dxfcpp::SpreadOrder Class Reference
Spread order event is a snapshot for a full available market depth for all spreads on a given underlying symbol.
#include <SpreadOrder.hpp>
Public Types
using Ptr = std::shared_ptr< SpreadOrder >
The alias to a type of shared pointer to the SpreadOrder object.
using Unique = std::unique_ptr< SpreadOrder >
The alias to a type of unique pointer to the SpreadOrder object.
Public Types inherited from dxfcpp::MarketEvent
using Ptr = std::shared_ptr< MarketEvent >
The alias to a type of shared pointer to the MarketEvent object.
Public Types inherited from dxfcpp::EventTypeWithSymbol< std::string >
using Ptr = std::shared_ptr< EventTypeWithSymbol< std::string > >
The alias to a type of shared pointer to the EventTypeWithSymbol's child object.
Public Types inherited from dxfcpp::EventType
using Ptr = std::shared_ptr< EventType >
The alias to a type of shared pointer to the EventType object.
Public Types inherited from dxfcpp::SharedEntity
using Ptr = std::shared_ptr< SharedEntity >
The alias to a type of shared pointer to the SharedEntity object.
Public Types inherited from dxfcpp::IndexedEvent
using Ptr = std::shared_ptr< IndexedEvent >
The alias to a type of shared pointer to the IndexedEvent object.
Public Member Functions
void * toGraal () const noexcept override
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
SpreadOrder () noexcept=default
Creates new spread order event with default values.
SpreadOrder (std::string eventSymbol) noexcept
Creates new spread order event with the specified event symbol.
SpreadOrder & withEventSymbol (const std::string &eventSymbol) noexcept
Changes event's symbol and returns the current spread order.
SpreadOrder::Ptr withEventSymbolShared (const std::string &eventSymbol) noexcept
Changes event's symbol and returns a shared pointer to the current spread order.
SpreadOrder & withEventTime (std::int64_t eventTime) noexcept
Changes event's creation time and returns the current spread order.
SpreadOrder::Ptr withEventTimeShared (std::int64_t eventTime) noexcept
Changes event's creation time and returns a shared pointer to the current spread order.
SpreadOrder & withSource (const OrderSource &source) noexcept
Changes event's source and returns the current spread order.
SpreadOrder::Ptr withSourceShared (const OrderSource &source) noexcept
Changes event's source and returns a shared pointer to the current spread order.
SpreadOrder & withEventFlags (std::int32_t eventFlags) noexcept
Changes transactional event flags and returns the current spread order.
SpreadOrder::Ptr withEventFlagsShared (std::int32_t eventFlags) noexcept
Changes transactional event flags and returns a shared pointer to the current spread order.
SpreadOrder & withEventFlags (const EventFlagsMask &eventFlags) noexcept
Changes transactional event flags and returns the current spread order.
SpreadOrder::Ptr withEventFlagsShared (const EventFlagsMask &eventFlags) noexcept
Changes transactional event flags and returns a shared pointer to the current spread order.
SpreadOrder & withIndex (std::int64_t index) noexcept
Changes unique per-symbol index of this spread order and returns it.
SpreadOrder::Ptr withIndexShared (std::int64_t index) noexcept
Changes unique per-symbol index of this spread order and returns a shared pointer to it.
SpreadOrder & withTime (std::int64_t time) noexcept
Changes time of this spread order and returns it.
SpreadOrder::Ptr withTimeShared (std::int64_t time) noexcept
Changes time of this spread order and returns a shared pointer to it.
SpreadOrder & withTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds time part of this spread order.
SpreadOrder::Ptr withTimeNanoPartShared (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds time part of this spread order.
SpreadOrder & withSequence (std::int32_t sequence) noexcept
Changes sequence number of this spread order.
SpreadOrder::Ptr withSequenceShared (std::int32_t sequence) noexcept
Changes sequence number of this spread order.
SpreadOrder & withTimeNanos (std::int64_t timeNanos) noexcept
Changes time of this spread order and returns it.
SpreadOrder::Ptr withTimeNanosShared (std::int64_t timeNanos) noexcept
Changes time of this spread order.
SpreadOrder & withAction (const OrderAction &action) noexcept
Changes action of this spread order and returns it.
SpreadOrder::Ptr withActionShared (const OrderAction &action) noexcept
Changes action of this spread order.
SpreadOrder & withActionTime (std::int64_t actionTime) noexcept
Changes time of the last action and returns current spread order.
SpreadOrder::Ptr withActionTimeShared (std::int64_t actionTime) noexcept
Changes time of the last action and returns a shared pointer to the current spread order.
SpreadOrder & withOrderId (std::int64_t orderId) noexcept
Changes order ID.
SpreadOrder::Ptr withOrderIdShared (std::int64_t orderId) noexcept
Changes spread order ID.
SpreadOrder & withAuxOrderId (std::int64_t auxOrderId) noexcept
Changes auxiliary spread order ID.
SpreadOrder::Ptr withAuxOrderIdShared (std::int64_t auxOrderId) noexcept
Changes auxiliary spread order ID.
SpreadOrder & withPrice (double price) noexcept
Changes price of this spread order.
SpreadOrder::Ptr withPriceShared (double price) noexcept
Changes price of this spread order.
SpreadOrder & withSize (double size) noexcept
Changes size of this spread order.
SpreadOrder::Ptr withSizeShared (double size) noexcept
Changes size of this spread order.
SpreadOrder & withExecutedSize (double executedSize) noexcept
Changes executed size of this spread order.
SpreadOrder::Ptr withExecutedSizeShared (double executedSize) noexcept
Changes executed size of this spread order.
SpreadOrder & withCount (std::int64_t count) noexcept
Changes number of individual spread orders in this aggregate spread order.
SpreadOrder::Ptr withCountShared (std::int64_t count) noexcept
Changes number of individual spread orders in this aggregate spread order.
SpreadOrder & withTradeId (std::int64_t tradeId) noexcept
Changes trade ID.
SpreadOrder::Ptr withTradeShared (std::int64_t tradeId) noexcept
Changes trade ID.
SpreadOrder & withTradePrice (double tradePrice) noexcept
Changes trade price.
SpreadOrder::Ptr withTradePriceShared (double tradePrice) noexcept
Changes trade price.
SpreadOrder & withTradeSize (double tradeSize) noexcept
Changes trade size.
SpreadOrder::Ptr withTradeSizeShared (double tradeSize) noexcept
Changes trade size.
SpreadOrder & withExchangeCode (char exchangeCode) noexcept
Changes exchange code of this spread order.
SpreadOrder::Ptr withExchangeCodeShared (char exchangeCode) noexcept
Changes exchange code of this spread order.
SpreadOrder & withExchangeCode (std::int16_t exchangeCode) noexcept
Changes exchange code of this spread order.
SpreadOrder::Ptr withExchangeCodeShared (std::int16_t exchangeCode) noexcept
Changes exchange code of this spread order.
SpreadOrder & withOrderSide (const Side &side) noexcept
Changes side of this spread order.
SpreadOrder::Ptr withOrderSideShared (const Side &side) noexcept
Changes side of this spread order.
SpreadOrder & withScope (const Scope &scope) noexcept
Changes scope of this spread order.
SpreadOrder::Ptr withScopeShared (const Scope &scope) noexcept
Changes scope of this spread order.
const std::string & getSpreadSymbol () const &noexcept
Returns spread symbol of this event.
const std::optional< std::string > & getSpreadSymbolOpt () const &noexcept
Returns spread symbol of this event.
void setSpreadSymbol (std::string spreadSymbol) noexcept
Changes spread symbol of this event.
SpreadOrder & withSpreadSymbol (std::string spreadSymbol) noexcept
Changes spread symbol of this event.
SpreadOrder::Ptr withSpreadSymbolShared (std::string spreadSymbol) noexcept
Changes spread symbol of this event.
std::string toString () const noexcept override
Returns a string representation of the current object.
Public Member Functions inherited from dxfcpp::OrderBase
OrderBase () noexcept=default
Creates new order event with default values.
OrderBase (std::string eventSymbol) noexcept
Creates new order event with the specified event symbol.
const OrderSource & getSource () const &noexcept override
Returns source of this event.
void setSource (const OrderSource &source) noexcept
Changes source of this event.
std::int32_t getEventFlags () const noexcept override
Returns transactional event flags.
EventFlagsMask getEventFlagsMask () const noexcept override
Returns transactional event flags.
void setEventFlags (std::int32_t eventFlags) noexcept override
Changes transactional event flags.
void setEventFlags (const EventFlagsMask &eventFlags) noexcept override
Changes transactional event flags.
void setIndex (std::int64_t index) noexcept override
Changes unique per-symbol index of this order.
std::int64_t getIndex () const noexcept override
Returns unique per-symbol index of this order.
std::int64_t getTimeSequence () const noexcept
Returns time and sequence of this order packaged into single long value.
void setTimeSequence (std::int64_t timeSequence) noexcept
Changes time and sequence of this order.
std::int64_t getTime () const noexcept
Returns time of this order.
void setTime (std::int64_t time) noexcept
Changes time of this order.
void setTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds time part of this order.
std::int32_t getTimeNanoPart () const noexcept
Returns microseconds and nanoseconds time part of this order.
std::int32_t getSequence () const noexcept
Returns sequence number of this order to distinguish orders that have the same time.
void setSequence (std::int32_t sequence) noexcept
Changes sequence number of this order.
std::int64_t getTimeNanos () const noexcept
Returns time of this order in nanoseconds.
void setTimeNanos (std::int64_t timeNanos) noexcept
Changes time of this order.
const OrderAction & getAction () const &noexcept
Returns order action if available, otherwise - OrderAction::UNDEFINED.
void setAction (const OrderAction &action) noexcept
Changes action of this order.
std::int64_t getActionTime () const noexcept
Returns time of the last action.
void setActionTime (std::int64_t actionTime) noexcept
Changes time of the last action.
std::int64_t getOrderId () const noexcept
Returns order ID if available.
void setOrderId (std::int64_t orderId) noexcept
Changes order ID.
std::int64_t getAuxOrderId () const noexcept
Returns auxiliary order ID if available:
void setAuxOrderId (std::int64_t auxOrderId) noexcept
Changes auxiliary order ID.
double getPrice () const noexcept
Returns price of this order.
void setPrice (double price) noexcept
Changes price of this order.
double getSize () const noexcept
Returns size of this order.
void setSize (double size) noexcept
Changes size of this order.
bool hasSize () const noexcept
Returns true if this order has some size (sizeAsDouble is neither 0 nor NaN).
double getExecutedSize () const noexcept
Returns executed size of this order.
void setExecutedSize (double executedSize) noexcept
Changes executed size of this order.
std::int64_t getCount () const noexcept
Returns number of individual orders in this aggregate order.
void setCount (std::int64_t count) noexcept
Changes number of individual orders in this aggregate order.
std::int64_t getTradeId () const noexcept
Returns trade (order execution) ID for events containing trade-related action.
void setTradeId (std::int64_t tradeId) noexcept
Changes trade ID.
double getTradePrice () const noexcept
Returns trade price for events containing trade-related action.
void setTradePrice (double tradePrice) noexcept
Changes trade price.
double getTradeSize () const noexcept
Returns trade size for events containing trade-related action.
void setTradeSize (double tradeSize) noexcept
Changes trade size.
std::int16_t getExchangeCode () const noexcept
Returns exchange code of this order.
std::string getExchangeCodeString () const noexcept
Returns exchange code of this order as UTF8 string.
void setExchangeCode (char exchangeCode) noexcept
Changes exchange code of this order.
void setExchangeCode (std::int16_t exchangeCode) noexcept
Changes exchange code of this order.
const Side & getOrderSide () const &noexcept
Returns side of this order.
void setOrderSide (const Side &side) noexcept
Changes side of this order.
const Scope & getScope () const &noexcept
Returns scope of this order.
void setScope (const Scope &scope) noexcept
Changes scope of this order.
std::string baseFieldsToString () const noexcept
Returns string representation of this order event's fields.
Public Member Functions inherited from dxfcpp::MarketEvent
const std::string & getEventSymbol () const &noexcept override
Returns symbol of this event.
const std::optional< std::string > & getEventSymbolOpt () const &noexcept override
Returns symbol of this event.
void setEventSymbol (const std::string &eventSymbol) noexcept override
Changes symbol of this event.
std::int64_t getEventTime () const noexcept override
Returns time when event was created or zero when time is not available.
void setEventTime (std::int64_t eventTime) noexcept override
Changes event creation time.
Public Member Functions inherited from dxfcpp::SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
Public Member Functions inherited from dxfcpp::Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Static Public Member Functions
static void freeGraal (void *graalNative) noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Attributes
static const EventTypeEnum & TYPE = EventTypeEnum::SPREAD_ORDER
Type identifier and additional information about the current event class.
Static Public Attributes inherited from dxfcpp::OrderBase
static constexpr std::uint32_t MAX_SEQUENCE = (1U << 22U) - 1U
Maximum allowed sequence value.
Static Public Attributes inherited from dxfcpp::IndexedEvent
static const EventFlag TX_PENDING = EventFlag::TX_PENDING
0x01 - A bitmask to get transaction pending indicator from the value of eventFlags property.
static const EventFlag REMOVE_EVENT = EventFlag::REMOVE_EVENT
0x02 - A bitmask to get removal indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_BEGIN = EventFlag::SNAPSHOT_BEGIN
0x04 - A bitmask to get snapshot begin indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_END = EventFlag::SNAPSHOT_END
0x08 - A bitmask to get snapshot end indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_SNIP = EventFlag::SNAPSHOT_SNIP
0x10 - A bitmask to get snapshot snip indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_MODE = EventFlag::SNAPSHOT_MODE
0x40 - A bitmask to set snapshot mode indicator into the value of eventFlags property.
Additional Inherited Members
Protected Member Functions inherited from dxfcpp::MarketEvent
MarketEvent (std::string eventSymbol) noexcept
Protected constructor for concrete implementation classes that initializes eventSymbol property.
Detailed Description
Spread order event is a snapshot for a full available market depth for all spreads on a given underlying symbol.
The collection of spread order events of a symbol represents the most recent information that is available about spread orders on the market at any given moment of time.
Spread order is similar to a regular Order, but it has a spreadSymbol property that contains the symbol of the actual spread that is being represented by spread order object. eventSymbol property contains the underlying symbol that was used in subscription.
Like regular orders, spread order events arrive from multiple sources for the same market symbol and are distinguished by their index. It is unique across all the sources of depth information for the symbol. The event with size either 0 or NaN is a signal to remove previously received order for the corresponding index. The method hasSize is a convenient method to test for size presence.
Event flags, transactions and snapshots
Some spread order event sources provide a consistent view of the price-level or detailed order book. Their updates may incorporate multiple changes to price levels or to individual orders that have to be processed at the same time. The corresponding information is carried in eventFlags property.
See Event Flags section of OrderBase class documentation for details.
IndexedEventModel class handles all the snapshot and transaction logic and conveniently represents a list current of events. It relies on the code of AbstractIndexedEventModel to handle this logic. Use the source code of AbstractIndexedEventModel for clarification on transactions and snapshot logic.
Publishing order books
When publishing an order event with DXPublisher::publishEvents() method, least significant 32 bits of order index must be in a range of from 0 to std::numeric_limits<std::int32_t>::max() inclusive. Use setSource method after setIndex to properly include source identifier into the index.
A snapshot has to be published in the descending order of index, starting with an event with the largest index and marking it with SpreadOrder::SNAPSHOT_BEGIN bit in eventFlags, and finishing the snapshot with an event that has zero 32 least significant bits of index. SpreadOrder::SNAPSHOT_END bit in eventFlags is optional during publishing. It will be properly set on receiving end anyway.
Limitations
This event type cannot be used with DXFeed::getLastEvent() method.
Full Order Book Support
Some feeds provide support for "Full Order Book" (FOB) where additional fields will be available:
action - event business meaning (see OrderAction for more details)
actionTime - time of the last action
orderId - ID of this order
auxOrderId - additional ID for this order
tradeId - trade (order execution) ID
tradePrice - price of the trade
tradeSize - size of the trade
Implementation details
This event is implemented on top of QDS records SpreadOrder#<source-id>, where <source-id> is up to 4 ASCII characters with a mnemonic for the source like "ISE".
Constructor & Destructor Documentation
SpreadOrder()
dxfcpp::SpreadOrder::SpreadOrder (std::string eventSymbol) inline explicit noexcept
Creates new spread order event with the specified event symbol.
Parameters
eventSymbol The event symbol.
Member Function Documentation
freeGraal()
void dxfcpp::SpreadOrder::freeGraal (void * graalNative) static noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
getSpreadSymbol()
const std::string& dxfcpp::SpreadOrder::getSpreadSymbol () const & inline noexcept
Returns spread symbol of this event.
Returns
spread symbol of this event or dxfcpp::String::NUL (std::string{"<null>"}).
getSpreadSymbolOpt()
const std::optional<std::string>& dxfcpp::SpreadOrder::getSpreadSymbolOpt () const & inline noexcept
Returns spread symbol of this event.
Returns
spread symbol of this event or std::nullopt
setSpreadSymbol()
void dxfcpp::SpreadOrder::setSpreadSymbol (std::string spreadSymbol) inline noexcept
Changes spread symbol of this event.
Parameters
spreadSymbol spread symbol of this event.
Referenced by withSpreadSymbol(), and withSpreadSymbolShared().
toGraal()
void * dxfcpp::SpreadOrder::toGraal () const override virtual noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Implements dxfcpp::EventType.
References toString().
toString()
std::string dxfcpp::SpreadOrder::toString () const override virtual noexcept
Returns a string representation of the current object.
Returns
a string representation
Reimplemented from dxfcpp::EventType.
Referenced by toGraal().
withAction()
SpreadOrder& dxfcpp::SpreadOrder::withAction (const OrderAction & action) inline noexcept
Changes action of this spread order and returns it.
Parameters
action The side of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setAction().
withActionShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withActionShared (const OrderAction & action) inline noexcept
Changes action of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
action The action of this spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setAction().
withActionTime()
SpreadOrder& dxfcpp::SpreadOrder::withActionTime (std::int64_t actionTime) inline noexcept
Changes time of the last action and returns current spread order.
Parameters
actionTime The last spread order action time.
Returns
The current spread order.
References dxfcpp::OrderBase::setActionTime().
withActionTimeShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withActionTimeShared (std::int64_t actionTime) inline noexcept
Changes time of the last action and returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
actionTime The last spread order action time.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setActionTime().
withAuxOrderId()
SpreadOrder& dxfcpp::SpreadOrder::withAuxOrderId (std::int64_t auxOrderId) inline noexcept
Changes auxiliary spread order ID.
Returns the current spread order.
Parameters
auxOrderId The auxiliary spread order ID.
Returns
The current spread order.
References dxfcpp::OrderBase::setAuxOrderId().
withAuxOrderIdShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withAuxOrderIdShared (std::int64_t auxOrderId) inline noexcept
Changes auxiliary spread order ID.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
auxOrderId The auxiliary spread order ID.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setAuxOrderId().
withCount()
SpreadOrder& dxfcpp::SpreadOrder::withCount (std::int64_t count) inline noexcept
Changes number of individual spread orders in this aggregate spread order.
Returns the current spread order.
Parameters
count The number of individual orders in this aggregate spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setCount().
withCountShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withCountShared (std::int64_t count) inline noexcept
Changes number of individual spread orders in this aggregate spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
count The number of individual spread orders in this aggregate spread spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setCount().
withEventFlags() [1/2]
SpreadOrder& dxfcpp::SpreadOrder::withEventFlags (const EventFlagsMask & eventFlags) inline noexcept
Changes transactional event flags and returns the current spread order.
See EventFlag "Event Flags" section.
Parameters
eventFlags The transactional event flags' mask.
Returns
The current spread order.
withEventFlags() [2/2]
SpreadOrder& dxfcpp::SpreadOrder::withEventFlags (std::int32_t eventFlags) inline noexcept
Changes transactional event flags and returns the current spread order.
See EventFlag "Event Flags" section.
Parameters
eventFlags The transactional event flags.
Returns
The current spread order.
withEventFlagsShared() [1/2]
SpreadOrder::Ptr dxfcpp::SpreadOrder::withEventFlagsShared (const EventFlagsMask & eventFlags) inline noexcept
Changes transactional event flags and returns a shared pointer to the current spread order.
See EventFlag "Event Flags" section.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
eventFlags The transactional event flags' mask.
Returns
A shared pointer to the current spread order.
withEventFlagsShared() [2/2]
SpreadOrder::Ptr dxfcpp::SpreadOrder::withEventFlagsShared (std::int32_t eventFlags) inline noexcept
Changes transactional event flags and returns a shared pointer to the current spread order.
See EventFlag "Event Flags" section.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
eventFlags The transactional event flags.
Returns
A shared pointer to the current spread order.
withEventSymbol()
SpreadOrder& dxfcpp::SpreadOrder::withEventSymbol (const std::string & eventSymbol) inline noexcept
Changes event's symbol and returns the current spread order.
Parameters
eventSymbol The symbol of this event.
Returns
The current spread order.
withEventSymbolShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withEventSymbolShared (const std::string & eventSymbol) inline noexcept
Changes event's symbol and returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
eventSymbol The symbol of this event.
Returns
A shared pointer to the current spread order.
withEventTime()
SpreadOrder& dxfcpp::SpreadOrder::withEventTime (std::int64_t eventTime) inline noexcept
Changes event's creation time and returns the current spread order.
Parameters
eventTime the difference, measured in milliseconds, between the event creation time and midnight, January 1, 1970 UTC.
Returns
The current spread order.
References dxfcpp::MarketEvent::setEventTime().
withEventTimeShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withEventTimeShared (std::int64_t eventTime) inline noexcept
Changes event's creation time and returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
eventTime The difference, measured in milliseconds, between the event creation time and midnight, January 1, 1970 UTC.
Returns
A shared pointer to the current spread order.
References dxfcpp::MarketEvent::setEventTime().
withExchangeCode() [1/2]
SpreadOrder& dxfcpp::SpreadOrder::withExchangeCode (char exchangeCode) inline noexcept
Changes exchange code of this spread order.
Returns the current spread order.
Parameters
exchangeCode The exchange code of this spread order.
Returns
The current spread order.
withExchangeCode() [2/2]
SpreadOrder& dxfcpp::SpreadOrder::withExchangeCode (std::int16_t exchangeCode) inline noexcept
Changes exchange code of this spread order.
Returns the current spread order.
Parameters
exchangeCode The exchange code of this spread order.
Returns
The current spread order.
withExchangeCodeShared() [1/2]
SpreadOrder::Ptr dxfcpp::SpreadOrder::withExchangeCodeShared (char exchangeCode) inline noexcept
Changes exchange code of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
exchangeCode The exchange code of this spread order.
Returns
A shared pointer to the current spread order.
withExchangeCodeShared() [2/2]
SpreadOrder::Ptr dxfcpp::SpreadOrder::withExchangeCodeShared (std::int16_t exchangeCode) inline noexcept
Changes exchange code of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
exchangeCode The exchange code of this spread order.
Returns
A shared pointer to the current spread order.
withExecutedSize()
SpreadOrder& dxfcpp::SpreadOrder::withExecutedSize (double executedSize) inline noexcept
Changes executed size of this spread order.
Returns the current spread order.
Parameters
executedSize The executed size of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setExecutedSize().
withExecutedSizeShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withExecutedSizeShared (double executedSize) inline noexcept
Changes executed size of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
executedSize The executed size of this spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setExecutedSize().
withIndex()
SpreadOrder& dxfcpp::SpreadOrder::withIndex (std::int64_t index) inline noexcept
Changes unique per-symbol index of this spread order and returns it.
Note, that this method also changes source, whose id occupies highest bits of index. Use OrderBase::setSource() after invocation of this method to set the desired value of source.
Parameters
index The unique per-symbol index of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setIndex().
withIndexShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withIndexShared (std::int64_t index) inline noexcept
Changes unique per-symbol index of this spread order and returns a shared pointer to it.
Note, that this method also changes source, whose id occupies highest bits of index. Use OrderBase::setSource() after invocation of this method to set the desired value of source.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
index The unique per-symbol index of this order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setIndex().
withOrderId()
SpreadOrder& dxfcpp::SpreadOrder::withOrderId (std::int64_t orderId) inline noexcept
Changes order ID.
Returns the current spread order.
Parameters
orderId The spread order ID.
Returns
The current spread order.
References dxfcpp::OrderBase::setOrderId().
withOrderIdShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withOrderIdShared (std::int64_t orderId) inline noexcept
Changes spread order ID.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
orderId The spread order ID.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setOrderId().
withOrderSide()
SpreadOrder& dxfcpp::SpreadOrder::withOrderSide (const Side & side) inline noexcept
Changes side of this spread order.
Returns the current spread order.
Parameters
side The side of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setOrderSide().
withOrderSideShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withOrderSideShared (const Side & side) inline noexcept
Changes side of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
side The side of this spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setOrderSide().
withPrice()
SpreadOrder& dxfcpp::SpreadOrder::withPrice (double price) inline noexcept
Changes price of this spread order.
Returns the current spread order.
Parameters
price The price of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setPrice().
withPriceShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withPriceShared (double price) inline noexcept
Changes price of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
price The price of this spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setPrice().
withScope()
SpreadOrder& dxfcpp::SpreadOrder::withScope (const Scope & scope) inline noexcept
Changes scope of this spread order.
Returns the current spread order.
Parameters
scope The scope of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setScope().
withScopeShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withScopeShared (const Scope & scope) inline noexcept
Changes scope of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
scope The scope of this spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setScope().
withSequence()
SpreadOrder& dxfcpp::SpreadOrder::withSequence (std::int32_t sequence) inline noexcept
Changes sequence number of this spread order.
Returns the current spread order.
Parameters
sequence The sequence.
Returns
The current spread order.
See also
OrderBase::getSequence()
References dxfcpp::OrderBase::setSequence().
withSequenceShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withSequenceShared (std::int32_t sequence) inline noexcept
Changes sequence number of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
sequence The sequence.
Returns
A shared pointer to the current spread order.
See also
OrderBase::getSequence()
References dxfcpp::OrderBase::setSequence().
withSize()
SpreadOrder& dxfcpp::SpreadOrder::withSize (double size) inline noexcept
Changes size of this spread order.
Returns the current spread order.
Parameters
size The size of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setSize().
withSizeShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withSizeShared (double size) inline noexcept
Changes size of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
size The size of this spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setSize().
withSource()
SpreadOrder& dxfcpp::SpreadOrder::withSource (const OrderSource & source) inline noexcept
Changes event's source and returns the current spread order.
This method changes highest bits of the index of this event.
Parameters
source The source of this event.
Returns
The current spread order.
References dxfcpp::OrderBase::setSource().
withSourceShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withSourceShared (const OrderSource & source) inline noexcept
Changes event's source and returns a shared pointer to the current spread order.
This method changes highest bits of the index of this event.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
source The source of this event.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setSource().
withSpreadSymbol()
SpreadOrder& dxfcpp::SpreadOrder::withSpreadSymbol (std::string spreadSymbol) inline noexcept
Changes spread symbol of this event.
Returns the current spread order.
Parameters
spreadSymbol spread symbol of this event.
Returns
The current spread order.
References setSpreadSymbol().
withSpreadSymbolShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withSpreadSymbolShared (std::string spreadSymbol) inline noexcept
Changes spread symbol of this event.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
spreadSymbol spread symbol of this event.
Returns
A shared pointer to the current spread order.
References setSpreadSymbol().
withTime()
SpreadOrder& dxfcpp::SpreadOrder::withTime (std::int64_t time) inline noexcept
Changes time of this spread order and returns it.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
Parameters
time The time of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setTime().
withTimeNanoPart()
SpreadOrder& dxfcpp::SpreadOrder::withTimeNanoPart (std::int32_t timeNanoPart) inline noexcept
Changes microseconds and nanoseconds time part of this spread order.
Returns the current spread order.
Parameters
timeNanoPart The microseconds and nanoseconds time part of this spread order.
Returns
The current spread order.
References dxfcpp::OrderBase::setTimeNanoPart().
withTimeNanoPartShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withTimeNanoPartShared (std::int32_t timeNanoPart) inline noexcept
Changes microseconds and nanoseconds time part of this spread order.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
timeNanoPart The microseconds and nanoseconds time part of this spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setTimeNanoPart().
withTimeNanos()
SpreadOrder& dxfcpp::SpreadOrder::withTimeNanos (std::int64_t timeNanos) inline noexcept
Changes time of this spread order and returns it.
Time is measured in nanoseconds between the current time and midnight, January 1, 1970 UTC.
Parameters
timeNanos The time of this order in nanoseconds.
Returns
The current spread order.
References dxfcpp::OrderBase::setTimeNanos().
withTimeNanosShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withTimeNanosShared (std::int64_t timeNanos) inline noexcept
Changes time of this spread order.
Returns a shared pointer to the current spread order. Time is measured in nanoseconds between the current time and midnight, January 1, 1970 UTC.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
timeNanos The time of this spread order in nanoseconds.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setTimeNanos().
withTimeShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withTimeShared (std::int64_t time) inline noexcept
Changes time of this spread order and returns a shared pointer to it.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
time The time of this spread order.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setTime().
withTradeId()
SpreadOrder& dxfcpp::SpreadOrder::withTradeId (std::int64_t tradeId) inline noexcept
Changes trade ID.
Returns the current spread order.
Parameters
tradeId The trade ID.
Returns
The current spread order.
References dxfcpp::OrderBase::setTradeId().
withTradePrice()
SpreadOrder& dxfcpp::SpreadOrder::withTradePrice (double tradePrice) inline noexcept
Changes trade price.
Returns the current spread order.
Parameters
tradePrice The trade price.
Returns
The current spread order.
References dxfcpp::OrderBase::setTradePrice().
withTradePriceShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withTradePriceShared (double tradePrice) inline noexcept
Changes trade price.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
tradePrice The trade price.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setTradePrice().
withTradeShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withTradeShared (std::int64_t tradeId) inline noexcept
Changes trade ID.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
tradeId The trade ID.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setTradeId().
withTradeSize()
SpreadOrder& dxfcpp::SpreadOrder::withTradeSize (double tradeSize) inline noexcept
Changes trade size.
Returns the current spread order.
Parameters
tradeSize The trade size.
Returns
The current spread order.
References dxfcpp::OrderBase::setTradeSize().
withTradeSizeShared()
SpreadOrder::Ptr dxfcpp::SpreadOrder::withTradeSizeShared (double tradeSize) inline noexcept
Changes trade size.
Returns a shared pointer to the current spread order.
Warning
Please do not use this method unless the object was created with std::shared_ptr<SpreadOrder>(new SpreadOrder(...)) or std::make_shared<SpreadOrder>(...)
Parameters
tradeSize The trade size.
Returns
A shared pointer to the current spread order.
References dxfcpp::OrderBase::setTradeSize().