dxFeed Graal CXX API: IndexedEventSource Class Reference
IndexedEventSource Class Reference
Source identifier for IndexedEvent.
#include <IndexedEventSource.hpp>
Public Member Functions
virtual void * toGraal () const
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
IndexedEventSource (std::int32_t id, std::string name) noexcept
Creates the new IndexedEvent's source by id and name.
std::int32_t id () const noexcept
Returns the source identifier.
const std::string & name () const noexcept
Returns the string representation of the object.
std::string toString () const noexcept
Returns the string representation of the object.
Static Public Member Functions
static void freeGraal (void *graalNative)
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
static IndexedEventSource fromGraal (void *graalNative)
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
Static Public Attributes
static const IndexedEventSource DEFAULT {0, "DEFAULT"}
The default source with zero identifier for all events that do not support multiple sources.
Detailed Description
Source identifier for IndexedEvent.
See IndexedEvent::getSource().
Constructor & Destructor Documentation
IndexedEventSource()
IndexedEventSource::IndexedEventSource (std::int32_t id, std::string name) inline noexcept
Creates the new IndexedEvent's source by id and name.
Parameters
id The source id
name The source name
Member Function Documentation
freeGraal()
void IndexedEventSource::freeGraal (void * graalNative) static
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Referenced by IndexedEventSubscriptionSymbol::freeGraal().
fromGraal()
IndexedEventSource IndexedEventSource::fromGraal (void * graalNative) static
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Returns
The object of current type.
Exceptions
std::invalid_argument
Referenced by IndexedEventSubscriptionSymbol::fromGraal().
id()
std::int32_t IndexedEventSource::id () const inline noexcept
Returns the source identifier.
Source identifier is non-negative.
Returns
The source identifier.
Referenced by OrderSource::isSpecialSourceId(), and OrderBase::setSource().
name()
const std::string & IndexedEventSource::name () const inline noexcept
Returns the string representation of the object.
Returns
The string representation of the object.
toGraal()
void * IndexedEventSource::toGraal () const virtual
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
toString()
std::string IndexedEventSource::toString () const inline noexcept
Returns the string representation of the object.
Returns
The string representation of the object.