dxFeed Graal CXX API: dxfcpp::InstrumentProfile Class Reference
dxfcpp::InstrumentProfile Class Reference final
Represents basic profile information about market instrument.
#include <InstrumentProfile.hpp>
Public Types
using Ptr = std::shared_ptr< InstrumentProfile >
The alias to a type of shared pointer to the InstrumentProfile object.
using Unique = std::unique_ptr< InstrumentProfile >
The alias to a type of unique pointer to the InstrumentProfile object.
Public Types inherited from dxfcpp::SharedEntity
using Ptr = std::shared_ptr< SharedEntity >
The alias to a type of shared pointer to the SharedEntity object.
Public Member Functions
void * toGraal () const noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
InstrumentProfile () noexcept=default
Creates new instrument profile with default values.
const std::string & getType () const &noexcept
Returns type of instrument.
void setType (const std::string &type) noexcept
Changes type of instrument.
InstrumentProfile & withType (const std::string &type) noexcept
Changes type of instrument and returns the current instrument profile.
InstrumentProfile::Ptr withTypeShared (const std::string &type) noexcept
Changes type of instrument and returns a shared pointer to the current instrument profile.
const std::string & getSymbol () const &noexcept
Returns identifier of instrument, preferable an international one in Latin alphabet.
void setSymbol (const std::string &symbol) noexcept
Changes identifier of instrument, preferable an international one in Latin alphabet.
InstrumentProfile & withSymbol (const std::string &symbol) noexcept
Changes identifier of instrument, preferable an international one in Latin alphabet.
InstrumentProfile::Ptr withSymbolShared (const std::string &symbol) noexcept
Changes identifier of instrument, preferable an international one in Latin alphabet.
const std::string & getDescription () const &noexcept
Returns the description of instrument, preferable an international one in Latin alphabet.
void setDescription (const std::string &description) noexcept
Changes description of instrument, preferable an international one in Latin alphabet.
InstrumentProfile & withDescription (const std::string &description) noexcept
Changes description of instrument, preferable an international one in Latin alphabet.
InstrumentProfile::Ptr withDescriptionShared (const std::string &description) noexcept
Changes description of instrument, preferable an international one in Latin alphabet.
const std::string & getLocalSymbol () const &noexcept
Returns identifier of instrument in national language.
void setLocalSymbol (const std::string &localSymbol) noexcept
Changes identifier of instrument in national language.
InstrumentProfile & withLocalSymbol (const std::string &localSymbol) noexcept
Changes identifier of instrument in national language.
InstrumentProfile::Ptr withLocalSymbolShared (const std::string &localSymbol) noexcept
Changes identifier of instrument in national language.
const std::string & getLocalDescription () const &noexcept
Returns description of instrument in national language.
void setLocalDescription (const std::string &localDescription) noexcept
Changes description of instrument in national language.
InstrumentProfile & withLocalDescription (const std::string &localDescription) noexcept
Changes description of instrument in national language.
InstrumentProfile::Ptr withLocalDescriptionShared (const std::string &localDescription) noexcept
Changes description of instrument in national language.
const std::string & getCountry () const &noexcept
Returns country of origin (incorporation) of corresponding company or parent entity.
void setCountry (const std::string &country) noexcept
Changes country of origin (incorporation) of corresponding company or parent entity.
InstrumentProfile & withCountry (const std::string &country) noexcept
Changes country of origin (incorporation) of corresponding company or parent entity.
InstrumentProfile::Ptr withCountryShared (const std::string &country) noexcept
Changes country of origin (incorporation) of corresponding company or parent entity.
const std::string & getOPOL () const &noexcept
Returns official Place Of Listing, the organization that have listed this instrument.
void setOPOL (const std::string &opol) noexcept
Changes official Place Of Listing, the organization that have listed this instrument.
InstrumentProfile & withOPOL (const std::string &opol) noexcept
Changes official Place Of Listing, the organization that have listed this instrument.
InstrumentProfile::Ptr withOPOLShared (const std::string &opol) noexcept
Changes official Place Of Listing, the organization that have listed this instrument.
const std::string & getExchangeData () const &noexcept
Returns exchange-specific data required to properly identify instrument when communicating with exchange.
void setExchangeData (const std::string &exchangeData) noexcept
Changes exchange-specific data required to properly identify instrument when communicating with exchange.
InstrumentProfile & withExchangeData (const std::string &exchangeData) noexcept
Changes exchange-specific data required to properly identify instrument when communicating with exchange.
InstrumentProfile::Ptr withExchangeDataShared (const std::string &exchangeData) noexcept
Changes exchange-specific data required to properly identify instrument when communicating with exchange.
const std::string & getExchanges () const &noexcept
Returns list of exchanges where instrument is quoted or traded.
void setExchanges (const std::string &exchanges) noexcept
Changes list of exchanges where instrument is quoted or traded.
InstrumentProfile & withExchanges (const std::string &exchanges) noexcept
Changes list of exchanges where instrument is quoted or traded.
InstrumentProfile::Ptr withExchangesShared (const std::string &exchanges) noexcept
Changes list of exchanges where instrument is quoted or traded.
const std::string & getCurrency () const &noexcept
Returns currency of quotation, pricing and trading.
void setCurrency (const std::string &currency) noexcept
Changes currency of quotation, pricing and trading.
InstrumentProfile & withCurrency (const std::string &currency) noexcept
Changes currency of quotation, pricing and trading.
InstrumentProfile::Ptr withCurrencyShared (const std::string &currency) noexcept
Changes currency of quotation, pricing and trading.
const std::string & getBaseCurrency () const &noexcept
Returns base currency of currency pair (FOREX instruments).
void setBaseCurrency (const std::string &baseCurrency) noexcept
Changes base currency of currency pair (FOREX instruments).
InstrumentProfile & withBaseCurrency (const std::string &baseCurrency) noexcept
Changes base currency of currency pair (FOREX instruments).
InstrumentProfile::Ptr withBaseCurrencyShared (const std::string &baseCurrency) noexcept
Changes base currency of currency pair (FOREX instruments).
const std::string & getCFI () const &noexcept
Returns Classification of Financial Instruments code.
void setCFI (const std::string &cfi) noexcept
Changes Classification of Financial Instruments code.
InstrumentProfile & withCFI (const std::string &cfi) noexcept
Changes Classification of Financial Instruments code.
InstrumentProfile::Ptr withCFIShared (const std::string &cfi) noexcept
Changes Classification of Financial Instruments code.
const std::string & getISIN () const &noexcept
Returns International Securities Identifying Number.
void setISIN (const std::string &isin) noexcept
Changes International Securities Identifying Number.
InstrumentProfile & withISIN (const std::string &isin) noexcept
Changes International Securities Identifying Number.
InstrumentProfile::Ptr withISINShared (const std::string &isin) noexcept
Changes International Securities Identifying Number.
const std::string & getSEDOL () const &noexcept
Returns Stock Exchange Daily Official List.
void setSEDOL (const std::string &sedol) noexcept
Changes Stock Exchange Daily Official List.
InstrumentProfile & withSEDOL (const std::string &sedol) noexcept
Changes Stock Exchange Daily Official List.
InstrumentProfile::Ptr withSEDOLShared (const std::string &sedol) noexcept
Changes Stock Exchange Daily Official List.
const std::string & getCUSIP () const &noexcept
Returns Committee on Uniform Security Identification Procedures code.
void setCUSIP (const std::string &cusip) noexcept
Changes Committee on Uniform Security Identification Procedures code.
InstrumentProfile & withCUSIP (const std::string &cusip) noexcept
Changes Committee on Uniform Security Identification Procedures code.
InstrumentProfile::Ptr withCUSIPShared (const std::string &cusip) noexcept
Changes Committee on Uniform Security Identification Procedures code.
std::int32_t getICB () const noexcept
Returns Industry Classification Benchmark.
void setICB (std::int32_t icb) noexcept
Changes Industry Classification Benchmark.
InstrumentProfile & withICB (std::int32_t icb) noexcept
Changes Industry Classification Benchmark.
InstrumentProfile::Ptr withICBShared (std::int32_t icb) noexcept
Changes Industry Classification Benchmark.
std::int32_t getSIC () const noexcept
Returns Standard Industrial Classification.
void setSIC (std::int32_t sic) noexcept
Changes Standard Industrial Classification.
InstrumentProfile & withSIC (std::int32_t sic) noexcept
Changes Standard Industrial Classification.
InstrumentProfile::Ptr withSICShared (std::int32_t sic) noexcept
Changes Standard Industrial Classification.
double getMultiplier () const noexcept
Returns market value multiplier.
void setMultiplier (double multiplier) noexcept
Changes market value multiplier.
InstrumentProfile & withMultiplier (double multiplier) noexcept
Changes market value multiplier.
InstrumentProfile::Ptr withMultiplierShared (double multiplier) noexcept
Changes market value multiplier.
const std::string & getProduct () const &noexcept
Returns product for futures and options on futures (underlying asset name).
void setProduct (const std::string &product) noexcept
Changes product for futures and options on futures (underlying asset name).
InstrumentProfile & withProduct (const std::string &product) noexcept
Changes product for futures and options on futures (underlying asset name).
InstrumentProfile::Ptr withProductShared (const std::string &product) noexcept
Changes product for futures and options on futures (underlying asset name).
const std::string & getUnderlying () const &noexcept
Returns primary underlying symbol for options.
void setUnderlying (const std::string &underlying) noexcept
Changes primary underlying symbol for options.
InstrumentProfile & withUnderlying (const std::string &underlying) noexcept
Changes primary underlying symbol for options.
InstrumentProfile::Ptr withUnderlyingShared (const std::string &underlying) noexcept
Changes primary underlying symbol for options.
double getSPC () const noexcept
Returns shares per contract for options.
void setSPC (double spc) noexcept
Changes shares per contract for options.
InstrumentProfile & withSPC (double spc) noexcept
Changes shares per contract for options.
InstrumentProfile::Ptr withSPCShared (double spc) noexcept
Changes shares per contract for options.
const std::string & getAdditionalUnderlyings () const &noexcept
Returns additional underlyings for options, including additional cash.
void setAdditionalUnderlyings (const std::string &additionalUnderlyings) noexcept
Changes additional underlyings for options, including additional cash.
InstrumentProfile & withAdditionalUnderlyings (const std::string &additionalUnderlyings) noexcept
Changes additional underlyings for options, including additional cash.
InstrumentProfile::Ptr withAdditionalUnderlyingsShared (const std::string &additionalUnderlyings) noexcept
Changes additional underlyings for options, including additional cash.
const std::string & getMMY () const &noexcept
Returns maturity month-year as provided for corresponding FIX tag (200).
void setMMY (const std::string &mmy) noexcept
Changes maturity month-year as provided for corresponding FIX tag (200).
InstrumentProfile & withMMY (const std::string &mmy) noexcept
Changes maturity month-year as provided for corresponding FIX tag (200).
InstrumentProfile::Ptr withMMYShared (const std::string &mmy) noexcept
Changes maturity month-year as provided for corresponding FIX tag (200).
std::int32_t getExpiration () const noexcept
Returns day id of expiration.
void setExpiration (std::int32_t expiration) noexcept
Changes day id of expiration.
InstrumentProfile & withExpiration (std::int32_t expiration) noexcept
Changes day id of expiration.
InstrumentProfile::Ptr withExpirationShared (std::int32_t expiration) noexcept
Changes day id of expiration.
std::int32_t getLastTrade () const noexcept
Returns day id of last trading day.
void setLastTrade (std::int32_t lastTrade) noexcept
Changes day id of last trading day.
InstrumentProfile & withLastTrade (std::int32_t lastTrade) noexcept
Changes day id of last trading day.
InstrumentProfile::Ptr withLastTradeShared (std::int32_t lastTrade) noexcept
Changes day id of last trading day.
double getStrike () const noexcept
Returns strike price for options.
void setStrike (double strike) noexcept
Changes strike price for options.
InstrumentProfile & withStrike (double strike) noexcept
Changes strike price for options.
InstrumentProfile::Ptr withStrikeShared (double strike) noexcept
Changes strike price for options.
const std::string & getOptionType () const &noexcept
Returns type of option.
void setOptionType (const std::string &optionType) noexcept
Changes type of option.
InstrumentProfile & withOptionType (const std::string &optionType) noexcept
Changes type of option.
InstrumentProfile::Ptr withOptionTypeShared (const std::string &optionType) noexcept
Changes type of option.
const std::string & getExpirationStyle () const &noexcept
Returns expiration cycle style, such as "Weeklys", "Quarterlys".
void setExpirationStyle (const std::string &expirationStyle) noexcept
Changes the expiration cycle style, such as "Weeklys", "Quarterlys".
InstrumentProfile & withExpirationStyle (const std::string &expirationStyle) noexcept
Changes the expiration cycle style, such as "Weeklys", "Quarterlys".
InstrumentProfile::Ptr withExpirationStyleShared (const std::string &expirationStyle) noexcept
Changes the expiration cycle style, such as "Weeklys", "Quarterlys".
const std::string & getSettlementStyle () const &noexcept
Returns settlement price determination style, such as "Open", "Close".
void setSettlementStyle (const std::string &settlementStyle) noexcept
Changes settlement price determination style, such as "Open", "Close".
InstrumentProfile & withSettlementStyle (const std::string &settlementStyle) noexcept
Changes settlement price determination style, such as "Open", "Close".
InstrumentProfile::Ptr withSettlementStyleShared (const std::string &settlementStyle) noexcept
Changes settlement price determination style, such as "Open", "Close".
const std::string & getPriceIncrements () const &noexcept
Returns minimum allowed price increments with corresponding price ranges.
void setPriceIncrements (const std::string &priceIncrements) noexcept
Changes minimum allowed price increments with corresponding price ranges.
InstrumentProfile & withPriceIncrements (const std::string &priceIncrements) noexcept
Changes minimum allowed price increments with corresponding price ranges.
InstrumentProfile::Ptr withPriceIncrementsShared (const std::string &priceIncrements) noexcept
Changes minimum allowed price increments with corresponding price ranges.
const std::string & getTradingHours () const &noexcept
Returns trading hours specification.
void setTradingHours (const std::string &tradingHours) noexcept
Changes trading hours specification.
InstrumentProfile & withTradingHours (const std::string &tradingHours) noexcept
Changes trading hours specification.
InstrumentProfile::Ptr withTradingHoursShared (const std::string &tradingHours) noexcept
Changes trading hours specification.
Public Member Functions inherited from dxfcpp::SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
virtual std::string toString () const noexcept
Returns a string representation of the current object.
Public Member Functions inherited from dxfcpp::Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Static Public Member Functions
static void freeGraal (void *graalNative) noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Detailed Description
Represents basic profile information about market instrument.
Please see Instrument Profile Format documentation for complete description.
Member Function Documentation
freeGraal()
void dxfcpp::InstrumentProfile::freeGraal (void * graalNative) static noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Referenced by dxfcpp::InstrumentProfileCollector::updateInstrumentProfile().
getAdditionalUnderlyings()
const std::string& dxfcpp::InstrumentProfile::getAdditionalUnderlyings () const & inline noexcept
Returns additional underlyings for options, including additional cash.
It shall use following format:
    <VALUE> ::= <empty> | <LIST>
    <LIST> ::= <AU> | <AU> <semicolon> <space> <LIST>
    <AU> ::= <UNDERLYING> <space> <SPC>
the list shall be sorted by <UNDERLYING>.
Example: "SE 50", "FIS 53; US$ 45.46".
Returns
The additional underlyings for options, including additional cash.
getBaseCurrency()
const std::string& dxfcpp::InstrumentProfile::getBaseCurrency () const & inline noexcept
Returns base currency of currency pair (FOREX instruments).
It shall use three-letter currency code similarly to currency.
Returns
The base currency of currency pair (FOREX instruments).
getCFI()
const std::string& dxfcpp::InstrumentProfile::getCFI () const & inline noexcept
Returns Classification of Financial Instruments code.
It is a mandatory field for OPTION instruments as it is the only way to distinguish Call/Put type, American/European exercise, Cash/Physical delivery. It shall use six-letter CFI code from ISO 10962 standard. It is allowed to use 'X' extensively and to omit trailing letters (assumed to be 'X'). See ISO 10962 on Wikipedia. Example: "ESNTPB", "ESXXXX", "ES" , "OPASPS".
Returns
CFI code.
getCountry()
const std::string& dxfcpp::InstrumentProfile::getCountry () const & inline noexcept
Returns country of origin (incorporation) of corresponding company or parent entity.
It shall use two-letter country code from ISO 3166-1 standard. See ISO 3166-1 on Wikipedia. Example: "US", "RU".
Returns
The country of origin (incorporation) of corresponding company or parent entity.
getCurrency()
const std::string& dxfcpp::InstrumentProfile::getCurrency () const & inline noexcept
Returns currency of quotation, pricing and trading.
It shall use three-letter currency code from ISO 4217 standard. See ISO 4217 on Wikipedia. Example: "USD", "RUB".
Returns
Currency of quotation, pricing and trading.
getCUSIP()
const std::string& dxfcpp::InstrumentProfile::getCUSIP () const & inline noexcept
Returns Committee on Uniform Security Identification Procedures code.
It shall use nine-letter code assigned by CUSIP Services Bureau. See CUSIP on Wikipedia. Example: "38259P508".
Returns
CUSIP code.
getDescription()
const std::string& dxfcpp::InstrumentProfile::getDescription () const & inline noexcept
Returns the description of instrument, preferable an international one in Latin alphabet.
Example: "Google Inc.", "Mini Gold Futures,Jun-2009,ETH".
Returns
The description of instrument.
getExchangeData()
const std::string& dxfcpp::InstrumentProfile::getExchangeData () const & inline noexcept
Returns exchange-specific data required to properly identify instrument when communicating with exchange.
It uses exchange-specific format.
Returns
The exchange-specific data required to properly identify instrument when communicating with exchange.
getExchanges()
const std::string& dxfcpp::InstrumentProfile::getExchanges () const & inline noexcept
Returns list of exchanges where instrument is quoted or traded.
Its shall use the following format:
<VALUE> ::= <empty> | <LIST>
<LIST> ::= <MIC> | <MIC> <semicolon>
<LIST> the list shall be sorted by MIC.
Example: "ARCX;CBSX ;XNAS;XNYS".
Returns
The list of exchanges where instrument is quoted or traded.
getExpiration()
std::int32_t dxfcpp::InstrumentProfile::getExpiration () const inline noexcept
Returns day id of expiration.
Example: day_util::#getDayIdByYearMonthDay() "dxfcpp::day_util::getDayIdByYearMonthDay"(20090117).
Returns
The day id of expiration.
getExpirationStyle()
const std::string& dxfcpp::InstrumentProfile::getExpirationStyle () const & inline noexcept
Returns expiration cycle style, such as "Weeklys", "Quarterlys".
Returns
The expiration cycle style.
getICB()
std::int32_t dxfcpp::InstrumentProfile::getICB () const inline noexcept
Returns Industry Classification Benchmark.
It shall use four-digit number from ICB catalog. See ICB on Wikipedia or ICB homepage. Example: "9535".
Returns
Industry Classification Benchmark.
getISIN()
const std::string& dxfcpp::InstrumentProfile::getISIN () const & inline noexcept
Returns International Securities Identifying Number.
It shall use twelve-letter code from ISO 6166 standard. See ISO 6166 on Wikipedia or ISIN on Wikipedia. Example: "DE0007100000", "US38259P5089".
Returns
International Securities Identifying Number.
getLastTrade()
std::int32_t dxfcpp::InstrumentProfile::getLastTrade () const inline noexcept
Returns day id of last trading day.
Example: day_util::#getDayIdByYearMonthDay() "dxfcpp::day_util::getDayIdByYearMonthDay"(20090116).
Returns
The day id of last trading day.
getLocalDescription()
const std::string& dxfcpp::InstrumentProfile::getLocalDescription () const & inline noexcept
Returns description of instrument in national language.
It shall be empty if same as description.
Returns
The description of instrument in national language.
getLocalSymbol()
const std::string& dxfcpp::InstrumentProfile::getLocalSymbol () const & inline noexcept
Returns identifier of instrument in national language.
It shall be empty if same as symbol.
Returns
The identifier of instrument in national language.
getMMY()
const std::string& dxfcpp::InstrumentProfile::getMMY () const & inline noexcept
Returns maturity month-year as provided for corresponding FIX tag (200).
It can use several different formats depending on data source:
YYYYMM if only year and month are specified
YYYYMMDD if full date is specified
YYYYMMwN if week number (within a month) is specified
Returns
The maturity month-year as provided for corresponding FIX tag (200).
getMultiplier()
double dxfcpp::InstrumentProfile::getMultiplier () const inline noexcept
Returns market value multiplier.
Example: 100, 33.2.
Returns
The market value multiplier.
getOPOL()
const std::string& dxfcpp::InstrumentProfile::getOPOL () const & inline noexcept
Returns official Place Of Listing, the organization that have listed this instrument.
Instruments with multiple listings shall use separate profiles for each listing. It shall use Market Identifier Code (MIC) from ISO 10383 standard. See ISO 10383 on Wikipedia or MIC homepage. Example: "XNAS", "RTSX"
Returns
The official Place Of Listing, the organization that have listed this instrument.
getOptionType()
const std::string& dxfcpp::InstrumentProfile::getOptionType () const & inline noexcept
Returns type of option.
It shall use one of following values:
STAN = Standard Options
LEAP = Long-term Equity AnticiPation Securities
SDO = Special Dated Options
BINY = Binary Options
FLEX = FLexible EXchange Options
VSO = Variable Start Options
RNGE = Range
Returns
The type of option.
getPriceIncrements()
const std::string& dxfcpp::InstrumentProfile::getPriceIncrements () const & inline noexcept
Returns minimum allowed price increments with corresponding price ranges.
It shall use following format:
    <VALUE> ::= <empty> | <LIST>
    <LIST> ::= <INCREMENT> | <RANGE> <semicolon> <space> <LIST>
    <RANGE> ::= <INCREMENT> <space> <UPPER_LIMIT>
the list shall be sorted by <UPPER_LIMIT>.
Example: "0.25", "0.01 3; 0.05".
Returns
The minimum allowed price increments with corresponding price ranges.
getProduct()
const std::string& dxfcpp::InstrumentProfile::getProduct () const & inline noexcept
Returns product for futures and options on futures (underlying asset name).
Example: "/YG".
Returns
The product for futures and options on futures (underlying asset name).
getSEDOL()
const std::string& dxfcpp::InstrumentProfile::getSEDOL () const & inline noexcept
Returns Stock Exchange Daily Official List.
It shall use seven-letter code assigned by London Stock Exchange. See SEDOL on Wikipedia or SEDOL on LSE. Example: "2310967", "5766857".
Returns
Stock Exchange Daily Official List.
getSettlementStyle()
const std::string& dxfcpp::InstrumentProfile::getSettlementStyle () const & inline noexcept
Returns settlement price determination style, such as "Open", "Close".
Returns
The settlement price determination style.
getSIC()
std::int32_t dxfcpp::InstrumentProfile::getSIC () const inline noexcept
Returns Standard Industrial Classification.
It shall use four-digit number from SIC catalog. See SIC on Wikipedia or SIC structure. Example: "7371".
Returns
Standard Industrial Classification.
getSPC()
double dxfcpp::InstrumentProfile::getSPC () const inline noexcept
Returns shares per contract for options.
Example: 1, 100.
Returns
shares per contract for options.
getStrike()
double dxfcpp::InstrumentProfile::getStrike () const inline noexcept
Returns strike price for options.
Example: 80, 22.5.
Returns
The strike price for options.
getSymbol()
const std::string& dxfcpp::InstrumentProfile::getSymbol () const & inline noexcept
Returns identifier of instrument, preferable an international one in Latin alphabet.
It is a mandatory field. It may not be empty. Example: "GOOG", "/YGM9", ".ZYEAD".
Returns
The identifier of instrument.
getTradingHours()
const std::string& dxfcpp::InstrumentProfile::getTradingHours () const & inline noexcept
Returns trading hours specification.
See Schedule::getInstance().
Returns
The trading hours specification.
getType()
const std::string& dxfcpp::InstrumentProfile::getType () const & inline noexcept
Returns type of instrument.
It takes precedence in conflict cases with other fields. It is a mandatory field. It may not be empty. Example: "STOCK", "FUTURE", "OPTION".
Returns
type of instrument.
getUnderlying()
const std::string& dxfcpp::InstrumentProfile::getUnderlying () const & inline noexcept
Returns primary underlying symbol for options.
Example: "C", "/YGM9"
Returns
The primary underlying symbol for options.
setAdditionalUnderlyings()
void dxfcpp::InstrumentProfile::setAdditionalUnderlyings (const std::string & additionalUnderlyings) inline noexcept
Changes additional underlyings for options, including additional cash.
It shall use following format:
    <VALUE> ::= <empty> | <LIST>
    <LIST> ::= <AU> | <AU> <semicolon> <space> <LIST>
    <AU> ::= <UNDERLYING> <space> <SPC>
the list shall be sorted by <UNDERLYING>.
Example: "SE 50", "FIS 53; US$ 45.46".
Parameters
additionalUnderlyings The additional underlyings for options, including additional cash.
Referenced by withAdditionalUnderlyings(), and withAdditionalUnderlyingsShared().
setBaseCurrency()
void dxfcpp::InstrumentProfile::setBaseCurrency (const std::string & baseCurrency) inline noexcept
Changes base currency of currency pair (FOREX instruments).
It shall use three-letter currency code similarly to currency.
Parameters
baseCurrency The base currency of currency pair (FOREX instruments).
Referenced by withBaseCurrency(), and withBaseCurrencyShared().
setCFI()
void dxfcpp::InstrumentProfile::setCFI (const std::string & cfi) inline noexcept
Changes Classification of Financial Instruments code.
It is a mandatory field for OPTION instruments as it is the only way to distinguish Call/Put type, American/European exercise, Cash/Physical delivery. It shall use six-letter CFI code from ISO 10962 standard. It is allowed to use 'X' extensively and to omit trailing letters (assumed to be 'X'). See ISO 10962 on Wikipedia. Example: "ESNTPB", "ESXXXX", "ES" , "OPASPS".
Parameters
cfi CFI code.
Referenced by withCFI(), and withCFIShared().
setCountry()
void dxfcpp::InstrumentProfile::setCountry (const std::string & country) inline noexcept
Changes country of origin (incorporation) of corresponding company or parent entity.
It shall use two-letter country code from ISO 3166-1 standard. See ISO 3166-1 on Wikipedia. Example: "US", "RU".
Parameters
country The country of origin (incorporation) of corresponding company or parent entity.
Referenced by withCountry(), and withCountryShared().
setCurrency()
void dxfcpp::InstrumentProfile::setCurrency (const std::string & currency) inline noexcept
Changes currency of quotation, pricing and trading.
It shall use three-letter currency code from ISO 4217 standard. See ISO 4217 on Wikipedia. Example: "USD", "RUB".
Parameters
currency Currency of quotation, pricing and trading.
Referenced by withCurrency(), and withCurrencyShared().
setCUSIP()
void dxfcpp::InstrumentProfile::setCUSIP (const std::string & cusip) inline noexcept
Changes Committee on Uniform Security Identification Procedures code.
It shall use nine-letter code assigned by CUSIP Services Bureau. See CUSIP on Wikipedia. Example: "38259P508".
Parameters
cusip CUSIP code.
Referenced by withCUSIP(), and withCUSIPShared().
setDescription()
void dxfcpp::InstrumentProfile::setDescription (const std::string & description) inline noexcept
Changes description of instrument, preferable an international one in Latin alphabet.
Example: "Google Inc.", "Mini Gold Futures,Jun-2009,ETH".
Parameters
description The description of instrument.
Referenced by withDescription(), and withDescriptionShared().
setExchangeData()
void dxfcpp::InstrumentProfile::setExchangeData (const std::string & exchangeData) inline noexcept
Changes exchange-specific data required to properly identify instrument when communicating with exchange.
It uses exchange-specific format.
Parameters
exchangeData The exchange-specific data required to properly identify instrument when communicating with exchange.
Referenced by withExchangeData(), and withExchangeDataShared().
setExchanges()
void dxfcpp::InstrumentProfile::setExchanges (const std::string & exchanges) inline noexcept
Changes list of exchanges where instrument is quoted or traded.
It shall use the following format:
<VALUE> ::= <empty> | <LIST>
<LIST> ::= <MIC> | <MIC> <semicolon>
<LIST> the list shall be sorted by MIC.
Example: "ARCX;CBSX ;XNAS;XNYS".
Parameters
exchanges The list of exchanges where instrument is quoted or traded.
Referenced by withExchanges(), and withExchangesShared().
setExpiration()
void dxfcpp::InstrumentProfile::setExpiration (std::int32_t expiration) inline noexcept
Changes day id of expiration.
Example: day_util::#getDayIdByYearMonthDay() "dxfcpp::day_util::getDayIdByYearMonthDay"(20090117).
Parameters
expiration The day id of expiration.
Referenced by withExpiration(), and withExpirationShared().
setExpirationStyle()
void dxfcpp::InstrumentProfile::setExpirationStyle (const std::string & expirationStyle) inline noexcept
Changes the expiration cycle style, such as "Weeklys", "Quarterlys".
Parameters
expirationStyle The expiration cycle style.
Referenced by withExpirationStyle(), and withExpirationStyleShared().
setICB()
void dxfcpp::InstrumentProfile::setICB (std::int32_t icb) inline noexcept
Changes Industry Classification Benchmark.
It shall use four-digit number from ICB catalog. See ICB on Wikipedia or ICB homepage. Example: "9535".
Parameters
icb Industry Classification Benchmark.
Referenced by withICB(), and withICBShared().
setISIN()
void dxfcpp::InstrumentProfile::setISIN (const std::string & isin) inline noexcept
Changes International Securities Identifying Number.
It shall use twelve-letter code from ISO 6166 standard. See ISO 6166 on Wikipedia or ISIN on Wikipedia. Example: "DE0007100000", "US38259P5089".
Parameters
isin International Securities Identifying Number.
Referenced by withISIN(), and withISINShared().
setLastTrade()
void dxfcpp::InstrumentProfile::setLastTrade (std::int32_t lastTrade) inline noexcept
Changes day id of last trading day.
Example: day_util::#getDayIdByYearMonthDay() "dxfcpp::day_util::getDayIdByYearMonthDay"(20090116).
Parameters
lastTrade The day id of last trading day.
Referenced by withLastTrade(), and withLastTradeShared().
setLocalDescription()
void dxfcpp::InstrumentProfile::setLocalDescription (const std::string & localDescription) inline noexcept
Changes description of instrument in national language.
It shall be empty if same as description.
Parameters
localDescription The description of instrument in national language.
Referenced by withLocalDescription(), and withLocalDescriptionShared().
setLocalSymbol()
void dxfcpp::InstrumentProfile::setLocalSymbol (const std::string & localSymbol) inline noexcept
Changes identifier of instrument in national language.
It shall be empty if same as symbol.
Parameters
localSymbol The identifier of instrument in national language.
Referenced by withLocalSymbol(), and withLocalSymbolShared().
setMMY()
void dxfcpp::InstrumentProfile::setMMY (const std::string & mmy) inline noexcept
Changes maturity month-year as provided for corresponding FIX tag (200).
It can use several different formats depending on data source:
YYYYMM if only year and month are specified
YYYYMMDD if full date is specified
YYYYMMwN if week number (within a month) is specified
Parameters
mmy The maturity month-year as provided for corresponding FIX tag (200).
Referenced by withMMY(), and withMMYShared().
setMultiplier()
void dxfcpp::InstrumentProfile::setMultiplier (double multiplier) inline noexcept
Changes market value multiplier.
Example: 100, 33.2.
Parameters
multiplier The market value multiplier.
Referenced by withMultiplier(), and withMultiplierShared().
setOPOL()
void dxfcpp::InstrumentProfile::setOPOL (const std::string & opol) inline noexcept
Changes official Place Of Listing, the organization that have listed this instrument.
Instruments with multiple listings shall use separate profiles for each listing. It shall use Market Identifier Code (MIC) from ISO 10383 standard. See ISO 10383 on Wikipedia or MIC homepage. Example: "XNAS", "RTSX"
Parameters
opol The official Place Of Listing, the organization that have listed this instrument.
Referenced by withOPOL(), and withOPOLShared().
setOptionType()
void dxfcpp::InstrumentProfile::setOptionType (const std::string & optionType) inline noexcept
Changes type of option.
It shall use one of following values:
STAN = Standard Options
LEAP = Long-term Equity AnticiPation Securities
SDO = Special Dated Options
BINY = Binary Options
FLEX = FLexible EXchange Options
VSO = Variable Start Options
RNGE = Range
Parameters
optionType The type of option.
Referenced by withOptionType(), and withOptionTypeShared().
setPriceIncrements()
void dxfcpp::InstrumentProfile::setPriceIncrements (const std::string & priceIncrements) inline noexcept
Changes minimum allowed price increments with corresponding price ranges.
It shall use following format:
    <VALUE> ::= <empty> | <LIST>
    <LIST> ::= <INCREMENT> | <RANGE> <semicolon> <space> <LIST>
    <RANGE> ::= <INCREMENT> <space> <UPPER_LIMIT>
the list shall be sorted by <UPPER_LIMIT>.
Example: "0.25", "0.01 3; 0.05".
Parameters
priceIncrements The minimum allowed price increments with corresponding price ranges.
Referenced by withPriceIncrements(), and withPriceIncrementsShared().
setProduct()
void dxfcpp::InstrumentProfile::setProduct (const std::string & product) inline noexcept
Changes product for futures and options on futures (underlying asset name).
Example: "/YG".
Parameters
product The product for futures and options on futures (underlying asset name).
Referenced by withProduct(), and withProductShared().
setSEDOL()
void dxfcpp::InstrumentProfile::setSEDOL (const std::string & sedol) inline noexcept
Changes Stock Exchange Daily Official List.
It shall use seven-letter code assigned by London Stock Exchange. See SEDOL on Wikipedia or SEDOL on LSE. Example: "2310967", "5766857".
Parameters
sedol Stock Exchange Daily Official List.
Referenced by withSEDOL(), and withSEDOLShared().
setSettlementStyle()
void dxfcpp::InstrumentProfile::setSettlementStyle (const std::string & settlementStyle) inline noexcept
Changes settlement price determination style, such as "Open", "Close".
Parameters
settlementStyle The settlement price determination style.
Referenced by withSettlementStyle(), and withSettlementStyleShared().
setSIC()
void dxfcpp::InstrumentProfile::setSIC (std::int32_t sic) inline noexcept
Changes Standard Industrial Classification.
It shall use four-digit number from SIC catalog. See SIC on Wikipedia or SIC structure. Example: "7371".
Parameters
sic Standard Industrial Classification.
Referenced by withSIC(), and withSICShared().
setSPC()
void dxfcpp::InstrumentProfile::setSPC (double spc) inline noexcept
Changes shares per contract for options.
Example: 1, 100.
Parameters
spc The shares per contract for options.
Referenced by withSPC(), and withSPCShared().
setStrike()
void dxfcpp::InstrumentProfile::setStrike (double strike) inline noexcept
Changes strike price for options.
Example: 80, 22.5.
Parameters
strike The strike price for options.
Referenced by withStrike(), and withStrikeShared().
setSymbol()
void dxfcpp::InstrumentProfile::setSymbol (const std::string & symbol) inline noexcept
Changes identifier of instrument, preferable an international one in Latin alphabet.
It is a mandatory field. It may not be empty. Example: "GOOG", "/YGM9", ".ZYEAD".
Parameters
symbol The identifier of instrument.
Referenced by withSymbol(), and withSymbolShared().
setTradingHours()
void dxfcpp::InstrumentProfile::setTradingHours (const std::string & tradingHours) inline noexcept
Changes trading hours specification.
See Schedule::getInstance().
Parameters
tradingHours The trading hours specification.
Referenced by withTradingHours(), and withTradingHoursShared().
setType()
void dxfcpp::InstrumentProfile::setType (const std::string & type) inline noexcept
Changes type of instrument.
It takes precedence in conflict cases with other fields. It is a mandatory field. It may not be empty. Example: "STOCK", "FUTURE", "OPTION".
Parameters
type The type of instrument.
Referenced by withType(), and withTypeShared().
setUnderlying()
void dxfcpp::InstrumentProfile::setUnderlying (const std::string & underlying) inline noexcept
Changes primary underlying symbol for options.
Example: "C", "/YGM9"
Parameters
underlying The primary underlying symbol for options.
Referenced by withUnderlying(), and withUnderlyingShared().
toGraal()
void * dxfcpp::InstrumentProfile::toGraal () const noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Referenced by dxfcpp::InstrumentProfileCollector::updateInstrumentProfile().
withAdditionalUnderlyings()
InstrumentProfile& dxfcpp::InstrumentProfile::withAdditionalUnderlyings (const std::string & additionalUnderlyings) inline noexcept
Changes additional underlyings for options, including additional cash.
It shall use following format:
    <VALUE> ::= <empty> | <LIST>
    <LIST> ::= <AU> | <AU> <semicolon> <space> <LIST>
    <AU> ::= <UNDERLYING> <space> <SPC>
the list shall be sorted by <UNDERLYING>.
Example: "SE 50", "FIS 53; US$ 45.46".
Parameters
additionalUnderlyings The additional underlyings for options, including additional cash.
Returns
The current instrument profile.
References setAdditionalUnderlyings().
withAdditionalUnderlyingsShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withAdditionalUnderlyingsShared (const std::string & additionalUnderlyings) inline noexcept
Changes additional underlyings for options, including additional cash.
It shall use following format:
    <VALUE> ::= <empty> | <LIST>
    <LIST> ::= <AU> | <AU> <semicolon> <space> <LIST>
    <AU> ::= <UNDERLYING> <space> <SPC>
the list shall be sorted by <UNDERLYING>.
Example: "SE 50", "FIS 53; US$ 45.46".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
additionalUnderlyings The additional underlyings for options, including additional cash.
Returns
A shared pointer to the current instrument profile.
References setAdditionalUnderlyings().
withBaseCurrency()
InstrumentProfile& dxfcpp::InstrumentProfile::withBaseCurrency (const std::string & baseCurrency) inline noexcept
Changes base currency of currency pair (FOREX instruments).
It shall use three-letter currency code similarly to currency.
Parameters
baseCurrency The base currency of currency pair (FOREX instruments).
Returns
The current instrument profile.
References setBaseCurrency().
withBaseCurrencyShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withBaseCurrencyShared (const std::string & baseCurrency) inline noexcept
Changes base currency of currency pair (FOREX instruments).
It shall use three-letter currency code similarly to currency.
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
baseCurrency The base currency of currency pair (FOREX instruments).
Returns
A shared pointer to the current instrument profile.
References setBaseCurrency().
withCFI()
InstrumentProfile& dxfcpp::InstrumentProfile::withCFI (const std::string & cfi) inline noexcept
Changes Classification of Financial Instruments code.
It is a mandatory field for OPTION instruments as it is the only way to distinguish Call/Put type, American/European exercise, Cash/Physical delivery. It shall use six-letter CFI code from ISO 10962 standard. It is allowed to use 'X' extensively and to omit trailing letters (assumed to be 'X'). See ISO 10962 on Wikipedia. Example: "ESNTPB", "ESXXXX", "ES" , "OPASPS".
Parameters
cfi CFI code.
Returns
The current instrument profile.
References setCFI().
withCFIShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withCFIShared (const std::string & cfi) inline noexcept
Changes Classification of Financial Instruments code.
It is a mandatory field for OPTION instruments as it is the only way to distinguish Call/Put type, American/European exercise, Cash/Physical delivery. It shall use six-letter CFI code from ISO 10962 standard. It is allowed to use 'X' extensively and to omit trailing letters (assumed to be 'X'). See ISO 10962 on Wikipedia. Example: "ESNTPB", "ESXXXX", "ES" , "OPASPS".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
cfi CFI code.
Returns
A shared pointer to the current instrument profile.
References setCFI().
withCountry()
InstrumentProfile& dxfcpp::InstrumentProfile::withCountry (const std::string & country) inline noexcept
Changes country of origin (incorporation) of corresponding company or parent entity.
It shall use two-letter country code from ISO 3166-1 standard. See ISO 3166-1 on Wikipedia. Example: "US", "RU".
Parameters
country The country of origin (incorporation) of corresponding company or parent entity.
Returns
The current instrument profile.
References setCountry().
withCountryShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withCountryShared (const std::string & country) inline noexcept
Changes country of origin (incorporation) of corresponding company or parent entity.
It shall use two-letter country code from ISO 3166-1 standard. See ISO 3166-1 on Wikipedia. Example: "US", "RU".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
country The country of origin (incorporation) of corresponding company or parent entity.
Returns
A shared pointer to the current instrument profile.
References setCountry().
withCurrency()
InstrumentProfile& dxfcpp::InstrumentProfile::withCurrency (const std::string & currency) inline noexcept
Changes currency of quotation, pricing and trading.
It shall use three-letter currency code from ISO 4217 standard. See ISO 4217 on Wikipedia. Example: "USD", "RUB".
Parameters
currency Currency of quotation, pricing and trading.
Returns
The current instrument profile.
References setCurrency().
withCurrencyShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withCurrencyShared (const std::string & currency) inline noexcept
Changes currency of quotation, pricing and trading.
It shall use three-letter currency code from ISO 4217 standard. See ISO 4217 on Wikipedia. Example: "USD", "RUB".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
currency Currency of quotation, pricing and trading.
Returns
A shared pointer to the current instrument profile.
References setCurrency().
withCUSIP()
InstrumentProfile& dxfcpp::InstrumentProfile::withCUSIP (const std::string & cusip) inline noexcept
Changes Committee on Uniform Security Identification Procedures code.
It shall use nine-letter code assigned by CUSIP Services Bureau. See CUSIP on Wikipedia. Example: "38259P508".
Parameters
cusip CUSIP code
Returns
The current instrument profile.
References setCUSIP().
withCUSIPShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withCUSIPShared (const std::string & cusip) inline noexcept
Changes Committee on Uniform Security Identification Procedures code.
It shall use nine-letter code assigned by CUSIP Services Bureau. See CUSIP on Wikipedia. Example: "38259P508".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
cusip CUSIP code
Returns
A shared pointer to the current instrument profile.
References setCUSIP().
withDescription()
InstrumentProfile& dxfcpp::InstrumentProfile::withDescription (const std::string & description) inline noexcept
Changes description of instrument, preferable an international one in Latin alphabet.
Example: "Google Inc.", "Mini Gold Futures,Jun-2009,ETH".
Parameters
description The description of instrument.
Returns
The current instrument profile.
References setDescription().
withDescriptionShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withDescriptionShared (const std::string & description) inline noexcept
Changes description of instrument, preferable an international one in Latin alphabet.
Example: "Google Inc.", "Mini Gold Futures,Jun-2009,ETH".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
description The description of instrument.
Returns
A shared pointer to the current instrument profile.
References setDescription().
withExchangeData()
InstrumentProfile& dxfcpp::InstrumentProfile::withExchangeData (const std::string & exchangeData) inline noexcept
Changes exchange-specific data required to properly identify instrument when communicating with exchange.
It uses exchange-specific format.
Parameters
exchangeData The exchange-specific data required to properly identify instrument when communicating with exchange.
Returns
The current instrument profile.
References setExchangeData().
withExchangeDataShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withExchangeDataShared (const std::string & exchangeData) inline noexcept
Changes exchange-specific data required to properly identify instrument when communicating with exchange.
It uses exchange-specific format.
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
exchangeData The exchange-specific data required to properly identify instrument when communicating with exchange.
Returns
A shared pointer to the current instrument profile.
References setExchangeData().
withExchanges()
InstrumentProfile& dxfcpp::InstrumentProfile::withExchanges (const std::string & exchanges) inline noexcept
Changes list of exchanges where instrument is quoted or traded.
It shall use the following format:
<VALUE> ::= <empty> | <LIST>
<LIST> ::= <MIC> | <MIC> <semicolon>
<LIST> the list shall be sorted by MIC.
Example: "ARCX;CBSX ;XNAS;XNYS".
Parameters
exchanges The list of exchanges where instrument is quoted or traded.
Returns
The current instrument profile.
References setExchanges().
withExchangesShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withExchangesShared (const std::string & exchanges) inline noexcept
Changes list of exchanges where instrument is quoted or traded.
It shall use the following format:
<VALUE> ::= <empty> | <LIST>
<LIST> ::= <MIC> | <MIC> <semicolon>
<LIST> the list shall be sorted by MIC.
Example: "ARCX;CBSX ;XNAS;XNYS".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
exchanges The list of exchanges where instrument is quoted or traded.
Returns
A shared pointer to the current instrument profile.
References setExchanges().
withExpiration()
InstrumentProfile& dxfcpp::InstrumentProfile::withExpiration (std::int32_t expiration) inline noexcept
Changes day id of expiration.
Example: day_util::#getDayIdByYearMonthDay() "dxfcpp::day_util::getDayIdByYearMonthDay"(20090117).
Parameters
expiration The day id of expiration.
Returns
The current instrument profile.
References setExpiration().
withExpirationShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withExpirationShared (std::int32_t expiration) inline noexcept
Changes day id of expiration.
Example: day_util::#getDayIdByYearMonthDay() "dxfcpp::day_util::getDayIdByYearMonthDay"(20090117).
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
expiration The day id of expiration.
Returns
A shared pointer to the current instrument profile.
References setExpiration().
withExpirationStyle()
InstrumentProfile& dxfcpp::InstrumentProfile::withExpirationStyle (const std::string & expirationStyle) inline noexcept
Changes the expiration cycle style, such as "Weeklys", "Quarterlys".
Parameters
expirationStyle The expiration cycle style.
Returns
The current instrument profile.
References setExpirationStyle().
withExpirationStyleShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withExpirationStyleShared (const std::string & expirationStyle) inline noexcept
Changes the expiration cycle style, such as "Weeklys", "Quarterlys".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
expirationStyle The expiration cycle style.
Returns
A shared pointer to the current instrument profile.
References setExpirationStyle().
withICB()
InstrumentProfile& dxfcpp::InstrumentProfile::withICB (std::int32_t icb) inline noexcept
Changes Industry Classification Benchmark.
It shall use four-digit number from ICB catalog. See ICB on Wikipedia or ICB homepage. Example: "9535".
Parameters
icb Industry Classification Benchmark.
Returns
The current instrument profile.
References setICB().
withICBShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withICBShared (std::int32_t icb) inline noexcept
Changes Industry Classification Benchmark.
It shall use four-digit number from ICB catalog. See ICB on Wikipedia or ICB homepage. Example: "9535".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
icb Industry Classification Benchmark.
Returns
A shared pointer to the current instrument profile.
References setICB().
withISIN()
InstrumentProfile& dxfcpp::InstrumentProfile::withISIN (const std::string & isin) inline noexcept
Changes International Securities Identifying Number.
It shall use twelve-letter code from ISO 6166 standard. See ISO 6166 on Wikipedia or ISIN on Wikipedia. Example: "DE0007100000", "US38259P5089".
Parameters
isin International Securities Identifying Number.
Returns
The current instrument profile.
References setISIN().
withISINShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withISINShared (const std::string & isin) inline noexcept
Changes International Securities Identifying Number.
It shall use twelve-letter code from ISO 6166 standard. See ISO 6166 on Wikipedia or ISIN on Wikipedia. Example: "DE0007100000", "US38259P5089".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
isin International Securities Identifying Number.
Returns
A shared pointer to the current instrument profile.
References setISIN().
withLastTrade()
InstrumentProfile& dxfcpp::InstrumentProfile::withLastTrade (std::int32_t lastTrade) inline noexcept
Changes day id of last trading day.
Example: day_util::#getDayIdByYearMonthDay() "dxfcpp::day_util::getDayIdByYearMonthDay"(20090116).
Parameters
lastTrade The day id of last trading day.
Returns
The current instrument profile.
References setLastTrade().
withLastTradeShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withLastTradeShared (std::int32_t lastTrade) inline noexcept
Changes day id of last trading day.
Example: day_util::#getDayIdByYearMonthDay() "dxfcpp::day_util::getDayIdByYearMonthDay"(20090116).
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
lastTrade The day id of last trading day.
Returns
A shared pointer to the current instrument profile.
References setLastTrade().
withLocalDescription()
InstrumentProfile& dxfcpp::InstrumentProfile::withLocalDescription (const std::string & localDescription) inline noexcept
Changes description of instrument in national language.
It shall be empty if same as description.
Parameters
localDescription The description of instrument in national language.
Returns
The current instrument profile.
References setLocalDescription().
withLocalDescriptionShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withLocalDescriptionShared (const std::string & localDescription) inline noexcept
Changes description of instrument in national language.
It shall be empty if same as description.
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
localDescription The description of instrument in national language.
Returns
A shared pointer to the current instrument profile.
References setLocalDescription().
withLocalSymbol()
InstrumentProfile& dxfcpp::InstrumentProfile::withLocalSymbol (const std::string & localSymbol) inline noexcept
Changes identifier of instrument in national language.
It shall be empty if same as symbol.
Parameters
localSymbol The identifier of instrument in national language.
Returns
The current instrument profile.
References setLocalSymbol().
withLocalSymbolShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withLocalSymbolShared (const std::string & localSymbol) inline noexcept
Changes identifier of instrument in national language.
It shall be empty if same as symbol.
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
localSymbol The identifier of instrument in national language.
Returns
A shared pointer to the current instrument profile.
References setLocalSymbol().
withMMY()
InstrumentProfile& dxfcpp::InstrumentProfile::withMMY (const std::string & mmy) inline noexcept
Changes maturity month-year as provided for corresponding FIX tag (200).
It can use several different formats depending on data source:
YYYYMM if only year and month are specified
YYYYMMDD if full date is specified
YYYYMMwN if week number (within a month) is specified
Parameters
mmy The maturity month-year as provided for corresponding FIX tag (200).
Returns
The current instrument profile.
References setMMY().
withMMYShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withMMYShared (const std::string & mmy) inline noexcept
Changes maturity month-year as provided for corresponding FIX tag (200).
It can use several different formats depending on data source:
YYYYMM if only year and month are specified
YYYYMMDD if full date is specified
YYYYMMwN if week number (within a month) is specified
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
mmy The maturity month-year as provided for corresponding FIX tag (200).
Returns
A shared pointer to the current instrument profile.
References setMMY().
withMultiplier()
InstrumentProfile& dxfcpp::InstrumentProfile::withMultiplier (double multiplier) inline noexcept
Changes market value multiplier.
Example: 100, 33.2.
Parameters
multiplier The market value multiplier.
Returns
The current instrument profile.
References setMultiplier().
withMultiplierShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withMultiplierShared (double multiplier) inline noexcept
Changes market value multiplier.
Example: 100, 33.2.
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
multiplier The market value multiplier.
Returns
A shared pointer to the current instrument profile.
References setMultiplier().
withOPOL()
InstrumentProfile& dxfcpp::InstrumentProfile::withOPOL (const std::string & opol) inline noexcept
Changes official Place Of Listing, the organization that have listed this instrument.
Instruments with multiple listings shall use separate profiles for each listing. It shall use Market Identifier Code (MIC) from ISO 10383 standard. See ISO 10383 on Wikipedia or MIC homepage. Example: "XNAS", "RTSX"
Parameters
opol The official Place Of Listing, the organization that have listed this instrument.
Returns
The current instrument profile.
References setOPOL().
withOPOLShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withOPOLShared (const std::string & opol) inline noexcept
Changes official Place Of Listing, the organization that have listed this instrument.
Instruments with multiple listings shall use separate profiles for each listing. It shall use Market Identifier Code (MIC) from ISO 10383 standard. See ISO 10383 on Wikipedia or MIC homepage. Example: "XNAS", "RTSX"
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
opol The official Place Of Listing, the organization that have listed this instrument.
Returns
A shared pointer to the current instrument profile.
References setOPOL().
withOptionType()
InstrumentProfile& dxfcpp::InstrumentProfile::withOptionType (const std::string & optionType) inline noexcept
Changes type of option.
It shall use one of following values:
STAN = Standard Options
LEAP = Long-term Equity AnticiPation Securities
SDO = Special Dated Options
BINY = Binary Options
FLEX = FLexible EXchange Options
VSO = Variable Start Options
RNGE = Range
Parameters
optionType The type of option.
Returns
The current instrument profile.
References setOptionType().
withOptionTypeShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withOptionTypeShared (const std::string & optionType) inline noexcept
Changes type of option.
It shall use one of following values:
STAN = Standard Options
LEAP = Long-term Equity AnticiPation Securities
SDO = Special Dated Options
BINY = Binary Options
FLEX = FLexible EXchange Options
VSO = Variable Start Options
RNGE = Range
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
optionType The type of option.
Returns
A shared pointer to the current instrument profile.
References setOptionType().
withPriceIncrements()
InstrumentProfile& dxfcpp::InstrumentProfile::withPriceIncrements (const std::string & priceIncrements) inline noexcept
Changes minimum allowed price increments with corresponding price ranges.
It shall use following format:
    <VALUE> ::= <empty> | <LIST>
    <LIST> ::= <INCREMENT> | <RANGE> <semicolon> <space> <LIST>
    <RANGE> ::= <INCREMENT> <space> <UPPER_LIMIT>
the list shall be sorted by <UPPER_LIMIT>.
Example: "0.25", "0.01 3; 0.05".
Parameters
priceIncrements The minimum allowed price increments with corresponding price ranges.
Returns
The current instrument profile.
References setPriceIncrements().
withPriceIncrementsShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withPriceIncrementsShared (const std::string & priceIncrements) inline noexcept
Changes minimum allowed price increments with corresponding price ranges.
It shall use following format:
    <VALUE> ::= <empty> | <LIST>
    <LIST> ::= <INCREMENT> | <RANGE> <semicolon> <space> <LIST>
    <RANGE> ::= <INCREMENT> <space> <UPPER_LIMIT>
the list shall be sorted by <UPPER_LIMIT>.
Example: "0.25", "0.01 3; 0.05".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
priceIncrements The minimum allowed price increments with corresponding price ranges.
Returns
A shared pointer to the current instrument profile.
References setPriceIncrements().
withProduct()
InstrumentProfile& dxfcpp::InstrumentProfile::withProduct (const std::string & product) inline noexcept
Changes product for futures and options on futures (underlying asset name).
Example: "/YG".
Parameters
product The product for futures and options on futures (underlying asset name).
Returns
The current instrument profile.
References setProduct().
withProductShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withProductShared (const std::string & product) inline noexcept
Changes product for futures and options on futures (underlying asset name).
Example: "/YG".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
product The product for futures and options on futures (underlying asset name).
Returns
A shared pointer to the current instrument profile.
References setProduct().
withSEDOL()
InstrumentProfile& dxfcpp::InstrumentProfile::withSEDOL (const std::string & sedol) inline noexcept
Changes Stock Exchange Daily Official List.
It shall use seven-letter code assigned by London Stock Exchange. See SEDOL on Wikipedia or SEDOL on LSE. Example: "2310967", "5766857".
Parameters
sedol Stock Exchange Daily Official List.
Returns
The current instrument profile.
References setSEDOL().
withSEDOLShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withSEDOLShared (const std::string & sedol) inline noexcept
Changes Stock Exchange Daily Official List.
It shall use seven-letter code assigned by London Stock Exchange. See SEDOL on Wikipedia or SEDOL on LSE. Example: "2310967", "5766857".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
sedol Stock Exchange Daily Official List.
Returns
A shared pointer to the current instrument profile.
References setSEDOL().
withSettlementStyle()
InstrumentProfile& dxfcpp::InstrumentProfile::withSettlementStyle (const std::string & settlementStyle) inline noexcept
Changes settlement price determination style, such as "Open", "Close".
Parameters
settlementStyle The settlement price determination style.
Returns
The current instrument profile.
References setSettlementStyle().
withSettlementStyleShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withSettlementStyleShared (const std::string & settlementStyle) inline noexcept
Changes settlement price determination style, such as "Open", "Close".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
settlementStyle The settlement price determination style.
Returns
A shared pointer to the current instrument profile.
References setSettlementStyle().
withSIC()
InstrumentProfile& dxfcpp::InstrumentProfile::withSIC (std::int32_t sic) inline noexcept
Changes Standard Industrial Classification.
It shall use four-digit number from SIC catalog. See SIC on Wikipedia or SIC structure. Example: "7371".
Parameters
sic Standard Industrial Classification.
Returns
The current instrument profile.
References setSIC().
withSICShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withSICShared (std::int32_t sic) inline noexcept
Changes Standard Industrial Classification.
It shall use four-digit number from SIC catalog. See SIC on Wikipedia or SIC structure. Example: "7371".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
sic Standard Industrial Classification.
Returns
A shared pointer to the current instrument profile.
References setSIC().
withSPC()
InstrumentProfile& dxfcpp::InstrumentProfile::withSPC (double spc) inline noexcept
Changes shares per contract for options.
Example: 1, 100.
Parameters
spc The shares per contract for options.
Returns
The current instrument profile.
References setSPC().
withSPCShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withSPCShared (double spc) inline noexcept
Changes shares per contract for options.
Example: 1, 100.
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
spc The shares per contract for options.
Returns
A shared pointer to the current instrument profile.
References setSPC().
withStrike()
InstrumentProfile& dxfcpp::InstrumentProfile::withStrike (double strike) inline noexcept
Changes strike price for options.
Example: 80, 22.5.
Parameters
strike The strike price for options
Returns
The current instrument profile.
References setStrike().
withStrikeShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withStrikeShared (double strike) inline noexcept
Changes strike price for options.
Example: 80, 22.5.
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
strike The strike price for options
Returns
A shared pointer to the current instrument profile.
References setStrike().
withSymbol()
InstrumentProfile& dxfcpp::InstrumentProfile::withSymbol (const std::string & symbol) inline noexcept
Changes identifier of instrument, preferable an international one in Latin alphabet.
It is a mandatory field. It may not be empty. Example: "GOOG", "/YGM9", ".ZYEAD".
Parameters
symbol The identifier of instrument.
Returns
The current instrument profile.
References setSymbol().
withSymbolShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withSymbolShared (const std::string & symbol) inline noexcept
Changes identifier of instrument, preferable an international one in Latin alphabet.
It is a mandatory field. It may not be empty. Example: "GOOG", "/YGM9", ".ZYEAD".
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
symbol The identifier of instrument.
Returns
A shared pointer to the current instrument profile.
References setSymbol().
withTradingHours()
InstrumentProfile& dxfcpp::InstrumentProfile::withTradingHours (const std::string & tradingHours) inline noexcept
Changes trading hours specification.
See Schedule::getInstance().
Parameters
tradingHours The trading hours specification.
Returns
The current instrument profile.
References setTradingHours().
withTradingHoursShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withTradingHoursShared (const std::string & tradingHours) inline noexcept
Changes trading hours specification.
See Schedule::getInstance().
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
tradingHours The trading hours specification.
Returns
A shared pointer to the current instrument profile.
References setTradingHours().
withType()
InstrumentProfile& dxfcpp::InstrumentProfile::withType (const std::string & type) inline noexcept
Changes type of instrument and returns the current instrument profile.
Parameters
type The type of instrument.
Returns
The current instrument profile.
References setType().
withTypeShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withTypeShared (const std::string & type) inline noexcept
Changes type of instrument and returns a shared pointer to the current instrument profile.
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
type The type of instrument.
Returns
A shared pointer to the current instrument profile.
References setType().
withUnderlying()
InstrumentProfile& dxfcpp::InstrumentProfile::withUnderlying (const std::string & underlying) inline noexcept
Changes primary underlying symbol for options.
Example: "C", "/YGM9"
Parameters
underlying The primary underlying symbol for options.
Returns
The current instrument profile.
References setUnderlying().
withUnderlyingShared()
InstrumentProfile::Ptr dxfcpp::InstrumentProfile::withUnderlyingShared (const std::string & underlying) inline noexcept
Changes primary underlying symbol for options.
Example: "C", "/YGM9"
Warning
Please do not use this method unless the object was created with std::shared_ptr<InstrumentProfile>(new InstrumentProfile(...)) or std::make_shared<InstrumentProfile>(...)
Parameters
underlying The primary underlying symbol for options.
Returns
A shared pointer to the current instrument profile.
References setUnderlying().