dxFeed Graal CXX API: dxfcpp::OptionSale Class Reference
dxfcpp::OptionSale Class Reference final
Option Sale event represents a trade or another market event with the price (for example, market open/close price, etc.) for each option symbol listed under the specified Underlying.
#include <OptionSale.hpp>
Public Types
using Ptr = std::shared_ptr< OptionSale >
The alias to a type of shared pointer to the OptionSale object.
using Unique = std::unique_ptr< OptionSale >
The alias to a type of unique pointer to the OptionSale object.
Public Types inherited from dxfcpp::MarketEvent
using Ptr = std::shared_ptr< MarketEvent >
The alias to a type of shared pointer to the MarketEvent object.
Public Types inherited from dxfcpp::EventTypeWithSymbol< std::string >
using Ptr = std::shared_ptr< EventTypeWithSymbol< std::string > >
The alias to a type of shared pointer to the EventTypeWithSymbol's child object.
Public Types inherited from dxfcpp::EventType
using Ptr = std::shared_ptr< EventType >
The alias to a type of shared pointer to the EventType object.
Public Types inherited from dxfcpp::SharedEntity
using Ptr = std::shared_ptr< SharedEntity >
The alias to a type of shared pointer to the SharedEntity object.
Public Types inherited from dxfcpp::IndexedEvent
using Ptr = std::shared_ptr< IndexedEvent >
The alias to a type of shared pointer to the IndexedEvent object.
Public Member Functions
void * toGraal () const noexcept override
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
OptionSale () noexcept=default
Creates new option sale event with default values.
OptionSale (std::string eventSymbol) noexcept
Creates new option sale event with the specified event symbol.
const IndexedEventSource & getSource () const &noexcept override
Returns the source of this event.
std::int32_t getEventFlags () const noexcept override
Returns transactional event flags.
EventFlagsMask getEventFlagsMask () const noexcept override
Returns transactional event flags.
void setEventFlags (std::int32_t eventFlags) noexcept override
Changes transactional event flags.
void setEventFlags (const EventFlagsMask &eventFlags) noexcept override
Changes transactional event flags.
std::int64_t getIndex () const noexcept override
Returns unique per-symbol index of this event.
void setIndex (std::int64_t index) noexcept override
Changes unique per-symbol index of this event.
std::int64_t getTimeSequence () const noexcept
Returns time and sequence of this event packaged into single long value.
void setTimeSequence (std::int64_t timeSequence) noexcept
Changes time and sequence of this event.
std::int64_t getTime () const noexcept
Returns time of this event.
void setTime (std::int64_t time) noexcept
Changes time of this event.
std::int64_t getTimeNanos () const noexcept
Returns time of the original event in nanoseconds.
void setTimeNanos (std::int64_t timeNanos) noexcept
Changes time of the original event.
void setTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds time part of the original event.
std::int32_t getTimeNanoPart () const noexcept
Returns microseconds and nanoseconds time part of the original event.
std::int32_t getSequence () const noexcept
Returns the sequence number of this event to distinguish events that have the same time.
void setSequence (int sequence) noexcept
Changes sequence number of this event.
std::int16_t getExchangeCode () const noexcept
Returns exchange code of this option sale event.
std::string getExchangeCodeString () const noexcept
Returns exchange code of this option sale as UTF8 string.
void setExchangeCode (char exchangeCode) noexcept
Changes exchange code of this option sale event.
void setExchangeCode (std::int16_t exchangeCode) noexcept
Changes exchange code of this option sale event.
double getPrice () const noexcept
Returns price of this option sale event.
void setPrice (double price) noexcept
Changes price of this option sale event.
double getSize () const noexcept
Returns size of this option sale event.
void setSize (double size) noexcept
Changes size of this option sale event.
double getBidPrice () const noexcept
Returns the current bid price on the market when this option sale event had occurred.
void setBidPrice (double bidPrice) noexcept
Changes the current bid price on the market when this option sale event had occurred.
double getAskPrice () const noexcept
Returns the current ask price on the market when this option sale event had occurred.
void setAskPrice (double askPrice) noexcept
Changes price of this time and sale event.the current ask price on the market when this option sale event had occurred.
const std::string & getExchangeSaleConditions () const &noexcept
Returns sale conditions provided for this event by data feed.
const std::optional< std::string > & getExchangeSaleConditionsOpt () const &noexcept
Returns sale conditions provided for this event by data feed.
void setExchangeSaleConditions (std::string exchangeSaleConditions) noexcept
Changes sale conditions provided for this event by data feed.
char getTradeThroughExempt () const noexcept
Returns TradeThroughExempt flag of this option sale event.
void setTradeThroughExempt (char tradeThroughExempt) noexcept
Changes TradeThroughExempt flag of this option sale event.
const Side & getAggressorSide () const &noexcept
Returns aggressor side of this option sale event.
void setAggressorSide (const Side &side) noexcept
Changes aggressor side of this option sale event.
bool isSpreadLeg () const noexcept
Returns whether this event represents a spread leg.
void setSpreadLeg (bool spreadLeg) noexcept
Changes whether this event represents a spread leg.
bool isExtendedTradingHours () const noexcept
Returns whether this event represents an extended trading hours sale.
void setExtendedTradingHours (bool extendedTradingHours) noexcept
Changes whether this event represents an extended trading hours sale.
bool isValidTick () const noexcept
Returns whether this event represents a valid intraday tick.
void setValidTick (bool validTick) noexcept
Changes whether this event represents a valid intraday tick.
const TimeAndSaleType & getType () const &noexcept
Returns type of this option sale event.
void setType (const TimeAndSaleType &type) noexcept
Changes type of this option sale event.
bool isNew () const noexcept
Returns whether this is a new event (not cancellation or correction).
bool isCorrection () const noexcept
Returns whether this is a correction of a previous event.
bool isCancel () const noexcept
Returns whether this is a cancellation of a previous event.
double getUnderlyingPrice () const noexcept
Returns underlying price at the time of this option sale event.
void setUnderlyingPrice (double underlyingPrice) noexcept
Changes underlying price at the time of this option sale event.
double getVolatility () const noexcept
Returns Black-Scholes implied volatility of the option at the time of this option sale event.
void setVolatility (double volatility) noexcept
Changes Black-Scholes implied volatility of the option at the time of this option sale event.
double getDelta () const noexcept
Return option delta at the time of this option sale event.
void setDelta (double delta) noexcept
Changes option delta at the time of this option sale event.
const std::string & getOptionSymbol () const &noexcept
Returns option symbol of this event.
const std::optional< std::string > & getOptionSymbolOpt () const &noexcept
Returns option symbol of this event.
void setOptionSymbol (std::string optionSymbol) noexcept
Changes option symbol of this event.
std::string toString () const noexcept override
Returns a string representation of the current object.
Public Member Functions inherited from dxfcpp::MarketEvent
const std::string & getEventSymbol () const &noexcept override
Returns symbol of this event.
const std::optional< std::string > & getEventSymbolOpt () const &noexcept override
Returns symbol of this event.
void setEventSymbol (const std::string &eventSymbol) noexcept override
Changes symbol of this event.
std::int64_t getEventTime () const noexcept override
Returns time when event was created or zero when time is not available.
void setEventTime (std::int64_t eventTime) noexcept override
Changes event creation time.
Public Member Functions inherited from dxfcpp::SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
Public Member Functions inherited from dxfcpp::Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Static Public Member Functions
static void freeGraal (void *graalNative) noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Attributes
static constexpr std::uint32_t MAX_SEQUENCE = (1U << 22U) - 1U
Maximum allowed sequence value.
static const EventTypeEnum & TYPE = EventTypeEnum::OPTION_SALE
Type identifier and additional information about the current event class.
Static Public Attributes inherited from dxfcpp::IndexedEvent
static const EventFlag TX_PENDING = EventFlag::TX_PENDING
0x01 - A bitmask to get transaction pending indicator from the value of eventFlags property.
static const EventFlag REMOVE_EVENT = EventFlag::REMOVE_EVENT
0x02 - A bitmask to get removal indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_BEGIN = EventFlag::SNAPSHOT_BEGIN
0x04 - A bitmask to get snapshot begin indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_END = EventFlag::SNAPSHOT_END
0x08 - A bitmask to get snapshot end indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_SNIP = EventFlag::SNAPSHOT_SNIP
0x10 - A bitmask to get snapshot snip indicator from the value of eventFlags property.
static const EventFlag SNAPSHOT_MODE = EventFlag::SNAPSHOT_MODE
0x40 - A bitmask to set snapshot mode indicator into the value of eventFlags property.
Additional Inherited Members
Protected Member Functions inherited from dxfcpp::MarketEvent
MarketEvent (std::string eventSymbol) noexcept
Protected constructor for concrete implementation classes that initializes eventSymbol property.
Detailed Description
Option Sale event represents a trade or another market event with the price (for example, market open/close price, etc.) for each option symbol listed under the specified Underlying.
Option Sales are intended to provide information about option trades in a continuous time slice with the additional metrics, like Option Volatility, Option Delta, and Underlying Price.
Option Sale events have unique index which can be used for later correction/cancellation processing.
Option sale data source provides a consistent view of the set of known option sales. The corresponding information is carried in eventFlags property. The logic behind this property is detailed in IndexedEvent class documentation. Multiple event sources for the same symbol are not supported for option sale events, thus source property is always DEFAULT.
This event is implemented on top of QDS records OptionSale.
Constructor & Destructor Documentation
OptionSale()
dxfcpp::OptionSale::OptionSale (std::string eventSymbol) inline explicit noexcept
Creates new option sale event with the specified event symbol.
Parameters
eventSymbol The event symbol.
References dxfcpp::MarketEvent::MarketEvent().
Member Function Documentation
freeGraal()
void dxfcpp::OptionSale::freeGraal (void * graalNative) static noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
getAggressorSide()
const Side& dxfcpp::OptionSale::getAggressorSide () const & inline noexcept
Returns aggressor side of this option sale event.
Returns
aggressor side of this option sale event.
getAskPrice()
double dxfcpp::OptionSale::getAskPrice () const inline noexcept
Returns the current ask price on the market when this option sale event had occurred.
Returns
the current ask price on the market when this option sale event had occurred.
getBidPrice()
double dxfcpp::OptionSale::getBidPrice () const inline noexcept
Returns the current bid price on the market when this option sale event had occurred.
Returns
the current bid price on the market when this option sale event had occurred.
getDelta()
double dxfcpp::OptionSale::getDelta () const inline noexcept
Return option delta at the time of this option sale event.
Delta is the first derivative of an option price by an underlying price.
Returns
option delta at the time of this option sale event.
getEventFlags()
std::int32_t dxfcpp::OptionSale::getEventFlags () const inline override virtual noexcept
Returns transactional event flags.
See EventFlag "Event Flags" section.
Returns
The transactional event flags.
Implements dxfcpp::IndexedEvent.
getEventFlagsMask()
EventFlagsMask dxfcpp::OptionSale::getEventFlagsMask () const inline override virtual noexcept
Returns transactional event flags.
See EventFlag "Event Flags" section.
Returns
The transactional event flags' mask.
Implements dxfcpp::IndexedEvent.
getExchangeCode()
std::int16_t dxfcpp::OptionSale::getExchangeCode () const inline noexcept
Returns exchange code of this option sale event.
Returns
exchange code of this option sale event.
getExchangeCodeString()
std::string dxfcpp::OptionSale::getExchangeCodeString () const inline noexcept
Returns exchange code of this option sale as UTF8 string.
Returns
exchange code of this option sale as UTF8 string.
getExchangeSaleConditions()
const std::string& dxfcpp::OptionSale::getExchangeSaleConditions () const & inline noexcept
Returns sale conditions provided for this event by data feed.
This field format is specific for every particular data feed.
Returns
sale conditions or dxfcpp::String::NUL (std::string{"<null>"}).
getExchangeSaleConditionsOpt()
const std::optional<std::string>& dxfcpp::OptionSale::getExchangeSaleConditionsOpt () const & inline noexcept
Returns sale conditions provided for this event by data feed.
This field format is specific for every particular data feed.
Returns
sale conditions or std::nullopt.
getIndex()
std::int64_t dxfcpp::OptionSale::getIndex () const inline override virtual noexcept
Returns unique per-symbol index of this event.
The index is composed of time and sequence. Changing either time or sequence changes event index.
Returns
unique index of this event.
Implements dxfcpp::IndexedEvent.
getOptionSymbol()
const std::string& dxfcpp::OptionSale::getOptionSymbol () const & inline noexcept
Returns option symbol of this event.
Returns
option symbol of this event or dxfcpp::String::NUL (std::string{"<null>"}).
getOptionSymbolOpt()
const std::optional<std::string>& dxfcpp::OptionSale::getOptionSymbolOpt () const & inline noexcept
Returns option symbol of this event.
Returns
option symbol of this event or std::nullopt
getPrice()
double dxfcpp::OptionSale::getPrice () const inline noexcept
Returns price of this option sale event.
Returns
price of this option sale event.
getSequence()
std::int32_t dxfcpp::OptionSale::getSequence () const inline noexcept
Returns the sequence number of this event to distinguish events that have the same time.
This sequence number does not have to be unique and does not need to be sequential. Sequence can range from 0 to ::MAX_SEQUENCE.
Returns
The sequence number of this event
getSize()
double dxfcpp::OptionSale::getSize () const inline noexcept
Returns size of this option sale event.
Returns
size of this option sale event.
getSource()
const IndexedEventSource& dxfcpp::OptionSale::getSource () const & inline override virtual noexcept
Returns the source of this event.
Returns
The source of this event.
Implements dxfcpp::IndexedEvent.
References dxfcpp::IndexedEventSource::DEFAULT.
getTime()
std::int64_t dxfcpp::OptionSale::getTime () const inline noexcept
Returns time of this event.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
Returns
time of this event.
getTimeNanoPart()
std::int32_t dxfcpp::OptionSale::getTimeNanoPart () const inline noexcept
Returns microseconds and nanoseconds time part of the original event.
Returns
microseconds and nanoseconds time part of the original event.
getTimeNanos()
std::int64_t dxfcpp::OptionSale::getTimeNanos () const inline noexcept
Returns time of the original event in nanoseconds.
Time is measured in nanoseconds between the current time and midnight, January 1, 1970 UTC.
Returns
time of the original event in nanoseconds.
getTimeSequence()
std::int64_t dxfcpp::OptionSale::getTimeSequence () const inline noexcept
Returns time and sequence of this event packaged into single long value.
Returns
time and sequence of this event.
getTradeThroughExempt()
char dxfcpp::OptionSale::getTradeThroughExempt () const inline noexcept
Returns TradeThroughExempt flag of this option sale event.
Returns
TradeThroughExempt flag of this option sale event.
getType()
const TimeAndSaleType& dxfcpp::OptionSale::getType () const & inline noexcept
Returns type of this option sale event.
Returns
type of this option sale event.
Referenced by isCancel(), isCorrection(), and isNew().
getUnderlyingPrice()
double dxfcpp::OptionSale::getUnderlyingPrice () const inline noexcept
Returns underlying price at the time of this option sale event.
Returns
underlying price at the time of this option sale event.
getVolatility()
double dxfcpp::OptionSale::getVolatility () const inline noexcept
Returns Black-Scholes implied volatility of the option at the time of this option sale event.
Returns
Black-Scholes implied volatility of the option at the time of this option sale event.
isCancel()
bool dxfcpp::OptionSale::isCancel () const inline noexcept
Returns whether this is a cancellation of a previous event.
It is false for newly created option sale event.
Returns
true if this is a cancellation of a previous event
References dxfcpp::TimeAndSaleType::CANCEL, and getType().
isCorrection()
bool dxfcpp::OptionSale::isCorrection () const inline noexcept
Returns whether this is a correction of a previous event.
It is false for newly created option sale event.
Returns
true if this is a correction of a previous event
References dxfcpp::TimeAndSaleType::CORRECTION, and getType().
isExtendedTradingHours()
bool dxfcpp::OptionSale::isExtendedTradingHours () const inline noexcept
Returns whether this event represents an extended trading hours sale.
Returns
true if this event represents an extended trading hours sale.
isNew()
bool dxfcpp::OptionSale::isNew () const inline noexcept
Returns whether this is a new event (not cancellation or correction).
It is true for newly created option sale event.
Returns
true if this is a new event (not cancellation or correction).
References getType(), and dxfcpp::TimeAndSaleType::NEW.
isSpreadLeg()
bool dxfcpp::OptionSale::isSpreadLeg () const inline noexcept
Returns whether this event represents a spread leg.
Returns
true if this event represents a spread leg.
isValidTick()
bool dxfcpp::OptionSale::isValidTick () const inline noexcept
Returns whether this event represents a valid intraday tick.
Note, that a correction for a previously distributed valid tick represents a new valid tick itself, but a cancellation of a previous valid tick does not.
Returns
true if this event represents a valid intraday tick.
setAggressorSide()
void dxfcpp::OptionSale::setAggressorSide (const Side & side) inline noexcept
Changes aggressor side of this option sale event.
Parameters
side aggressor side of this option sale event.
setAskPrice()
void dxfcpp::OptionSale::setAskPrice (double askPrice) inline noexcept
Changes price of this time and sale event.the current ask price on the market when this option sale event had occurred.
Parameters
askPrice the current ask price on the market when this option sale event had occurred.
setBidPrice()
void dxfcpp::OptionSale::setBidPrice (double bidPrice) inline noexcept
Changes the current bid price on the market when this option sale event had occurred.
Parameters
bidPrice the current bid price on the market when this option sale event had occurred.
setDelta()
void dxfcpp::OptionSale::setDelta (double delta) inline noexcept
Changes option delta at the time of this option sale event.
Parameters
delta option delta at the time of this option sale event.
setEventFlags() [1/2]
void dxfcpp::OptionSale::setEventFlags (const EventFlagsMask & eventFlags) inline override virtual noexcept
Changes transactional event flags.
See EventFlag "Event Flags" section.
Parameters
eventFlags transactional event flags' mask.
Implements dxfcpp::IndexedEvent.
setEventFlags() [2/2]
void dxfcpp::OptionSale::setEventFlags (std::int32_t eventFlags) inline override virtual noexcept
Changes transactional event flags.
See EventFlag "Event Flags" section.
Parameters
eventFlags transactional event flags.
Implements dxfcpp::IndexedEvent.
setExchangeCode() [1/2]
void dxfcpp::OptionSale::setExchangeCode (char exchangeCode) noexcept
Changes exchange code of this option sale event.
Parameters
exchangeCode exchange code of this option sale event.
setExchangeCode() [2/2]
void dxfcpp::OptionSale::setExchangeCode (std::int16_t exchangeCode) inline noexcept
Changes exchange code of this option sale event.
Parameters
exchangeCode exchange code of this option sale event.
setExchangeSaleConditions()
void dxfcpp::OptionSale::setExchangeSaleConditions (std::string exchangeSaleConditions) inline noexcept
Changes sale conditions provided for this event by data feed.
Parameters
exchangeSaleConditions sale conditions.
setExtendedTradingHours()
void dxfcpp::OptionSale::setExtendedTradingHours (bool extendedTradingHours) inline noexcept
Changes whether this event represents an extended trading hours sale.
Parameters
extendedTradingHours true if this event represents an extended trading hours sale.
setIndex()
void dxfcpp::OptionSale::setIndex (std::int64_t index) inline override virtual noexcept
Changes unique per-symbol index of this event.
The index is composed of time and sequence and invocation of this method changes time and sequence. Do not use this method directly. Change time and/or sequence.
Parameters
index the event index.
See also
OptionSale::getIndex()
Implements dxfcpp::IndexedEvent.
setOptionSymbol()
void dxfcpp::OptionSale::setOptionSymbol (std::string optionSymbol) inline noexcept
Changes option symbol of this event.
Parameters
optionSymbol option symbol of this event.
setPrice()
void dxfcpp::OptionSale::setPrice (double price) inline noexcept
Changes price of this option sale event.
Parameters
price price of this option sale event.
setSequence()
void dxfcpp::OptionSale::setSequence (int sequence) inline noexcept
Changes sequence number of this event.
Parameters
sequence the sequence.
See also
::getSequence()
References MAX_SEQUENCE.
setSize()
void dxfcpp::OptionSale::setSize (double size) inline noexcept
Changes size of this option sale event.
Parameters
size size of this option sale event.
setSpreadLeg()
void dxfcpp::OptionSale::setSpreadLeg (bool spreadLeg) inline noexcept
Changes whether this event represents a spread leg.
Parameters
spreadLeg true if this event represents a spread leg.
setTime()
void dxfcpp::OptionSale::setTime (std::int64_t time) inline noexcept
Changes time of this event.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
Parameters
time time of this event.
Referenced by setTimeNanos().
setTimeNanoPart()
void dxfcpp::OptionSale::setTimeNanoPart (std::int32_t timeNanoPart) inline noexcept
Changes microseconds and nanoseconds time part of the original event.
Parameters
timeNanoPart microseconds and nanoseconds time part of the original event.
setTimeNanos()
void dxfcpp::OptionSale::setTimeNanos (std::int64_t timeNanos) inline noexcept
Changes time of the original event.
Time is measured in nanoseconds between the current time and midnight, January 1, 1970 UTC.
Parameters
timeNanos time of the original event in nanoseconds.
References setTime().
setTimeSequence()
void dxfcpp::OptionSale::setTimeSequence (std::int64_t timeSequence) inline noexcept
Changes time and sequence of this event.
Do not use this method directly. Change time and/or sequence.
Parameters
timeSequence the time and sequence.
See also
::getTimeSequence()
setTradeThroughExempt()
void dxfcpp::OptionSale::setTradeThroughExempt (char tradeThroughExempt) inline noexcept
Changes TradeThroughExempt flag of this option sale event.
Parameters
tradeThroughExempt TradeThroughExempt flag of this option sale event.
setType()
void dxfcpp::OptionSale::setType (const TimeAndSaleType & type) inline noexcept
Changes type of this option sale event.
Parameters
type type of this option sale event.
setUnderlyingPrice()
void dxfcpp::OptionSale::setUnderlyingPrice (double underlyingPrice) inline noexcept
Changes underlying price at the time of this option sale event.
Parameters
underlyingPrice underlying price at the time of this option sale event.
setValidTick()
void dxfcpp::OptionSale::setValidTick (bool validTick) inline noexcept
Changes whether this event represents a valid intraday tick.
Parameters
validTick true if this event represents a valid intraday tick.
setVolatility()
void dxfcpp::OptionSale::setVolatility (double volatility) inline noexcept
Changes Black-Scholes implied volatility of the option at the time of this option sale event.
Parameters
volatility Black-Scholes implied volatility of the option at the time of this option sale event.
toGraal()
void * dxfcpp::OptionSale::toGraal () const override virtual noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Implements dxfcpp::EventType.
References toString().
toString()
std::string dxfcpp::OptionSale::toString () const override virtual noexcept
Returns a string representation of the current object.
Returns
a string representation
Reimplemented from dxfcpp::EventType.
Referenced by toGraal().
Member Data Documentation
MAX_SEQUENCE
constexpr std::uint32_t dxfcpp::OptionSale::MAX_SEQUENCE = (1U << 22U) - 1U static constexpr
Maximum allowed sequence value.
See also
OptionSale::setSequence()
Referenced by setSequence().