dxFeed Graal CXX API: dxfcpp::EventFlagsMask Class Reference
dxfcpp::EventFlagsMask Class Reference final
The event flags' mask (a set of bit flags)
#include <EventFlag.hpp>
Public Member Functions
EventFlagsMask () noexcept
Creates an empty event flags mask.
template<Integral MaskType>
EventFlagsMask (MaskType mask) noexcept
Create event flags mask by integer value.
template<typename EventFlagIt >
EventFlagsMask (EventFlagIt begin, EventFlagIt end) noexcept
Creates event flags mask by iterators of container with flags.
EventFlagsMask (std::initializer_list< EventFlag > eventFlags) noexcept
Creates event flags mask by initializer list with flags.
constexpr std::uint32_t getMask () const noexcept
Returns an integer representation of event mask.
Friends
EventFlagsMask operator| (const EventFlagsMask &eventFlagsMask, const EventFlag &eventFlag) noexcept
Performs a bit or operation with an event flags' mask and an event flag.
EventFlagsMask operator& (const EventFlagsMask &eventFlagsMask, const EventFlag &eventFlag) noexcept
Performs a bit and operation with an event flags' mask and an event flag.
EventFlagsMask operator| (const EventFlag &eventFlag1, const EventFlag &eventFlag2) noexcept
Performs a bit or operation with two event flags.
Detailed Description
The event flags' mask (a set of bit flags)
Constructor & Destructor Documentation
EventFlagsMask() [1/3]
template<Integral MaskType> dxfcpp::EventFlagsMask::EventFlagsMask (MaskType mask) inline explicit noexcept
Create event flags mask by integer value.
Template Parameters
MaskType The type of integer mask
Parameters
mask The integer mask value
EventFlagsMask() [2/3]
template<typename EventFlagIt > dxfcpp::EventFlagsMask::EventFlagsMask (EventFlagIt begin, EventFlagIt end) inline noexcept
Creates event flags mask by iterators of container with flags.
Template Parameters
EventFlagIt The iterator type
Parameters
begin The start position
end The end position
References dxfcpp::EventFlag::getFlag().
EventFlagsMask() [3/3]
dxfcpp::EventFlagsMask::EventFlagsMask (std::initializer_list< EventFlag > eventFlags) inline noexcept
Creates event flags mask by initializer list with flags.
Parameters
eventTypes The list with flags
References EventFlagsMask().
Referenced by EventFlagsMask().
Member Function Documentation
getMask()
constexpr std::uint32_t dxfcpp::EventFlagsMask::getMask () const inline constexpr noexcept
Returns an integer representation of event mask.
Returns
an integer representation
Referenced by dxfcpp::Candle::setEventFlags(), dxfcpp::OptionSale::setEventFlags(), dxfcpp::OrderBase::setEventFlags(), dxfcpp::TimeAndSale::setEventFlags(), dxfcpp::Greeks::setEventFlags(), dxfcpp::Series::setEventFlags(), dxfcpp::TheoPrice::setEventFlags(), and dxfcpp::Underlying::setEventFlags().
Friends And Related Function Documentation
operator&
EventFlagsMask operator& (const EventFlagsMask & eventFlagsMask, const EventFlag & eventFlag) friend
Performs a bit and operation with an event flags' mask and an event flag.
Parameters
eventFlagsMask The event flags' mask
eventFlag The event flag
Returns
The result (event flags' mask)
operator| [1/2]
EventFlagsMask operator| (const EventFlag & eventFlag1, const EventFlag & eventFlag2) friend
Performs a bit or operation with two event flags.
Parameters
eventType1 The first event flag
eventType2 The second event flag
Returns
The result (event flags' mask)
operator| [2/2]
EventFlagsMask operator| (const EventFlagsMask & eventFlagsMask, const EventFlag & eventFlag) friend
Performs a bit or operation with an event flags' mask and an event flag.
Parameters
eventFlagsMask The event flags' mask
eventFlag The event flag
Returns
The result (event flags' mask)