dxFeed Graal CXX API: TimeSeriesTxModelListener< E > Struct Template Reference
TimeSeriesTxModelListener< E > Struct Template Reference final
The listener for receiving time series events with the specified type from the TimeSeriesTxModel.
#include <TxModelListener.hpp>
Public Member Functions
std::string toString () const override
Returns a string representation of the current object.
Public Member Functions inherited from SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
Public Member Functions inherited from Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Static Public Member Functions
static std::shared_ptr< TimeSeriesTxModelListener< E > > create (std::function< void(const std::vector< std::shared_ptr< E > > &, bool)> onEventsReceived)
Creates a listener for receiving time series events (with instantiation by event type E and verification)
Static Public Member Functions inherited from RequireMakeShared< TimeSeriesTxModelListener< E > >
static auto createShared (Args &&...args)
Creates smart pointer to object.
Additional Inherited Members
Public Types inherited from SharedEntity
using Ptr = std::shared_ptr<SharedEntity>
The alias to a type of shared pointer to the SharedEntity object.
Detailed Description
template<Derived< TimeSeriesEvent > E>
struct TimeSeriesTxModelListener< E >
The listener for receiving time series events with the specified type from the TimeSeriesTxModel.
Member Function Documentation
create()
template<Derived< TimeSeriesEvent > E> static std::shared_ptr< TimeSeriesTxModelListener< E > > TimeSeriesTxModelListener< E >::create (std::function< void(const std::vector< std::shared_ptr< E > > &, bool)> onEventsReceived) inline static
Creates a listener for receiving time series events (with instantiation by event type E and verification)
auto listener = TimeSeriesTxModelListener<Candle>::create([](const auto &events, bool isSnapshot) {
    if (isSnapshot) {
        std::cout << "Snapshot:" << std::endl;
    } else {
        std::cout << "Update:" << std::endl;
    }
    for (const auto &e : events) {
        std::cout << "[" << e->getEventFlagsMask().toString() << "]:" << e << std::endl;
    }
    std::cout << std::endl;
});
builder->withListener(listener);
Template Parameters
E The event type.
Parameters
onEventsReceived A functional object, lambda, or function to which indexed event data will be passed.
Returns
A smart pointer to the listener.
References TimeSeriesTxModelListener< E >::create().
Referenced by TimeSeriesTxModelListener< E >::create(), and TimeSeriesTxModelListener< E >::toString().
toString()
template<Derived< TimeSeriesEvent > E> std::string TimeSeriesTxModelListener< E >::toString () const inline override virtual
Returns a string representation of the current object.
Returns
a string representation
Reimplemented from SharedEntity.
References TimeSeriesTxModelListener< E >::create().