dxFeed Graal CXX API: SymbolWrapper Struct Reference
SymbolWrapper Struct Reference final
A helper wrapper class needed to pass heterogeneous symbols using a container and convert them to internal Graal representation.
#include <SymbolWrapper.hpp>
Public Member Functions
template<ConvertibleToStringSymbol Symbol>
SymbolWrapper (Symbol &&symbol) noexcept
Constructor for any wrapped symbol.
SymbolWrapper (const StringSymbol &stringSymbol) noexcept
Constructor for any wrapped string symbol.
SymbolWrapper (const WildcardSymbol &wildcardSymbol) noexcept
Constructor for any wrapped wildcard (*) symbol.
SymbolWrapper (const IndexedEventSubscriptionSymbol &indexedEventSubscriptionSymbol) noexcept
Constructor for IndexedEventSubscriptionSymbol.
SymbolWrapper (const TimeSeriesSubscriptionSymbol &timeSeriesSubscriptionSymbol) noexcept
Constructor for TimeSeriesSubscriptionSymbol.
SymbolWrapper (const CandleSymbol &candleSymbol) noexcept
Constructor for CandleSymbol.
void * toGraal () const noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
std::string toString () const noexcept
Returns a string representation of the current object.
bool isStringSymbol () const noexcept
std::string asStringSymbol () const noexcept
bool isWildcardSymbol () const noexcept
std::optional< WildcardSymbol > asWildcardSymbol () const noexcept
bool isIndexedEventSubscriptionSymbol () const noexcept
std::optional< IndexedEventSubscriptionSymbol > asIndexedEventSubscriptionSymbol () const noexcept
bool isTimeSeriesSubscriptionSymbol () const noexcept
std::optional< TimeSeriesSubscriptionSymbol > asTimeSeriesSubscriptionSymbol () const noexcept
bool isCandleSymbol () const noexcept
std::optional< CandleSymbol > asCandleSymbol () const noexcept
Static Public Member Functions
static void freeGraal (void *graalNative)
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
static SymbolWrapper fromGraal (void *graalNative)
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
Detailed Description
A helper wrapper class needed to pass heterogeneous symbols using a container and convert them to internal Graal representation.
Constructor & Destructor Documentation
SymbolWrapper() [1/6]
template<ConvertibleToStringSymbol Symbol> SymbolWrapper::SymbolWrapper (Symbol && symbol) inline noexcept
Constructor for any wrapped symbol.
Must be implicit to wrap symbols passed to collection or container
Template Parameters
Symbol The symbol type
Parameters
symbol The symbol
SymbolWrapper() [2/6]
SymbolWrapper::SymbolWrapper (const StringSymbol & stringSymbol) inline noexcept
Constructor for any wrapped string symbol.
Must be implicit to wrap symbols passed to collection or container
Parameters
stringSymbol The wrapped string (std::string, std::string_view, const char*) symbol
SymbolWrapper() [3/6]
SymbolWrapper::SymbolWrapper (const WildcardSymbol & wildcardSymbol) inline noexcept
Constructor for any wrapped wildcard (*) symbol.
Parameters
wildcardSymbol The wrapped wildcard symbol
SymbolWrapper() [4/6]
SymbolWrapper::SymbolWrapper (const IndexedEventSubscriptionSymbol & indexedEventSubscriptionSymbol) inline noexcept
Constructor for IndexedEventSubscriptionSymbol.
Parameters
indexedEventSubscriptionSymbol The IndexedEventSubscriptionSymbol
SymbolWrapper() [5/6]
SymbolWrapper::SymbolWrapper (const TimeSeriesSubscriptionSymbol & timeSeriesSubscriptionSymbol) inline noexcept
Constructor for TimeSeriesSubscriptionSymbol.
Parameters
timeSeriesSubscriptionSymbol The TimeSeriesSubscriptionSymbol
SymbolWrapper() [6/6]
SymbolWrapper::SymbolWrapper (const CandleSymbol & candleSymbol) inline noexcept
Constructor for CandleSymbol.
Parameters
candleSymbol The CandleSymbol
Member Function Documentation
asCandleSymbol()
std::optional< CandleSymbol > SymbolWrapper::asCandleSymbol () const inline noexcept
Returns
CandleSymbol (optional) or std::nullopt if current SymbolWrapper doesn't hold CandleSymbol
asIndexedEventSubscriptionSymbol()
std::optional< IndexedEventSubscriptionSymbol > SymbolWrapper::asIndexedEventSubscriptionSymbol () const inline noexcept
Returns
IndexedEventSubscriptionSymbol (optional) or std::nullopt if current SymbolWrapper doesn't hold IndexedEventSubscriptionSymbol
asStringSymbol()
std::string SymbolWrapper::asStringSymbol () const inline noexcept
Returns
String representation of StringSymbol or an empty string
asTimeSeriesSubscriptionSymbol()
std::optional< TimeSeriesSubscriptionSymbol > SymbolWrapper::asTimeSeriesSubscriptionSymbol () const inline noexcept
Returns
TimeSeriesSubscriptionSymbol (optional) or std::nullopt if current SymbolWrapper doesn't hold TimeSeriesSubscriptionSymbol
asWildcardSymbol()
std::optional< WildcardSymbol > SymbolWrapper::asWildcardSymbol () const inline noexcept
Returns
WildcardSymbol (optional) or std::nullopt if current SymbolWrapper doesn't hold WildcardSymbol
freeGraal()
void SymbolWrapper::freeGraal (void * graalNative) static
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
References CandleSymbol::freeGraal(), IndexedEventSubscriptionSymbol::freeGraal(), StringSymbol::freeGraal(), TimeSeriesSubscriptionSymbol::freeGraal(), and WildcardSymbol::freeGraal().
Referenced by IndexedEventSubscriptionSymbol::freeGraal(), and TimeSeriesSubscriptionSymbol::freeGraal().
fromGraal()
SymbolWrapper SymbolWrapper::fromGraal (void * graalNative) static
Creates an object of the current type and fills it with data from the the dxFeed Graal SDK structure.
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
Returns
The object of current type.
Exceptions
std::invalid_argument
References CandleSymbol::fromGraal(), IndexedEventSubscriptionSymbol::fromGraal(), StringSymbol::fromGraal(), TimeSeriesSubscriptionSymbol::fromGraal(), and WildcardSymbol::fromGraal().
Referenced by IndexedEventSubscriptionSymbol::fromGraal(), and TimeSeriesSubscriptionSymbol::fromGraal().
isCandleSymbol()
bool SymbolWrapper::isCandleSymbol () const inline noexcept
Returns
true if current SymbolWrapper holds a CandleSymbol
isIndexedEventSubscriptionSymbol()
bool SymbolWrapper::isIndexedEventSubscriptionSymbol () const inline noexcept
Returns
true if current SymbolWrapper holds a IndexedEventSubscriptionSymbol
isStringSymbol()
bool SymbolWrapper::isStringSymbol () const inline noexcept
Returns
true if current SymbolWrapper holds a StringSymbol
isTimeSeriesSubscriptionSymbol()
bool SymbolWrapper::isTimeSeriesSubscriptionSymbol () const inline noexcept
Returns
true if current SymbolWrapper holds a TimeSeriesSubscriptionSymbol
isWildcardSymbol()
bool SymbolWrapper::isWildcardSymbol () const inline noexcept
Returns
true if current SymbolWrapper holds a WildcardSymbol
toGraal()
void * SymbolWrapper::toGraal () const inline noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
toString()
std::string SymbolWrapper::toString () const inline noexcept
Returns a string representation of the current object.
Returns
a string representation