dxFeed Graal CXX API: dxfcpp::Handler< void(ArgTypes...)> Struct Template Reference
dxfcpp::Handler< void(ArgTypes...)> Struct Template Reference final
A thread-safe class that allows to asynchronously notify listeners with a given signature.
#include <Handler.hpp>
Public Types
using ListenerType = std::function< void(ArgTypes...)>
The listener type.
Public Member Functions
Handler (std::size_t mainFuturesSize=MAIN_FUTURES_DEFAULT_SIZE)
Creates the new handler by specified size of circular buffer of futures.
void handle (ArgTypes... args)
Calls the listeners and pass the args to them.
void operator() (ArgTypes... args)
Calls the listeners and pass the ars to them.
std::size_t add (ListenerType &&listener)
Adds the listener to "main" group.
std::size_t addLowPriority (ListenerType &&listener)
Adds the low priority listener (to the "low priority" group) It will be called after the "main" listeners.
std::size_t operator+= (ListenerType &&listener)
Adds the listener to "main" group.
std::size_t operator%= (ListenerType &&listener)
Adds the low priority listener (to the "low priority" group).
void remove (std::size_t id)
Removes a listener by the id.
void operator-= (std::size_t id)
Removes a listener by the id.
Detailed Description
template<typename... ArgTypes>
struct dxfcpp::Handler< void(ArgTypes...)>
A thread-safe class that allows to asynchronously notify listeners with a given signature.
Listeners can be any callable entities. Listeners are placed in a future. Within one batch, listeners will be called sequentially. Futures are placed in a circular buffer and executed asynchronously.
If you need synchronous execution of listeners, but it was possible to execute them in another thread, then limit the buffer size to one.
Template Parameters
ArgTypes The arguments "signature" (example: void(int, int))
Constructor & Destructor Documentation
Handler()
template<typename... ArgTypes> dxfcpp::Handler< void(ArgTypes...)>::Handler (std::size_t mainFuturesSize = MAIN_FUTURES_DEFAULT_SIZE) inline explicit
Creates the new handler by specified size of circular buffer of futures.
Parameters
mainFuturesSize The size of the circular buffer of futures
Member Function Documentation
add()
template<typename... ArgTypes> std::size_t dxfcpp::Handler< void(ArgTypes...)>::add (ListenerType && listener) inline
Adds the listener to "main" group.
Parameters
listener The listener
Returns
The listener id
Referenced by operator+=().
addLowPriority()
template<typename... ArgTypes> std::size_t dxfcpp::Handler< void(ArgTypes...)>::addLowPriority (ListenerType && listener) inline
Adds the low priority listener (to the "low priority" group) It will be called after the "main" listeners.
Parameters
listener The listener
Returns
The listener id
Referenced by operator%=().
handle()
template<typename... ArgTypes> void dxfcpp::Handler< void(ArgTypes...)>::handle (ArgTypes... args) inline
Calls the listeners and pass the args to them.
Parameters
args The listeners arguments
Referenced by operator()().
operator%=()
template<typename... ArgTypes> std::size_t dxfcpp::Handler< void(ArgTypes...)>::operator%= (ListenerType && listener) inline
Adds the low priority listener (to the "low priority" group).
It will be called after the "main" listeners
Parameters
listener The listener
Returns
The listener id
References addLowPriority().
operator()()
template<typename... ArgTypes> void dxfcpp::Handler< void(ArgTypes...)>::operator() (ArgTypes... args) inline
Calls the listeners and pass the ars to them.
Parameters
args The listeners arguments
References handle().
operator+=()
template<typename... ArgTypes> std::size_t dxfcpp::Handler< void(ArgTypes...)>::operator+= (ListenerType && listener) inline
Adds the listener to "main" group.
Parameters
listener The listener
Returns
The listener id
References add().
operator-=()
template<typename... ArgTypes> void dxfcpp::Handler< void(ArgTypes...)>::operator-= (std::size_t id) inline
Removes a listener by the id.
Parameters
id The listener id
References remove().
remove()
template<typename... ArgTypes> void dxfcpp::Handler< void(ArgTypes...)>::remove (std::size_t id) inline
Removes a listener by the id.
Parameters
id The listener id
Referenced by operator-=().