dxFeed Graal CXX API: dxfcpp::Quote Class Reference
dxfcpp::Quote Class Reference final
Quote event is a snapshot of the best bid and ask prices, and other fields that change with each quote.
#include <Quote.hpp>
Public Types
using Ptr = std::shared_ptr< Quote >
The alias to a type of shared pointer to the Quote object.
using Unique = std::unique_ptr< Quote >
The alias to a type of unique pointer to the Quote object.
Public Types inherited from dxfcpp::MarketEvent
using Ptr = std::shared_ptr< MarketEvent >
The alias to a type of shared pointer to the MarketEvent object.
Public Types inherited from dxfcpp::EventTypeWithSymbol< std::string >
using Ptr = std::shared_ptr< EventTypeWithSymbol< std::string > >
The alias to a type of shared pointer to the EventTypeWithSymbol's child object.
Public Types inherited from dxfcpp::EventType
using Ptr = std::shared_ptr< EventType >
The alias to a type of shared pointer to the EventType object.
Public Types inherited from dxfcpp::SharedEntity
using Ptr = std::shared_ptr< SharedEntity >
The alias to a type of shared pointer to the SharedEntity object.
Public Types inherited from dxfcpp::LastingEvent
using Ptr = std::shared_ptr< LastingEvent >
The alias to a type of shared pointer to the LastingEvent object.
Public Member Functions
void * toGraal () const noexcept override
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Quote () noexcept=default
Creates new quote event with default values.
Quote (std::string eventSymbol) noexcept
Creates new quote event with the specified event symbol.
Quote & withEventSymbol (const std::string &eventSymbol) noexcept
Changes event's symbol and returns the current quote.
Quote::Ptr withEventSymbolShared (const std::string &eventSymbol) noexcept
Changes event's symbol and returns a shared pointer to the current quote.
Quote & withEventTime (std::int64_t eventTime) noexcept
Changes event's creation time and returns the current quote.
Quote::Ptr withEventTimeShared (std::int64_t eventTime) noexcept
Changes event's creation time and returns a shared pointer to the current quote.
std::int32_t getSequence () const noexcept
Returns sequence number of this quote to distinguish quotes that have the same time.
void setSequence (std::int32_t sequence) noexcept
Changes sequence number of this quote.
Quote & withSequence (std::int32_t sequence) noexcept
Changes sequence number of this quote and returns the current quote.
Quote::Ptr withSequenceShared (std::int32_t sequence) noexcept
Changes sequence number of this quote and returns a shared pointer to the current quote.
std::int64_t getTime () const noexcept
Returns time of the last bid or ask change.
std::int64_t getTimeNanos () const noexcept
Returns time of the last bid or ask change in nanoseconds.
std::int32_t getTimeNanoPart () const noexcept
Returns microseconds and nanoseconds part of time of the last bid or ask change.
void setTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds part of time of the last bid or ask change.
Quote & withTimeNanoPart (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds part of time of the last bid or ask change and returns the current quote.
Quote::Ptr withTimeNanoPartShared (std::int32_t timeNanoPart) noexcept
Changes microseconds and nanoseconds part of time of the last bid or ask change and returns a shared pointer to the current quote.
std::int64_t getBidTime () const noexcept
Returns time of the last bid change.
void setBidTime (std::int64_t bidTime) noexcept
Changes time of the last bid change.
Quote & withBidTime (std::int64_t bidTime) noexcept
Changes time of the last bid change and returns the current quote.
Quote::Ptr withBidTimeShared (std::int64_t bidTime) noexcept
Changes time of the last bid change and returns a shared pointer to the current quote.
std::int16_t getBidExchangeCode () const noexcept
Returns bid exchange code.
std::string getBidExchangeCodeString () const noexcept
Returns bid exchange code as UTF8 string.
void setBidExchangeCode (char bidExchangeCode) noexcept
Changes bid exchange code.
Quote & withBidExchangeCode (char bidExchangeCode) noexcept
Changes bid exchange code and returns the current quote.
Quote::Ptr withBidExchangeCodeShared (char bidExchangeCode) noexcept
Changes bid exchange code and returns a shared pointer to the current quote.
void setBidExchangeCode (std::int16_t bidExchangeCode) noexcept
Changes bid exchange code.
Quote & withBidExchangeCode (std::int16_t bidExchangeCode) noexcept
Changes bid exchange code and returns the current quote.
Quote::Ptr withBidExchangeCodeShared (std::int16_t bidExchangeCode) noexcept
Changes bid exchange code and returns a shared pointer to the current quote.
double getBidPrice () const noexcept
Returns bid price.
void setBidPrice (double bidPrice) noexcept
Changes bid price.
Quote & withBidPrice (double bidPrice) noexcept
Changes bid price and returns the current quote.
Quote::Ptr withBidPriceShared (double bidPrice) noexcept
Changes bid price and returns a shared pointer to the current quote.
double getBidSize () const noexcept
Returns bid size.
void setBidSize (double bidSize) noexcept
Changes bid size.
Quote & withBidSize (double bidSize) noexcept
Changes bid size and returns the current quote.
Quote::Ptr withBidSizeShared (double bidSize) noexcept
Changes bid size and returns a shared pointer to the current quote.
std::int64_t getAskTime () const noexcept
Returns time of the last ask change.
void setAskTime (std::int64_t askTime) noexcept
Changes time of the last ask change.
Quote & withAskTime (std::int64_t askTime) noexcept
Changes time of the last ask change and returns the current quote.
Quote::Ptr withAskTimeShared (std::int64_t askTime) noexcept
Changes time of the last ask change and returns a shared pointer to the current quote.
std::int16_t getAskExchangeCode () const noexcept
Returns ask exchange code.
std::string getAskExchangeCodeString () const noexcept
Returns ask exchange code as UTF8 string.
void setAskExchangeCode (char askExchangeCode) noexcept
Changes ask exchange code.
Quote & withAskExchangeCode (char askExchangeCode) noexcept
Changes ask exchange code and returns the current quote.
Quote::Ptr withAskExchangeCodeShared (char askExchangeCode) noexcept
Changes ask exchange code and returns a shared pointer to the current quote.
void setAskExchangeCode (std::int16_t askExchangeCode) noexcept
Changes ask exchange code.
Quote & withAskExchangeCode (std::int16_t askExchangeCode) noexcept
Changes ask exchange code and returns the current quote.
Quote::Ptr withAskExchangeCodeShared (std::int16_t askExchangeCode) noexcept
Changes ask exchange code and returns a shared pointer to the current quote.
double getAskPrice () const
Returns ask price.
void setAskPrice (double askPrice)
Changes ask price.
Quote & withAskPrice (double askPrice) noexcept
Changes ask price and returns the current quote.
Quote::Ptr withAskPriceShared (double askPrice) noexcept
Changes ask price and returns a shared pointer to the current quote.
double getAskSize () const
Returns ask size.
void setAskSize (double askSize)
Changes ask size.
Quote & withAskSize (double askSize) noexcept
Changes ask size and returns the current quote.
Quote::Ptr withAskSizeShared (double askSize) noexcept
Changes ask size and returns a shared pointer to the current quote.
std::string toString () const noexcept override
Returns a string representation of the current object.
Public Member Functions inherited from dxfcpp::MarketEvent
const std::string & getEventSymbol () const &noexcept override
Returns symbol of this event.
const std::optional< std::string > & getEventSymbolOpt () const &noexcept override
Returns symbol of this event.
void setEventSymbol (const std::string &eventSymbol) noexcept override
Changes symbol of this event.
std::int64_t getEventTime () const noexcept override
Returns time when event was created or zero when time is not available.
void setEventTime (std::int64_t eventTime) noexcept override
Changes event creation time.
Public Member Functions inherited from dxfcpp::SharedEntity
template<typename T >
bool is () const noexcept
Checks that pointer to the current type could be converted to type T* In other words: whether type T belongs to the type hierarchy in which the current type resides.
template<typename T >
std::shared_ptr< T > sharedAs () noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
template<typename T >
std::shared_ptr< T > sharedAs () const noexcept
Returns a pointer to the current object wrapped in a smart pointer to type T.
Public Member Functions inherited from dxfcpp::Entity
virtual ~Entity () noexcept=default
The default virtual d-tor.
Static Public Member Functions
static void freeGraal (void *graalNative) noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Static Public Attributes
static constexpr std::uint32_t MAX_SEQUENCE = (1U << 22U) - 1U
Maximum allowed sequence value.
static const EventTypeEnum & TYPE = EventTypeEnum::QUOTE
Type identifier and additional information about the current event class.
Additional Inherited Members
Protected Member Functions inherited from dxfcpp::MarketEvent
MarketEvent (std::string eventSymbol) noexcept
Protected constructor for concrete implementation classes that initializes eventSymbol property.
Detailed Description
Quote event is a snapshot of the best bid and ask prices, and other fields that change with each quote.
It represents the most recent information that is available about the best quote on the market at any given moment of time.
Bid corresponds to the best (maximal price) order to buy, ask corresponds to the best (minimal price) order to sell.
Constructor & Destructor Documentation
Quote()
dxfcpp::Quote::Quote (std::string eventSymbol) inline explicit noexcept
Creates new quote event with the specified event symbol.
Parameters
eventSymbol The event symbol.
Member Function Documentation
freeGraal()
void dxfcpp::Quote::freeGraal (void * graalNative) static noexcept
Releases the memory occupied by the dxFeed Graal SDK structure (recursively if necessary).
Parameters
graalNative The pointer to the dxFeed Graal SDK structure.
getAskExchangeCode()
std::int16_t dxfcpp::Quote::getAskExchangeCode () const noexcept
Returns ask exchange code.
Returns
The ask exchange code.
getAskExchangeCodeString()
std::string dxfcpp::Quote::getAskExchangeCodeString () const noexcept
Returns ask exchange code as UTF8 string.
Returns
The ask exchange code as UTF8 string.
getAskPrice()
double dxfcpp::Quote::getAskPrice () const inline
Returns ask price.
Returns
The ask price.
getAskSize()
double dxfcpp::Quote::getAskSize () const inline
Returns ask size.
Returns
The ask size
getAskTime()
std::int64_t dxfcpp::Quote::getAskTime () const inline noexcept
Returns time of the last ask change.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
This time is always transmitted with seconds precision, so the result of this method is usually a multiple of 1000.
Returns
The time of the last ask change.
getBidExchangeCode()
std::int16_t dxfcpp::Quote::getBidExchangeCode () const noexcept
Returns bid exchange code.
Returns
The bid exchange code.
getBidExchangeCodeString()
std::string dxfcpp::Quote::getBidExchangeCodeString () const noexcept
Returns bid exchange code as UTF8 string.
Returns
The bid exchange code as UTF8 string.
getBidPrice()
double dxfcpp::Quote::getBidPrice () const inline noexcept
Returns bid price.
Returns
The bid price.
getBidSize()
double dxfcpp::Quote::getBidSize () const inline noexcept
Returns bid size.
Returns
The bid size
getBidTime()
std::int64_t dxfcpp::Quote::getBidTime () const inline noexcept
Returns time of the last bid change.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
This time is always transmitted with seconds precision, so the result of this method is usually a multiple of 1000.
Returns
The time of the last bid change.
getSequence()
std::int32_t dxfcpp::Quote::getSequence () const inline noexcept
Returns sequence number of this quote to distinguish quotes that have the same time.
This sequence number does not have to be unique and does not need to be sequential. Sequence can range from 0 to Quote::MAX_SEQUENCE.
Returns
sequence of this quote.
References MAX_SEQUENCE.
getTime()
std::int64_t dxfcpp::Quote::getTime () const inline noexcept
Returns time of the last bid or ask change.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
Returns
The time of the last bid or ask change.
Referenced by getTimeNanos().
getTimeNanoPart()
std::int32_t dxfcpp::Quote::getTimeNanoPart () const inline noexcept
Returns microseconds and nanoseconds part of time of the last bid or ask change.
Returns
The microseconds and nanoseconds part of time of the last bid or ask change.
getTimeNanos()
std::int64_t dxfcpp::Quote::getTimeNanos () const inline noexcept
Returns time of the last bid or ask change in nanoseconds.
Time is measured in nanoseconds between the current time and midnight, January 1, 1970 UTC.
Returns
The time of the last bid or ask change in nanoseconds.
References getTime().
setAskExchangeCode() [1/2]
void dxfcpp::Quote::setAskExchangeCode (char askExchangeCode) noexcept
Changes ask exchange code.
Parameters
askExchangeCode The ask exchange code.
Referenced by withAskExchangeCode(), and withAskExchangeCodeShared().
setAskExchangeCode() [2/2]
void dxfcpp::Quote::setAskExchangeCode (std::int16_t askExchangeCode) noexcept
Changes ask exchange code.
Parameters
askExchangeCode The ask exchange code.
Referenced by withAskExchangeCode(), and withAskExchangeCodeShared().
setAskPrice()
void dxfcpp::Quote::setAskPrice (double askPrice) inline
Changes ask price.
Parameters
askPrice The ask price.
Referenced by withAskPrice(), and withAskPriceShared().
setAskSize()
void dxfcpp::Quote::setAskSize (double askSize) inline
Changes ask size.
Parameters
askSize The ask size.
Referenced by withAskSize(), and withAskSizeShared().
setAskTime()
void dxfcpp::Quote::setAskTime (std::int64_t askTime) inline noexcept
Changes time of the last ask change.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
You can set the actual millisecond-precision time here to publish event and the millisecond part will make the Quote::getTime() of this quote even precise up to a millisecond.
Parameters
askTime The time of the last ask change.
Referenced by withAskTime(), and withAskTimeShared().
setBidExchangeCode() [1/2]
void dxfcpp::Quote::setBidExchangeCode (char bidExchangeCode) noexcept
Changes bid exchange code.
Parameters
bidExchangeCode The bid exchange code.
Referenced by withBidExchangeCode(), and withBidExchangeCodeShared().
setBidExchangeCode() [2/2]
void dxfcpp::Quote::setBidExchangeCode (std::int16_t bidExchangeCode) noexcept
Changes bid exchange code.
Parameters
bidExchangeCode bid exchange code.
Referenced by withBidExchangeCode(), and withBidExchangeCodeShared().
setBidPrice()
void dxfcpp::Quote::setBidPrice (double bidPrice) inline noexcept
Changes bid price.
Parameters
bidPrice The bid price.
Referenced by withBidPrice(), and withBidPriceShared().
setBidSize()
void dxfcpp::Quote::setBidSize (double bidSize) inline noexcept
Changes bid size.
Parameters
bidSize The bid size.
Referenced by withBidSize(), and withBidSizeShared().
setBidTime()
void dxfcpp::Quote::setBidTime (std::int64_t bidTime) inline noexcept
Changes time of the last bid change.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
You can set the actual millisecond-precision time here to publish event and the millisecond part will make the Quote::getTime() of this quote even precise up to a millisecond.
Parameters
bidTime The time of the last bid change.
Referenced by withBidTime(), and withBidTimeShared().
setSequence()
void dxfcpp::Quote::setSequence (std::int32_t sequence) inline noexcept
Changes sequence number of this quote.
Parameters
sequence The sequence.
See also
Quote::getSequence()
References MAX_SEQUENCE.
Referenced by withSequence(), and withSequenceShared().
setTimeNanoPart()
void dxfcpp::Quote::setTimeNanoPart (std::int32_t timeNanoPart) inline noexcept
Changes microseconds and nanoseconds part of time of the last bid or ask change.
This method changes Quote::getTimeNanos() result.
Parameters
timeNanoPart The microseconds and nanoseconds part of time of the last bid or ask change.
Referenced by withTimeNanoPart(), and withTimeNanoPartShared().
toGraal()
void * dxfcpp::Quote::toGraal () const override virtual noexcept
Allocates memory for the dxFeed Graal SDK structure (recursively if necessary).
Fills the dxFeed Graal SDK structure's fields by the data of the current entity (recursively if necessary). Returns the pointer to the filled structure.
Returns
The pointer to the filled dxFeed Graal SDK structure
Implements dxfcpp::EventType.
References toString().
toString()
std::string dxfcpp::Quote::toString () const override virtual noexcept
Returns a string representation of the current object.
Returns
A string representation.
Reimplemented from dxfcpp::EventType.
Referenced by toGraal().
withAskExchangeCode() [1/2]
Quote& dxfcpp::Quote::withAskExchangeCode (char askExchangeCode) inline noexcept
Changes ask exchange code and returns the current quote.
Parameters
askExchangeCode The ask exchange code.
Returns
The current quote
References setAskExchangeCode().
withAskExchangeCode() [2/2]
Quote& dxfcpp::Quote::withAskExchangeCode (std::int16_t askExchangeCode) inline noexcept
Changes ask exchange code and returns the current quote.
Parameters
askExchangeCode The ask exchange code.
Returns
The current quote.
References setAskExchangeCode().
withAskExchangeCodeShared() [1/2]
Quote::Ptr dxfcpp::Quote::withAskExchangeCodeShared (char askExchangeCode) inline noexcept
Changes ask exchange code and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
askExchangeCode The ask exchange code.
Returns
A shared pointer to the current quote.
References setAskExchangeCode().
withAskExchangeCodeShared() [2/2]
Quote::Ptr dxfcpp::Quote::withAskExchangeCodeShared (std::int16_t askExchangeCode) inline noexcept
Changes ask exchange code and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
askExchangeCode The ask exchange code.
Returns
A shared pointer to the current quote.
References setAskExchangeCode().
withAskPrice()
Quote& dxfcpp::Quote::withAskPrice (double askPrice) inline noexcept
Changes ask price and returns the current quote.
Parameters
askPrice The ask price.
Returns
The current quote
References setAskPrice().
withAskPriceShared()
Quote::Ptr dxfcpp::Quote::withAskPriceShared (double askPrice) inline noexcept
Changes ask price and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
askPrice The ask price.
Returns
A shared pointer to the current quote.
References setAskPrice().
withAskSize()
Quote& dxfcpp::Quote::withAskSize (double askSize) inline noexcept
Changes ask size and returns the current quote.
Parameters
askSize The ask size.
Returns
The current quote.
References setAskSize().
withAskSizeShared()
Quote::Ptr dxfcpp::Quote::withAskSizeShared (double askSize) inline noexcept
Changes ask size and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
askSize The ask size.
Returns
A shared pointer to the current quote.
References setAskSize().
withAskTime()
Quote& dxfcpp::Quote::withAskTime (std::int64_t askTime) inline noexcept
Changes time of the last ask change and returns the current quote.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
You can set the actual millisecond-precision time here to publish event and the millisecond part will make the Quote::getTime() of this quote even precise up to a millisecond.
Parameters
askTime The time of the last ask change.
Returns
The current quote.
References setAskTime().
withAskTimeShared()
Quote::Ptr dxfcpp::Quote::withAskTimeShared (std::int64_t askTime) inline noexcept
Changes time of the last ask change and returns a shared pointer to the current quote.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
You can set the actual millisecond-precision time here to publish event and the millisecond part will make the Quote::getTime() of this quote even precise up to a millisecond.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
askTime The time of the last ask change.
Returns
A shared pointer to the current quote.
References setAskTime().
withBidExchangeCode() [1/2]
Quote& dxfcpp::Quote::withBidExchangeCode (char bidExchangeCode) inline noexcept
Changes bid exchange code and returns the current quote.
Parameters
bidExchangeCode The bid exchange code.
Returns
The current quote
References setBidExchangeCode().
withBidExchangeCode() [2/2]
Quote& dxfcpp::Quote::withBidExchangeCode (std::int16_t bidExchangeCode) inline noexcept
Changes bid exchange code and returns the current quote.
Parameters
bidExchangeCode The bid exchange code.
Returns
The current quote.
References setBidExchangeCode().
withBidExchangeCodeShared() [1/2]
Quote::Ptr dxfcpp::Quote::withBidExchangeCodeShared (char bidExchangeCode) inline noexcept
Changes bid exchange code and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
bidExchangeCode The bid exchange code.
Returns
A shared pointer to the current quote.
References setBidExchangeCode().
withBidExchangeCodeShared() [2/2]
Quote::Ptr dxfcpp::Quote::withBidExchangeCodeShared (std::int16_t bidExchangeCode) inline noexcept
Changes bid exchange code and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
bidExchangeCode The bid exchange code.
Returns
A shared pointer to the current quote.
References setBidExchangeCode().
withBidPrice()
Quote& dxfcpp::Quote::withBidPrice (double bidPrice) inline noexcept
Changes bid price and returns the current quote.
Parameters
bidPrice The bid price.
Returns
The current quote
References setBidPrice().
withBidPriceShared()
Quote::Ptr dxfcpp::Quote::withBidPriceShared (double bidPrice) inline noexcept
Changes bid price and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
bidPrice The bid price.
Returns
A shared pointer to the current quote.
References setBidPrice().
withBidSize()
Quote& dxfcpp::Quote::withBidSize (double bidSize) inline noexcept
Changes bid size and returns the current quote.
Parameters
bidSize The bid size.
Returns
The current quote.
References setBidSize().
withBidSizeShared()
Quote::Ptr dxfcpp::Quote::withBidSizeShared (double bidSize) inline noexcept
Changes bid size and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
bidSize The bid size.
Returns
A shared pointer to the current quote.
References setBidSize().
withBidTime()
Quote& dxfcpp::Quote::withBidTime (std::int64_t bidTime) inline noexcept
Changes time of the last bid change and returns the current quote.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
You can set the actual millisecond-precision time here to publish event and the millisecond part will make the Quote::getTime() of this quote even precise up to a millisecond.
Parameters
bidTime The time of the last bid change.
Returns
The current quote.
References setBidTime().
withBidTimeShared()
Quote::Ptr dxfcpp::Quote::withBidTimeShared (std::int64_t bidTime) inline noexcept
Changes time of the last bid change and returns a shared pointer to the current quote.
Time is measured in milliseconds between the current time and midnight, January 1, 1970 UTC.
You can set the actual millisecond-precision time here to publish event and the millisecond part will make the Quote::getTime() of this quote even precise up to a millisecond.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
bidTime The time of the last bid change.
Returns
A shared pointer to the current quote.
References setBidTime().
withEventSymbol()
Quote& dxfcpp::Quote::withEventSymbol (const std::string & eventSymbol) inline noexcept
Changes event's symbol and returns the current quote.
Parameters
eventSymbol The symbol of this event.
Returns
The current quote.
withEventSymbolShared()
Quote::Ptr dxfcpp::Quote::withEventSymbolShared (const std::string & eventSymbol) inline noexcept
Changes event's symbol and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
eventSymbol The symbol of this event.
Returns
A shared pointer to the current quote.
withEventTime()
Quote& dxfcpp::Quote::withEventTime (std::int64_t eventTime) inline noexcept
Changes event's creation time and returns the current quote.
Parameters
eventTime the difference, measured in milliseconds, between the event creation time and midnight, January 1, 1970 UTC.
Returns
The current quote.
References dxfcpp::MarketEvent::setEventTime().
withEventTimeShared()
Quote::Ptr dxfcpp::Quote::withEventTimeShared (std::int64_t eventTime) inline noexcept
Changes event's creation time and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
eventTime the difference, measured in milliseconds, between the event creation time and midnight, January 1, 1970 UTC.
Returns
A shared pointer to the current quote.
References dxfcpp::MarketEvent::setEventTime().
withSequence()
Quote& dxfcpp::Quote::withSequence (std::int32_t sequence) inline noexcept
Changes sequence number of this quote and returns the current quote.
Parameters
sequence The sequence.
Returns
The current quote.
See also
Quote::getSequence()
References setSequence().
withSequenceShared()
Quote::Ptr dxfcpp::Quote::withSequenceShared (std::int32_t sequence) inline noexcept
Changes sequence number of this quote and returns a shared pointer to the current quote.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
sequence The sequence.
Returns
A shared pointer to the current quote.
See also
Quote::getSequence()
References setSequence().
withTimeNanoPart()
Quote& dxfcpp::Quote::withTimeNanoPart (std::int32_t timeNanoPart) inline noexcept
Changes microseconds and nanoseconds part of time of the last bid or ask change and returns the current quote.
This method changes Quote::getTimeNanos() result.
Parameters
timeNanoPart The microseconds and nanoseconds part of time of the last bid or ask change.
Returns
The current quote.
References setTimeNanoPart().
withTimeNanoPartShared()
Quote::Ptr dxfcpp::Quote::withTimeNanoPartShared (std::int32_t timeNanoPart) inline noexcept
Changes microseconds and nanoseconds part of time of the last bid or ask change and returns a shared pointer to the current quote.
This method changes Quote::getTimeNanos() result.
Warning
Please do not use this method unless the object was created with std::shared_ptr<Quote>(new Quote(...)) or std::make_shared<Quote>(...)
Parameters
timeNanoPart The microseconds and nanoseconds part of time of the last bid or ask change.
Returns
A shared pointer to the current quote.
References setTimeNanoPart().
Member Data Documentation
MAX_SEQUENCE
constexpr std::uint32_t dxfcpp::Quote::MAX_SEQUENCE = (1U << 22U) - 1U static constexpr
Maximum allowed sequence value.
See also
Quote::setSequence()
Referenced by getSequence(), and setSequence().