# Copyright (c) 2024 Devexperts LLC.
# SPDX-License-Identifier: MPL-2.0

name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  XCODE_VERSION: '15.0'
  GCC_VERSION: '12'

jobs:
  build:
    strategy:
      matrix:
        #        os: [windows-latest, macos-latest, ubuntu-latest]
        os: [ windows-latest, macos-13, ubuntu-22.04, macos-14 ]
        buildType: [ Release ]
        cores: [ 4 ]
        exclude:
          - os: macos-14
            cores: 4
        include:
          - os: macos-14
            cores: 3

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        if: ${{ contains(matrix.os, 'macos') }}
        run: sudo xcode-select -s '/Applications/Xcode_${{env.XCODE_VERSION}}.app/Contents/Developer'

      - name: Prepare build
        run: |
          ls
          mkdir ${{github.workspace}}/build    

      - name: Configure CMake (!Ubuntu)
        if: ${{ !contains(matrix.os, 'ubuntu') }}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildType}} -DDXFCXX_BUILD_DOC=OFF

      - name: Configure CMake (Ubuntu)
        env:
          CC: gcc-${{env.GCC_VERSION}}
          CXX: g++-${{env.GCC_VERSION}}
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildType}} -DDXFCXX_BUILD_DOC=OFF

      - name: Build (!Win)
        if: ${{ !contains(matrix.os, 'win') }}
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.buildType}} -j ${{matrix.cores}}

      - name: Build (Win)
        if: ${{ contains(matrix.os, 'win') }}
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.buildType}} -j ${{matrix.cores}} -- /p:CL_MPCount=${{matrix.cores}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.buildType}} --extra-verbose
