# Copyright (c) 2023 Devexperts LLC.
# SPDX-License-Identifier: MPL-2.0

name: CI

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z]+'
      - '[a-zA-Z]+-[0-9]+\.[0-9]+\.[0-9]+'
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: 'Release'

jobs:
  build:
    strategy:
      matrix:
        #        os: [windows-latest, macos-latest, ubuntu-latest]
        os: [ windows-latest, macos-latest, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Prepare build
        run: |
          ls
          mkdir ${{github.workspace}}/build    

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --extra-verbose
