# Copyright (c) 2023 Devexperts LLC.
# SPDX-License-Identifier: MPL-2.0

name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: 'Release'
  XCODE_VERSION: '15.0'
  GCC_VERSION: '12'

jobs:
  build:
    strategy:
      matrix:
        #        os: [windows-latest, macos-latest, ubuntu-latest]
        os: [ windows-latest, macos-13, macos-13-x1, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        if: ${{ contains(matrix.os, 'macos') }}
        run: sudo xcode-select -s '/Applications/Xcode_${{env.XCODE_VERSION}}.app/Contents/Developer'

      - name: Select gcc version
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          export CC=gcc-${{env.GCC_VERSION}}
          export CXX=g++-${{env.GCC_VERSION}}        

      - name: Prepare build
        run: |
          ls
          mkdir ${{github.workspace}}/build    

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --extra-verbose
